### ISSUE TITLE
Cannot access bridged docker port

### ISSUE THREAD

**Issue by mixxen** [mesosphere/marathon#753] opened 2014-10-29 23:15 UTC
I've started a cluster using the digitalocean.mesophere.com web ui and I'm trying to run a simple nodejs express application in a docker via marathon. Marathon is able run the docker container on the slaves, but I cannot access the bridged port. If I run the docker from the command line on the slave, I am able to access the port. ```docker ps``` on one of the slaves is shown below (05a is run by marathon, c55 is run from command line with ```docker run -d -p 31001:3000 mixxen/express```)

```
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS                     NAMES
05a1a1754cba        mixxen/express:latest   "npm start"         17 minutes ago      Up 17 minutes       0.0.0.0:31000->3000/tcp   mesos-e4f05672-8e8c-44ca-a47c-94cebe7170ce   
c55b155d8c89        mixxen/express:latest   "npm start"         19 hours ago        Up 19 hours         0.0.0.0:31001->3000/tcp   sad_morse                                    
```

Below is the JSON sent to /v2/apps

```
{
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "mixxen/express",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": "3000", "hostPort": "0", "protocol": "tcp" }
      ]
     }
  },
  "id": "express3",
  "instances": "1",
  "cpus": ".1",
  "mem": "64",
  "uris": []
}
```

I am able to see ```http://serverip:31001``` but not ```http://serverip:31000```

**Comment by saulshanabrook** [comment] 2015-05-17 15:50
yeah this would be huge

**Comment by kolloch** [comment] 2015-05-18 14:08
#1254 is probably a duplicate of this but a bit more specific. Therefore I close this issue.

**Closed by kolloch** 2015-05-18 14:08 UTC
