### ISSUE TITLE
Marathon should pull the latest image before running it

### ISSUE THREAD

**Issue by djannot** [mesosphere/marathon#943] opened 2015-01-06 16:37 UTC
I have a 3 nodes cluster and I've started an app with 4 instances, then I found that one instance was running an old version of the image

**Comment by lukaswelte** [comment] 2015-01-06 16:40
A duplicate of #880 

Quick answer.. use tagged docker images. Then you will be fine and you get some versioning in addition for free ;)

**Comment by drexin** [comment] 2015-01-06 16:50
Right, we recommend using tags, because otherwise rollbacks would not be possible.

I will close this, as this is a duplicate.

**Closed by drexin** 2015-01-06 16:50 UTC

**Comment by djannot** [comment] 2015-01-06 16:53
Perfect, thanks guys

**Comment by ConnorDoyle** [comment] 2015-01-06 17:36
See also #899 -- this will be added to Marathon after Mesos 0.22.0 is released.

**Comment by djannot** [comment] 2015-01-06 17:55
Awesome !
