### ISSUE TITLE
Make tasks exponentially back off, even if they end up as "TASK_FINISHED", but just finish really rapidly

### ISSUE THREAD

**Issue by solarkennedy** [mesosphere/marathon#1470] opened 2015-05-05 21:24 UTC
I'm a big fan of the exponential backoff.

But recently we had a situation where it was not taking affect on a "failing" service that was churning very rapidly. (load, disk, sandboxes, docker, etc)

Marathon was doing its darndness to keep the service up, but the task was finishing cleanly (exit 0). so it was TASK_FINISHED.

I understand the need to reset the exponential backoff at some point when the service "works", but what if that reset happened after... a healthcheck passes? Not everybody uses healthckecks, but if they were set, then we could use those to know if a service is "really" healthy.

Or, instead of just relying on the exit state
https://github.com/mesosphere/marathon/blob/8bf0616286a486b0e672e4e69ac5363a7bc6c6a8/src/main/scala/mesosphere/marathon/MarathonScheduler.scala#L131-L134
... maybe it could assume that if it didn't stay up for say, at least 60 seconds, then it didn't work?

Would you accept a PR for any of the proposed solutions? Or an alternative way to handle this situation (we may be just doing it wrong)

cc @evankrall @mrtyler

**Comment by kolloch** [comment] 2015-05-06 13:30
Since Marathon is built for long running tasks, I agree that just finishing is usually an error condition.

Just that I am not missing any corner cases, are there cases where TASK_FINISHED does not indicate failure in the case of Marathon, @drexin ?

**Comment by kolloch** [comment] 2015-07-21 09:49
Hi @solarkennedy, sorry that this not in our focus in the past. It is an important topic. Would you think that this is basically a duplicate of #1111? Can we continue the discussion there? Otherwise please reopen and point out the differences.

**Closed by kolloch** 2015-07-21 09:49 UTC

**Comment by EvanKrall** [comment] 2015-07-21 17:43
If #1111 allows us to have marathon slow down launching of new task for apps that exit immediately, then I think it'll work for us.

**Comment by solarkennedy** [comment] 2015-07-22 03:05
Yes, lets continue on #1111.

**Comment by kolloch** [comment] 2015-07-22 09:10
@EvanKrall that might also be solved by #1504 which is open
