### ISSUE TITLE
Allow a constraint that forces a service to start on all slaves in a cluster. 

### ISSUE THREAD

**Issue by rodrickbrown** [mesosphere/marathon#2784] opened 2015-12-07 03:24 UTC
When using a service like the spark-shuffle service it would be nice to specify a constraint that could have the service start on all nodes in the cluster since this service needs to be running on all nodes where the spark jobs would run.

**Comment by aldipower** [comment] 2015-12-07 13:13
Hi @rodrickbrown !

I think you could achieve this with the UNIQUE constraint.
You can set this operator to the _hostname_ and then scale to that many instances you have nodes.
Didn't tested this, but should work.

### UNIQUE operator

`UNIQUE` tells Marathon to enforce uniqueness of the attribute across all of an app's tasks. For example the following constraint ensures that there is only one app task running on each host:

``` bash
$ curl -X POST -H "Content-type: application/json" localhost:8080/v2/apps -d '{
    "id": "sleep-unique",
    "cmd": "sleep 60",
    "instances": 3,
    "constraints": [["hostname", "UNIQUE"]]
  }'
```

https://github.com/mesosphere/marathon/blob/master/docs/docs/constraints.md

**Comment by gkleiman** [comment] 2015-12-09 12:10
Dupe of #846.

**Closed by gkleiman** 2015-12-09 12:10 UTC
Labels: question
