### ISSUE TITLE
Spawning tasks on the whole cluster

### ISSUE THREAD

**Issue by ktf** [mesosphere/marathon#1264] opened 2015-03-03 16:09 UTC
I need to spawn a cleanup process on each machine of the cluster once per day. Right now I'm using:

```
constraints: [["hostname", "UNIQUE"], ["hostname", "LIKE", "mycluster.*"]]
```

which does the job but then it requires me to know the number of machines I've active in the cluster which I'd like not to hardcode. Is there any better way of doing this?

**Comment by drexin** [comment] 2015-03-03 16:21
We can't guarantee that a process will reach every node in the cluster, because Mesos schedules the offers.

**Comment by ktf** [comment] 2015-03-03 19:48
that would be fine, I would simply like to say "reach as many as possible
on the cluster"

**Comment by gomes** [comment] 2015-05-05 14:39
I think this can be solved improving the task api, supporting scale by value, so you can add 1 task more for the app, then you can call it when you are provisioning your new slave.

**Comment by drexin** [comment] 2015-05-05 14:43
Assuming you have multiple frameworks running, there's no guarantee that Marathon will ever receive an offer from that slave.

**Comment by gomes** [comment] 2015-05-05 14:52
Yes, but you can solve it using constraints. I create some special slaves that will only run my LB's, exposing them to the internet, then I used something like that, ["exclusive", "UNLIKE", ".*"]. I can do that to slaves that will be used for cassandra, for example.

I use Qubit Bamboo for Service Discovery and I run one bamboo instance in every slave I create. I have to scale it manually.

**Comment by gomes** [comment] 2015-05-06 18:42
I think https://github.com/mesosphere/marathon/issues/1015 can be solved using roles too.

**Comment by air** [comment] 2015-07-29 22:17
Closing as dupe of #846.

**Closed by air** 2015-07-29 22:17 UTC
