### ISSUE TITLE
Transactionality for scaling marathon APIs

### ISSUE THREAD

**Issue by Ferdiism** [mesosphere/marathon#1642] opened 2015-06-11 12:54 UTC
MARATHON-151

**Comment by Ferdiism** [comment] 2015-06-11 13:02
@air, do you have additional information here?

**Comment by air** [comment] 2015-07-08 18:16
hey @Ferdiism didn't we talk to the customer on this while we were at the offsite? Maybe you have notes.

**Comment by aquamatthias** [comment] 2015-07-09 12:57
This is a duplicate of #1709

**Closed by aquamatthias** 2015-07-09 12:57 UTC
Labels: question
