### ISSUE TITLE
Marathon 0.11 ubuntu package looks to be broken

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/marathon#2384] opened 2015-10-08 23:39 UTC
The Marathon 0.11 ubuntu package on 14.04 depends on java8-runtime-headless, which is not provided.

**Comment by gkleiman** [comment] 2015-10-09 14:10
Marathon v0.11.0 depends on Java 8. Java 8 is not included in old versions of Ubuntu, but we provided instructions to install it from Oracle's PPA.

Dupe of #2357

**Closed by gkleiman** 2015-10-09 14:10 UTC

**Comment by mgummelt** [comment] 2015-10-09 18:44
OK, but note that download page is not the only place that with marathon install instructions.  For example, these pages are also now broken:

http://open.mesosphere.com/getting-started/datacenter/install/
https://open.mesosphere.com/getting-started/developer/single-node-install/

**Comment by mgummelt** [comment] 2015-10-09 18:45
Better would be to just support marathon on 15.04, where java 8 is available in the universe

**Comment by scalp42** [comment] 2015-11-10 21:47
@gkleiman any way to not force the dependency on us ? This should be let to the user.

In my example, using Ubuntu 14.04 LTS:

```
The following packages have unmet dependencies:
marathon : Depends: java8-runtime-headless but it is not installable
```

I do *not* want to install the 3rd party PPA as you instruct. Our nodes are provisioned to pull from Oracle directly:

```
root@mesos-1:/usr/lib/jvm# java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

**Comment by gkleiman** [comment] 2015-11-11 09:55
@scalp42 if you have already satisfied the dependency by installing Java 8 without using Ubuntu's pkg system, then you can use `equivs-build` to make an empty Debian package to register it.

See http://shallowsky.com/blog/linux/install/blocking-deb-dependencies.html for an example.
