### ISSUE TITLE
Question: Retrieve Deployment logs during deploy

### ISSUE THREAD

**Issue by sepiroth887** [mesosphere/marathon#1881] opened 2015-07-25 01:35 UTC
I noticed that there is relatively little feedback during a deployment and frequently got me wondering whats going on. You can look at the marathon syslogs but this is really no great way to work if you got many devs trying to deploy things. 

Is there something I'm missing where I could surface deployment details to users so they would know whats wrong and when to stop/rollback a deployment?

**Comment by pierlo-upitup** [comment] 2015-07-25 07:10
Hi @sepiroth887,

Thanks for your feedback - We are going to concentrate on surfacing vital info regarding deployments in the UI in the coming weeks.

Do you have any specific use case you had in mind?

**Comment by gregory90** [comment] 2015-07-25 09:31
I've got two use cases when I have to guess what's wrong(even mesos sandbox logs doesn't help):
1. Deploying docker container with non existent image name/tag and when authentication to docker registry is required but not provided.
2. When no offers were received for given task(e.g. with wrong constraint).

It would really help troubleshooting user errors.

**Comment by pierlo-upitup** [comment] 2015-07-25 17:44
@gregory90 thank you very much for your valuable input – we are going to concentrate on a revamp of the deployments UI soon, and these specific use cases definitely help us better understand better all possible scenarios.

cc @air @aquamatthias

**Comment by sepiroth887** [comment] 2015-07-25 19:01
Thanks for the quick reply! On top of the previously mentioned points it would be great to get a stream of sandbox error logs / docker logs during a deployment. (Or some other consumable stream per deployment which exposes maybe parts of this)

As much as the gui is concerned, im looking forward to more functionality but it would really need to go along with a good permissions model for our usecases. We are planning on using marathon via the rest API with Teamcity or Jenkins

**Comment by MikeMichel** [comment] 2015-07-29 21:43
this is related to https://issues.apache.org/jira/browse/MESOS-2035 
as the mesos slave is the executer it already has all the information but has to pass it to marathon where it then could be pushed via eventbus which would be pretty awesome

**Comment by sepiroth887** [comment] 2015-08-11 14:16
Maybe a good first step would be to allow marathon to return the URL to the sandbox stdout and stderr logs so we don't have to guess what they might be? (This was probably already covered in another issue though) 

How granular is the evenbus? Can I attach to it and consume only events for a specific app or group?

**Comment by kamilchm** [comment] 2015-08-11 15:45
See https://github.com/mesosphere/marathon/issues/878 for sandbox url

**Comment by MikeMichel** [comment] 2015-10-28 19:29
As https://issues.apache.org/jira/browse/MESOS-2020 landed in mesos 0.23.0 can marathon work now with this information?

**Comment by aquamatthias** [comment] 2015-11-02 10:28
@MikeMichel you can see the Last Task Failure with the reason now filled in correctly from mesos. 
(E.g.: Failed to launch container: Failed to 'docker pull topface_test_wtf:latest': exit status = exited with status 1 stderr = time="2015-11-02T10:20:06Z" level=fatal msg="Error: image library/topface_test_wtf:latest not found")

**Comment by MikeMichel** [comment] 2015-11-02 10:31
@aquamatthias filled in where? In the mesos logfiles? event bus?

**Comment by aquamatthias** [comment] 2015-11-02 10:33
@MikeMichel See Application > Debug Tab > Last Task Failure

**Comment by MikeMichel** [comment] 2015-11-02 10:41
yay, that's a reason to update. thx!

**Comment by aquamatthias** [comment] 2015-11-02 10:56
@gregory90 
Use Case #1 should be solved: Please see Last Task Failure in the Debug Tab
Use Case #2 partially solved: We introduced the Waiting state as part of the Deployment in the UI. If your deployment enters the Waiting state, than you know: Marathon waits for offers that match the requirements. There are a lot of possibilities, why there is no offer that matches the requirement: not enough resources, impossible constraints, resource allocation starvation etc. We need to improve on the root cause, but the problem you described (no offers were received for given task) is visible.
Use Case #3 should be solved: if the executor_registration_timeout is exceeded the task launch is marked as failed. You can see this in App.lastTaskFailure or the Debug Tab

**Comment by aquamatthias** [comment] 2015-11-02 11:03
@sepiroth887 You have access to every task status update via the event stream.
We will add events for accepted and denied resource offers to complete the information.

**Comment by meichstedt** [comment] 2017-03-06 20:48
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3485. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment] 2017-03-07 12:57
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3485. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Closed** 2017-03-27 07:43 UTC
Labels: gui, OKR Usability, question
