### ISSUE TITLE
Allow per-app task "viability" period for task launch backoff

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1504] opened 2015-05-11 21:59 UTC
The backoff factor is designed to increase exponentially if the task fails to launch or if it terminates abnormally.  However, this backoff resets to zero whenever a task launches successfully.

It seems like the default Mesos command executor emits a TASK_RUNNING status update immediately when forking the subprocess.  Marathon could be extended to be more tolerant to this type of flapping task as follows.  We could support an additional field for Marathon app definitions that specifies how long a task needs to stay alive before the task launch backoff is reset.  This new option could have a sane default (say 5 seconds).  That way, if every task for a given app is failing within a few seconds of starting, the backoff will continue to rise as desired.

**Comment by kolloch** [comment] 2015-06-11 08:54
This is pretty similar to the supervisord concept of `startsecs` so that I guess that it is a rather established concept which is good.

How should we call that field? Maybe `"considerRunningAfterSeconds"`? Or `"taskLaunchSuccesfulAfterSeconds`"? Or `"minimumRunningTimeSeconds"`?

**Comment by aquamatthias** [comment] 2015-07-14 14:19
A major rewrite of the task scheduler is in progress by peter that will also cover the backoff delay.
See #1640 #1741 #462.
Since this has not made it to the 0.10.0 release, it is moved to 0.11.0 release as well.

**Comment by ConnorDoyle** [comment] 2015-07-14 15:58
Re: naming, I rather like `minimumTaskExecutionSeconds`.

**Comment by kolloch** [comment] 2015-07-22 09:26
Just a thought: What about resetting the back off only when we get an update that an app is deemed healthy (either via Mesos or Marathon)?

**Comment by kolloch** [comment] 2015-07-22 09:50
Or even: Does it make sense to reset the backoff delay at all when we have one viable/running/healthy task? Maybe just do not reset the delay?

**Comment by ConnorDoyle** [comment] 2015-07-28 15:35
@kolloch if we never reset the delay then that precludes rapid recovery from failures due to unavailable external services.  Since failures _will_ happen, I'm afraid this will cause every app to tend towards its maximum task launch backoff.

**Comment by ConnorDoyle** [comment] 2015-07-28 15:36
Continuing the larger discussion in #1111 for now.

**Comment by kolloch** [comment] 2015-07-28 16:51
@ConnorDoyle Regarding resetting the delay if we have one good task update: It is only leads to faster recovery if not all tasks fail in one "launch iteration". But it is kind of random because it all depends on which updates we receive first: The ones from the failing ones or the ones from the good ones.

**Comment by ConnorDoyle** [comment] 2015-07-28 16:52
@kolloch see the description expanding on your excellent launch parallelism ramp-up idea in #1111.  Does that address the problem or do you think we need to do something more?

**Comment by kolloch** [comment] 2015-08-17 10:35
We are not convinced that the solution proposed in this ticket is the correct solution. For us, it appears to be an alternative to a health check, basically saying that the app is only healthy if it survives for `minimumTaskExecutionSeconds` seconds. That might be valuable but we like other approaches better that solve the customer's issue.

We plan to include the following relevant changes to satisfy customer requirements related to the underlying problem:

* Do not reset the back off delay automatically anymore. Only reset if requested by the user via the API or the UI.
* We will implement "As a Developer, I would like more information over task restarts #1951" (https://github.com/mesosphere/marathon/issues/1951)
* Export average/mean task life time (API) (https://github.com/mesosphere/marathon/issues/2009)
* Show average/mean task life time (UI) (https://github.com/mesosphere/marathon/issues/2010)
* Export summary about the most recent configuration change (API) (https://github.com/mesosphere/marathon/issues/2011)
* Show summary about the most recent configuration change (UI) (https://github.com/mesosphere/marathon/issues/2012)

Further related issues which will be included in 0.11:
* Expose task failures in the UI (https://github.com/mesosphere/marathon/issues/1179)
* Allow access to Mesos sandbox logs from Marathon UI (https://github.com/mesosphere/marathon/issues/1871)
* Add sorting to the health column in the app list (https://github.com/mesosphere/marathon/issues/1058)

**Comment by pierrecdn** [comment] 2015-12-10 11:19
Hi, 
In the [0.11.0](https://github.com/mesosphere/marathon/releases/tag/v0.11.0) changelog I understand that this is fixed by PR #2175 ("No automatic reset of the app backoff when detecting a running task"), and originally fix #2166.
This implies that backoff is not reset on TASK_RUNNING event, but on manual restarts, config changes andby clicking "Reset Delay" in the UI.
This issue should be closed.

**Comment by pierrecdn** [comment] 2015-12-11 15:50
Seems to be less trivial, and in fact **not fixed at all** in 0.11.1

My first tests were done in this context: 
* stable cluster (no master election, no slave kill, etc)
* app definition: 
```json
{
  "id": "bug",
  "cmd": "non-exising-command",
  "instances": 1,
  "backoffSeconds": 10,
  "backoffFactor": 2,
  "maxLaunchDelaySeconds": 3600
  (...)
}
```
This config. implies this theoretical delaying scheme: 
```
try1: 0h0mn10s
try2: 0h0mn20s
try3: 0h0mn40s
try4: 0h1mn20s
try5: 0h2mn40s
try6: 0h5mn20s
try7: 0h10mn40s
try8: 0h21mn20s
try9: 0h42mn40s
try10: 1h25mn20s
# Definitively delayed, as it reach the maxLaunchDelaySeconds
```

Since, I've found at least 3 contexts where the backoff do not apply: 

* When the app is RUNNING then quickly FAILED, which is exactly the point of the issue described in this ticket, the backoff factor seems to be **never** applied.

Examples with `{ "cmd": "ls; sleep 5; non-exising-command" }`, (Note that the backoff will be delayed of 5s each time, since I'm now doing a sleep).

```
2015-12-11T15:58:28+0100
2015-12-11T15:58:10+0100
2015-12-11T15:57:54+0100
2015-12-11T15:57:26+0100
2015-12-11T15:57:10+0100
2015-12-11T15:56:53+0100
2015-12-11T15:56:25+0100
2015-12-11T15:56:09+0100
2015-12-11T15:55:51+0100
2015-12-11T15:55:25+0100
2015-12-11T15:55:08+0100
# got an endless 15s delay
```
* Back to an immediate FAILED, `{ "cmd": "non-exising-command" }`. When you set-up more than 1 instance, it seems to apply but the next runs are delayed Nth faster as it should (N = number of instances). Maybe you don't really want that.

Example with `{ "instances": 2 }`: 
```
2015-12-11T15:48:27+0100
2015-12-11T15:48:27+0100 # ~+5mn20s
2015-12-11T15:43:06+0100
2015-12-11T15:43:06+0100 # weird... 
2015-12-11T15:41:45+0100
2015-12-11T15:41:45+0100 # weird... 
2015-12-11T15:41:24+0100
2015-12-11T15:41:24+0100 # ~+1mn20s
2015-12-11T15:39:59+0100
2015-12-11T15:39:59+0100 # ~+20s
2015-12-11T15:39:38+0100
2015-12-11T15:39:38+0100
```
* When a mesos master election occurs, the scheduling of the tasks exponential backoff seems to be a mess. Not 100% sure about that as I wasn't able to reproduce systematically.

This has huge side-effects, especially when using the HTTP callback, as your listeners are continuously notified with `{ "eventType": "status_update_event" }`.

Related issues:
- #1111
- #2249

**Comment by kolloch** [comment] 2015-12-14 13:06
I cannot follow all of what you wrote and I agree that the back off scheme is simplistic and not sufficient (that is why #1111 is open). This ticket suggested a possible work around.

That said, as you have discovered, the logic works differently from what you (@pierrecdn) seem to expect. On every task failure event:

* We check if there is a remaining delay in place for this app:
  * If yes, we update the _remaining_ delay with the backoffFactor.
  * If no, we set the delay to backoffSeconds.

If a delay is in place, we do not start tasks for that app until it is over.

Therefore, if you have only one instance for your app, you should never see a delay beyond backoffSeconds.

Does that help you in understanding the current logic?

**Comment by kolloch** [comment] 2015-12-14 13:06
Feel free to suggest updates to our documentation to clarify this:

https://mesosphere.github.io/marathon/docs/contributing.html

**Comment by pierrecdn** [comment] 2015-12-14 15:41
Hi, 
Many thanks for your answer.

My entrypoint was the 0.11.0 changelog saying "No automatic reset of the app backoff when detecting a running task". Then I figured out why this was not what I get when I deploy apps that crash within 5 sec after starting and/or apps with multiple instances.

I still don't fully understand why a TASK_FAILED state didn't succeed in updating the delay when it occurs after a TASK_RUNNING.
How the first delay is initiated? It seems we always are in your "If no remaining delay" case.

Apart from that, I fully approve the choices discussed here https://github.com/mesosphere/marathon/issues/1111#issuecomment-125654910. I'm sad that this issue is not addressed in 0.14, as this seems to be a blocker to safely implement event subscriptions (or maybe you've something else to suggest?).

**Comment by pierrecdn** [comment] 2015-12-15 10:57
Example of an apps launched with default settings (backoffSeconds: 1, backoffFactor: 1.15) that fails after startup (TASK_RUNNING then TASK_FAILED).

* 1 instance
```
Dec 15 10:48:32 sample-host marathon: [2015-12-15 10:48:32,645] INFO Increasing delay. Task launch delay for [/sample-app-1-instance] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:48:44 sample-host marathon: [2015-12-15 10:48:44,137] INFO Increasing delay. Task launch delay for [/sample-app-1-instance] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:48:59 sample-host marathon: [2015-12-15 10:48:59,682] INFO Increasing delay. Task launch delay for [/sample-app-1-instance] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:49:14 sample-host marathon: [2015-12-15 10:49:14,121] INFO Increasing delay. Task launch delay for [/sample-app-1-instance] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:49:29 sample-host marathon: [2015-12-15 10:49:29,887] INFO Increasing delay. Task launch delay for [/sample-app-1-instance] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:49:49 sample-host marathon: [2015-12-15 10:49:49,163] INFO Increasing delay. Task launch delay for [/sample-app-1-instance] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:50:04 sample-host marathon: [2015-12-15 10:50:04,188] INFO Increasing delay. Task launch delay for [/sample-app-1-instance] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:50:19 sample-host marathon: [2015-12-15 10:50:19,268] INFO Increasing delay. Task launch delay for [/sample-app-1-instance] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:50:35 sample-host marathon: [2015-12-15 10:50:35,173] INFO Increasing delay. Task launch delay for [/sample-app-1-instance] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:50:54 sample-host marathon: [2015-12-15 10:50:54,191] INFO Increasing delay. Task launch delay for [/sample-app-1-instance] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
```

* 2 instances
```
Dec 15 10:43:41 sample-host marathon: [2015-12-15 10:43:41,300] INFO Increasing delay. Task launch delay for [/sample-service-2-instances] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:43:41 sample-host marathon: [2015-12-15 10:43:41,302] INFO Increasing delay. Task launch delay for [/sample-service-2-instances] changed from [998 milliseconds] to [1 seconds 150 milliseconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:43:47 sample-host marathon: [2015-12-15 10:43:47,952] INFO Increasing delay. Task launch delay for [/sample-service-2-instances] changed from [-500 milliseconds] to [1 seconds 322 milliseconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:43:48 sample-host marathon: [2015-12-15 10:43:48,108] INFO Increasing delay. Task launch delay for [/sample-service-2-instances] changed from [1 seconds 166 milliseconds] to [1 seconds 520 milliseconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:43:53 sample-host marathon: [2015-12-15 10:43:53,273] INFO Increasing delay. Task launch delay for [/sample-service-2-instances] changed from [0 milliseconds] to [1 seconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
Dec 15 10:43:53 sample-host marathon: [2015-12-15 10:43:53,413] INFO Increasing delay. Task launch delay for [/sample-service-2-instances] changed from [860 milliseconds] to [1 seconds 150 milliseconds]. (mesosphere.marathon.core.launchqueue.impl.RateLimiter$:52)
```

The backoff is still reset to 0 in this case...

**Comment by kolloch** [comment] 2015-12-16 10:42
I think there is still a glitch in our communication, @pierrecdn.

What do you mean by "The backoff is still reset to 0 in this case"? What we mean with a backoff reset is invoking `RateLimiter.resetDelay` which would be visible by the following log line: `Task launch delay for [...] reset to zero`

The backoff delay is calculated per app (not per task) and can be viewed as a means for calculating and updating a deadline. If a new failure is detected, the `backoffFactor` is applied to the remaining duration towards this deadline. Otherwise the deadline is set to `backoffDuration` seconds into the future.

Before this deadline, now new tasks are launched. When the deadline has been reached, tasks are started as quickly as possible again.

**Comment by pierrecdn** [comment] 2015-12-17 18:58
Hi @kolloch, 

OK, I'm sorry for the terminology I used, I understand it was quite unclear.
As you can see in my log, I never explicitly did an invocation of RateLimiter.resetDelay (I was doing `tail -f marathon.log | grep -i "delay"`).

Following your explanation: 
> The backoff delay is calculated per app (not per task) and can be viewed as a means for calculating and updating a deadline. If a new failure is detected, the backoffFactor is applied to the remaining duration towards this deadline. Otherwise the deadline is set to backoffDuration seconds into the future.
Before this deadline, now new tasks are launched. When the deadline has been reached, tasks are started as quickly as possible again.

In my case, it seems it doesn't prevent the app to be deployed again and again. 
I really don't understand why the next run of my apps are not delayed and spam the event listeners of perpetual updates (in a case of a broken app that fails a few seconds after startup).

What do you think about my first example of an app with 1 instance that seems to log `Increasing delay. Task launch delay for [...]` every 15s ?

**Comment by kolloch** [comment] 2015-12-18 13:52
@pierrecdn As desribed in other issues, I think that the current implementation leaves a lot to be desired. What you saw follows from that as far as I can see. In general, Marathon will try to launch tasks perpetually. The backoff configuration tells it how long it should wait in-between.

**Comment by FlorentFlament** [comment] 2016-01-21 14:53
This issue may be related to this bug: https://github.com/mesosphere/marathon/issues/3059

**Comment by meichstedt** [comment] 2017-03-07 13:11
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3066. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Closed** 2017-03-27 07:44 UTC
Labels: enhancement, service, Size: L, usability
