### ISSUE TITLE
Prominent "No Deployments" if there was an error retrieving the deployments

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3131] opened 2016-02-02 14:36 UTC
Very similar to #3093.

We should not show "No Deployments" if there was an error while retrieving the deployments. In this case, we simply do not know if there are any deployments.

<img width="811" alt="screen shot 2016-02-02 at 15 33 50" src="https://cloud.githubusercontent.com/assets/339354/12752379/96e40ae8-c9c2-11e5-9091-2f8114b3f11c.png">

I also think that the error message should be a lot more prominent.

**Comment by philipnrmn** [comment] 2016-02-29 18:16
I'm kind of confused, it looks like this should have been fixed in mesosphere/marathon-ui#535

Do we have a regression? Any idea what's happened here @pierlo-upitup?

**Comment by philipnrmn** [comment] 2016-02-29 22:17
I found it - it was a deliberate reversion:
https://github.com/mesosphere/marathon-ui/commit/1f14af3cd517b537552d044b283c9c12376852dc

**Comment by pierlo-upitup** [comment] 2016-03-01 10:05
I'm descoping this from `0.16` – I had a chat with @philipnrmn and we couldn't come to an agreement regarding wether or not hiding the rows to display the prominent error would be a regression (see @aldipower 's comment here https://github.com/mesosphere/marathon-ui/pull/535#issuecomment-170592918 ) and because we need a global notification system for the best solution I'm moving this to Backlog.

**Comment by meichstedt** [comment] 2017-03-07 12:11
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2680. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Closed** 2017-03-27 07:42 UTC
Labels: bug, gui
