### ISSUE TITLE
Dialog ribbon colors not matching state

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#3446] opened 2016-03-09 17:43 UTC
If the dialog is a danger or warning state, the top ribbon color should be red or yellow.

Currently (in Master) it is blue if I try to destroy an application and blue if I try to stop a deployment. There is a color mismatch.

![image](https://cloud.githubusercontent.com/assets/15963/13644560/3ea79504-e5db-11e5-95fd-66a63884e1ac.png)

![image](https://cloud.githubusercontent.com/assets/15963/13644581/613c0ff0-e5db-11e5-907d-cfd84bfde541.png)

**Comment by pierlo-upitup** [comment] 2016-03-11 14:14
Duplicate of https://github.com/mesosphere/marathon/issues/3458

**Closed by pierlo-upitup** 2016-03-11 14:14 UTC
Labels: gui, usability
