### ISSUE TITLE
Can't rename application using UI

### ISSUE THREAD

**Issue by magcius** [mesosphere/marathon#2840] opened 2015-12-16 20:38 UTC
For some reason, when using the UI to edit an application configuration, modifying the application's ID and pressing "Change and deploy configuration" gives me:

> App is currently locked by one or more deployments. Pressing the button again will forcefully change and deploy the new configuration.

Pressing the button again seems to do nothing.

**Comment by philipnrmn** [comment] 2015-12-17 10:10
As ever, thanks for the bug report. I opened a duplicate of this ticket just now: #2845 

You actually can't rename apps in Marathon as their IDs are literally their identifiers. What actually happens when you alter the name is that a new app is created with a copy of the same app configuration.

The default `ports` value is `0`, which randomly assigns a port on initial app creation. Thereafter the randomly assigned port is returned (typically some value like 10001, at least on my dev setup). This gets carried over into the new application configuration, and the server returns a `490 conflict` with a helpful error message.

The bug is that the UI detects this as a deployment lock and shows the wrong error message.

**Comment by philipnrmn** [comment] 2015-12-17 11:11
duplicates #2845

**Closed by philipnrmn** 2015-12-17 11:11 UTC
Labels: bug, duplicate, gui

**Comment by magcius** [comment] 2015-12-17 17:20
Aha. So if I change the ports, it should work? Got it. I was also wondering how to copy an application, and now I know.
