### ISSUE TITLE
Kill & Scale, followed by scale-up does not work.

### ISSUE THREAD

**Issue by rohitgupta-90** [mesosphere/marathon#1868] opened 2015-07-23 23:56 UTC
On Marathon 0.8.0, when we have multiple instances of an app deployed, and we select one of the instance and use the "kill & Scale" button on the UI, that particular instance of the app is destroyed. But when we try to scale up the instance by one, marathon does not react to it, although I see the request in marathon logs, there is no activity on mesos master and the mesos slave in context. 

However, now if I scale down the number of apps using the scale button which choses one app and kills it, and then scale up. I am able to recover my original number of instances. 

Tried this with two different deployment of Mesos/Marathon clusters and I see the same behavior.

**Comment by kolloch** [comment] 2015-07-29 13:07
I couldn't reproduce this with 0.10.0-RC3. Any chance that you can test this with that version? Thanks.

**Comment by aquamatthias** [comment] 2015-08-12 13:30
Hey @rohitgupta-90 This is a known problem in 0.8.0 and is fixed in 0.10.0 (currently RC5)

**Closed by aquamatthias** 2015-08-12 13:30 UTC
Labels: bug, service
