### ISSUE TITLE
No way to spread tasks evenly on a cluster?

### ISSUE THREAD

**Issue by gtmtech** [mesosphere/marathon#3220] opened 2016-02-11 14:57 UTC
Just raising this because I dont believe there is a way to spread task instances evenly on a cluster of hosts.

Reading through the issues I think there is quite a good awareness that GROUP_BY doesnt work at all well - and you can end up with horribly skewed task-instances across a cluster because at the point of scheduling the new task, marathon is only aware of existing offers from mesos for a subsection of nodes in a cluster.

The recommended way seems to be to supply GROUP_BY constraint with a number, indicating the size of your pool of (e.g. hosts) to try and spread the task-instances evenly over only that pre-defined number.

However this also doesnt work in an autoscaling group, when you dont know the number of available hosts in advance, and even when you set it to the number of hosts at time t, given that may change, marathon wont actively reschedule the task-instances to allow the autoscaling nature of the hosts.

UNIQUE is also not available as a solution as this automatically precludes having multiple task-instances on a host.

To be clear, the solution I am looking for is:
- I have 8 hosts, and wish to run 14 instances of a task - marathon schedules as 6 hosts with 2 task-instances and 2 hosts with 1 task-instances. (6_2 + 2_1)
- I later lose a host because of system failure - marathon schedules as 7 hosts with 2 task-instances
- The host comes back up and marathon reschedules as 6 hosts with 2 task-instances and 2 hosts with 1 task-instance as originally.
- A further host is added to the cluster and marathon reschedules as 5 hosts with 2 task-instances and 4 hosts with 1 task-instance.

I would have thought this is the most common desired situation of all - "Please evenly distribute n instances of a task on m hosts at all times".

Is there no way to do this in marathon, or have I missed something obvious? Many thanks

**Comment by bryanstephens** [comment] 2016-02-11 17:37
Not sure if Marathon could benefit from utilizing something like Netflix's Fenzo project for this: https://github.com/Netflix/Fenzo

This is something my team has been looking to integrate with our own scheduler in the future but if Marathon could support it out of the box that would be amazing.

**Comment by gtmtech** [comment] 2016-02-11 21:33
Finding docs on how GROUP_BY actually works seems pretty impossible, so for the benefit of others, after reading the scala code, and also lots of experiments, here is how I believe the GROUP_BY scheduling algorithm works. Please correct if this is not the case, but this is my experience. If this is as designed, I think it would be really helpful to folks to have this as part of the documentation, because otherwise there's a lot of second-guessing, and scheduling is quite an important thing to understand.


For this example, suppose I have 6 unique hosts (host1..host6), and
I schedule a task with a hostname GROUP_BY clause of 4. I desire the
task to have 10 instances. The documentation, the API and the code confusingly intermingle "instances" and "tasks", so I will refer to them below as "tasks" but they are really instances of the same task:

First of all, the hosts are empty, so look like this:

```
[host1]   [host2]   [host3]   [host4]   [host5]   [host6]
```

host1 offers resources. marathon has not seen this node before, so 
automatically says yes (marathon prefers to expand the group if 
possible at all times)

```
[host1]   [host2]   [host3]   [host4]   [host5]   [host6]
task1
```

host1 offers resources again. This time marathon has seen the node
before, so asks the question: do I have min 4 different hosts
across all my tasks? The answer is no, so it refuses the offer

host2 offers resources. Marathon automatically says yes

```
[host1]   [host2]   [host3]   [host4]   [host5]   [host6]
task1     task2
```

host3 offers resources. host4 offers resources, both yes.

```
[host1]   [host2]   [host3]   [host4]   [host5]   [host6]
task1     task2     task3     task4
```

now if host5 offers resources, marathon would automatically
accept by the "prefer to expand the cluster" rule. So instead
lets consider that host1 offers resources next.

Marathon now asks 2 questions: Do I have min 4 different hosts
across all my tasks? (YES). Does this host have the minimum
tasks running across all the known hosts for which at least
one task is running? (YES). As both are yes, it schedules task5

```
[host1]   [host2]   [host3]   [host4]   [host5]   [host6]
task1     task2     task3     task4
task5
```

if host1 now offers resources again, marathon would ask the
same questions and reply YES,NO - so would not allow the
scheduling onto host1

if host2|host3|host4 offered resources, marathon would ask
the same questions and reply YES,YES - so would allow the
scheduling onto these hosts

if host5|host6 offered resources, remember marathon always
allows the expansion of the cluster so would allow the 
scheduling onto these hosts

suppose host5 and host6 still dont offer yet, so we continue
with the next 3 tasks in no particular order:

```
[host1]   [host2]   [host3]   [host4]   [host5]   [host6]
task1     task2     task3     task4
task5     task8     task6     task7
```

So far, nice and evenly balanced.

host3 now offers resources, and the answer is YES,YES for
task9

```
[host1]   [host2]   [host3]   [host4]   [host5]   [host6]
task1     task2     task3     task4
task5     task8     task6     task7
                    task9
```

Still evenly balanced, however finally host5 offers
resources. As this node has not been seen before,
marathon automatically answers yes:

```
[host1]   [host2]   [host3]   [host4]   [host5]   [host6]
task1     task2     task3     task4     task10
task5     task8     task6     task7
                    task9
```

Now we have an unbalanced cluster, but it does fulfil the
constraint that GROUP_BY 4 - i.e. we have at least 4
hostgroups at all times.

If there was a task11, the ONLY two hosts that would allow
it to be scheduled are host5 and host6, because either an
unknown host or a host which contains the minimum number of
running tasks can run task11.

If host1,host2,host3,host4 have lots of free room to run task11
but host5 and host6 cannot because they are running other
tasks and have no resources with which to make offers,
task11 will never be scheduled (FAIL 1)

Suppose now, host5, host3 and host6 fail/die. In this case
there should be 10 running tasks, but only 6 are running

```
[host1]   [host2]   [xxxxx]   [host4]   [xxxxx]   [xxxxx]
task1     task2     -----     task4     -----            
task5     task8     -----     task7
                    -----
```

Although host1, host2 and host4 may continue to offer 
resources, the base constraint requires that minimum 4
groups have to be running tasks, so all these offers will
be ignored. This results in 4 downed tasks that will not 
be rescheduled until another host makes offers. (FAIL 2)

Suppose host6 comes back online. Now there are min 4 
hosts which satisfies the constraint, so they fill up
like this>

```
[host1]   [host2]   [xxxxx]   [host4]   [xxxxx]   [host6]
task1     task2     -----     task4     -----     task3       
task5     task8     -----     task7               task6
                    -----
```

At this point any of host1,host2,host4,host6 can offer 
and at least one of (task9,task10) will run on (host1,
host2,host4). Consider that before host6 came back
online, marathon would refuse to run any more tasks
on (host1,host2,host4), but now it does.

From my reading of the scheduling code/algorithm, I 
believe this to be the best explanation of what happens
behind the scenes with a GROUP_BY clause. As you can see
from the above examples, it leads to at least 2 
suboptimal situations.

**Comment by scalp42** [comment] 2016-02-11 22:55
@gtmtech thanks a lot for taking the time writing this up, this is confusing for us as well.

**Comment by philipnrmn** [comment] 2016-02-12 14:34
Wow, thanks for the write-up @gtmtech!

There's more discussion of the original requirement in this ticket: #846

**Comment by philipnrmn** [comment] 2016-02-12 14:35
Marked this as a dupe of #846 but leaving it open as a ticket to fold @gtmtech's writeup into our docs.

**Comment by timoreimann** [comment] 2016-02-13 22:20
@philipnrmn Are you certain this ticket is a duplicate? From my understanding, #846 is about running one instance of an application on every slave; that is, if you have x slaves, you always want x instances running, thus making the scaling factor irrelevant. Conversely, #3220 is about even distribution of an application's tasks on all slaves, where the number of application tasks can be smaller, equal, or higher than the number of slaves.

**Comment by bryanstephens** [comment] 2016-02-14 05:12
@philipnrmn I don't think this is a duplicate of #846, the docs should definitely be improved for the GROUP_BY clause if that is in fact what it does.

**Comment by philipnrmn** [comment] 2016-02-15 11:52
I guess that's fair, it's not exactly the same functionality.

**Comment by medzin** [comment] 2016-04-05 20:02
The current grouping algorithm of tasks on a cluster isn't too optimal. Consider a situation in which I have a cluster that is spread across 3 availability zones, and I want to run application with 12 instances spread evenly on each zone. So I use az:GROUP_BY:3 (az - my custom attribute) constraint and everything spreads fine - then one zone goes down and the problems begin. I lost 4 instances of my application, but ok, I still have a quorum so the Marathon will try to keep alive the remaining 8. So after a while 2 instances of my app in the remaining zone goes down (but ok, Marathon should try to recover them). But then comes the GROUP_BY constraint that is also applied to recovery algorithm and it forces the starting of the new instances in the unavailable zone. Maybe the GROUP_BY algorithm shouldn't sequentially accept offers only with different grouped values, but instead it should know how many offers with the same attribute value it can accept, and accept them as they come, so at least Marathon will be able to keep my remaining 8 instances healthy.

**Comment by janisz** [comment] 2016-04-06 11:44
How about introducing new constraint: `SPREAD_ACROSS`. It will have similar behavior to `GROUP_BY` with one difference. Instead of trying to launch task evenly on minimum numer of groups, it will launch tasks exactly on specified number of groups (or more). Consider following example (based on @gtmtech):

> For this example, suppose I have 6 unique hosts (host1..host6), and
I schedule a task with a hostname SPREAD_ACROSS clause of 4. I desire the
task to have 10 instances.

1. First of all, the hosts are empty, so look like this:

        [host1]   [host2]   [host3]   [host4]   [host5]   [host6]

2. host1 offers resources. marathon has not seen this node before, so automatically says yes marathon prefers to expand the group if possible at all times)

        [host1]   [host2]   [host3]   [host4]   [host5]   [host6]
         task1

3. host1 offers resources again. This time marathon has seen the node before, so asks the question: _How many tasks can I place on one host to still have ability to spread it across 4 nodes._ The answer is: ⎡¹⁰⁄₄⎤ = 3 (or in more verbose form `[3,3,2,2]`)

        [host1]   [host2]   [host3]   [host4]   [host5]   [host6]
         task1
         task2

4. host2 offers resources. Marathon automatically says yes

        [host1]   [host2]   [host3]   [host4]   [host5]   [host6]
         task1     task3
         task2

5. host3 offers resources. host4 offers resources, both yes.

        [host1]   [host2]   [host3]   [host4]   [host5]   [host6]
         task1     task3     task4     task5
         task2

6. If

    * host1 now offers resources again, marathon would ask the same questions and reply YES - so would allow the scheduling onto these hosts (but next jobs will be rejected)
    * host2|host3|host4 offered resources, marathon would ask the same questions and reply YES - so  would allow the scheduling onto these hosts
    * host5|host6 offered resources, remember marathon always allows the expansion of the cluster so  would allow the scheduling onto these hosts

**Comment by mimmus** [comment] 2016-10-27 14:15
Thank you very much to gtmtech for detailed explanation of GROUP_BY.
Using:

 constraints: [
      "hostname",
      "GROUP_BY",
      "2"
    ]

together with:

 instances: 2

I get a almost-evenly process distribution in my cluster (with 3 slaves), every app has two istances on different nodes (HA).

**Comment by jeacott1** [comment] 2016-12-06 10:35
Thanks for the group by description! Now, is there anyway to control the spread of 'different' tasks? We have hundreds of unique tasks starting/stopping all the time. But whenever marathon gets a request to spin up say 50 tasks (1 instance each) simultaneously,  it invariably schedules them all on the same node which puts a huge load on it and healthchecks temporarily fail. Would love to be able to control this a lot better.

**Comment by janisz** [comment] 2016-12-06 10:52
@jeacott1 You can control with 
> [`--max_tasks_per_offer` (Optional. Default: 5): Launch at most this number of tasks per Mesos offer. Usually, there is one offer per cycle and slave. You can speed up launching tasks by increasing this number.](https://github.com/mesosphere/marathon/blob/master/docs/docs/command-line-flags.md#marathon-after-0110-including)

Deploymenst will be slower but different tasks will be scheduled across different hosts.

**Comment by meichstedt** [comment] 2017-03-07 12:06
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2348. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Closed** 2017-03-27 07:42 UTC
Labels: analyze, docs, enhancement
