### ISSUE TITLE
LDAP authentication 

### ISSUE THREAD

**Issue by felixb** [mesosphere/marathon#1847] opened 2015-07-21 18:56 UTC
I'd like to see LDAP authentication for marathon. The implementation should support r/w and r/o groups. You still need /ping be accessible w/o authentication for different kinds of health checks. 

I'd be glad to get rid of my current workaround deploying marathon with an apache reverse proxy in the same docker container.

**Comment by janisz** [comment] 2015-07-22 20:09
It's duplicate of https://github.com/mesosphere/marathon/issues/128

**Comment by felixb** [comment] 2015-07-22 20:17
It's not. I'm not asking for multi tenancy at all. Just authentication and restriction to r/o mode for some users.

**Comment by sepiroth887** [comment] 2015-07-25 01:23
while this is not a solution, i run nginx on the mesos-master which also runs marathon. nginx has the ldap-module enabled which should be able to scope pretty well what you need. If you only allow GET to marathon via nginx you should be able to get what you want. 

That said id still like to see granular permissions with Marathon :)

**Comment by felixb** [comment] 2015-07-25 07:41
I'm doing the same thing with apache, because nginx-ldap does not support STARTTLS.

Anyway, I don't like the idea to run a webserver next to marathon (or chronos) in a single docker container just to do LDAP authentication.
Using marathons groups to marathon/chronos and apache as single containers isn't a solution either. The marathon/chronos instance would be accessible from outside if you know where it's running.

**Comment by sepiroth887** [comment] 2015-07-27 13:51
True. The permissions model on containers could generally improve to allow those use cases but thats more in dockers realm. 

The problem though is not just with marathon but a lot of other tools with poir or no ldap support. Actually dockers registry 2.0 does bundle nginx internally for ssl termination iirc. 

I would generally love to see more integrations with oauth similar to what rancher does with github. 
This gives a lot of flexibility and granularity for ACLs

**Comment by air** [comment] 2015-08-09 20:32
Hey @felixb - thanks for the issue! We definitely want to improve Marathon access control.
 
We're working on adding hooks for this in Marathon, as well as some commercial add-ons as part of [DCOS](https://mesosphere.com/learn/).

Could you give a quick example of r/w, r/o users/groups and how it might work for your use case?

**Comment by felixb** [comment] 2015-08-10 09:06
We currently run one marathon for each team. There is an LDAP group for each team, one for ops/admin and one for read only/monitoring users. The team and ops are allowed to do any requests. Read only is allowed to do GET requests only.
Access one of the css files is granted without login. This is just for the health checks.
I'm quite fine with the current situation. But I'd rather remove the proxy in front of marathon.

**Comment by janisz** [comment] 2015-08-12 12:55
I created PoC for this feature. Please tell mi if this is right approach. I used shiro to provide user authentication. It works with AD and basic shiro auth. It supports read and write permissions.

**Comment by kamilchm** [comment] 2015-08-12 14:45
It would be great to have it 0.11 :)

**Comment by janisz** [comment] 2015-08-17 09:46
PoC with Shiro works fine for me. 
What do you think about following requirements for this feature

1. Health check ([`/ping`](https://mesosphere.github.io/marathon/docs/rest-api.html#get-ping)) is avaliable without authentication
2. Authentication is enabled when user provides path to shiro config
3. There is auditlog with information `datetime method URL who`

Are there any other requirements?

**Comment by sepiroth887** [comment] 2015-08-17 12:56
That would do the trick :) never worked with shiro but as long as it supports ldap/ad/basic auth its a great start :)

**Comment by SEJeff** [comment] 2015-10-05 19:42
@janisz That all sounds entirely reasonable. Did you make a PR for this?

**Comment by janisz** [comment] 2015-10-05 21:01
PR is [here](https://github.com/mesosphere/marathon/pull/1986) but in next Marathon release plugin interface will be available. I started working on authentication plugin [here](https://github.com/janisz/marathon-shiro-authentication-plugin/tree/shiro_authenticator) but it's not finished. I hope I'll fix it next week.

**Comment by janisz** [comment] 2015-10-19 13:24
@SEJeff I just created [PR ](https://github.com/janisz/marathon-shiro-authentication-plugin/pull/1) for authentication plugin that is based on [Shiro](http://shiro.apache.org/) it will work with Marathon 0.12. Right now it supports only authenctication, so if you log in you can do anything. I need to think how to combine actions on different paths and shiro roles.

**Comment by SEJeff** [comment] 2016-06-14 15:15
For any non-dcos users, this [ldap plugin](http://jbu.io/2016/04/19/securing-mesosphere-marathon-using-the-marathon-ldap-plugin/) seems to be targeted at the new marathon plugin api.

**Comment by jasongilanfarr** [comment] 2016-11-23 18:22
Closed as there is now a plugin

**Closed by jasongilanfarr** 2016-11-23 18:22 UTC
Labels: enhancement, service
