### ISSUE TITLE
Cannot install 1.3.0-1.0.506 on RHEL/CentOS v7.2

### ISSUE THREAD

**Issue by djl87** [mesosphere/marathon#4391] opened 2016-09-15 13:52 UTC
Previously had no problems installing marathon and have been doing so a couple of times a day for the last couple of months. However, with the latest build:

```
Downloading packages:
marathon-1.3.0-1.0.506.el7.x86_64.rpm                                                                                                                                                                                 |  17 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : marathon-1.3.0-1.0.506.el7.x86_64                                                                                                                                                                                         1/1
Error unpacking rpm package marathon-1.3.0-1.0.506.el7.x86_64
**error: unpacking of archive failed on file /usr/bin/marathon;57daa6d3: cpio: read**
  Verifying  : marathon-1.3.0-1.0.506.el7.x86_64                                                                                                                                                                                         1/1

Failed:
  marathon.x86_64 0:1.3.0-1.0.506.el7

```

**Comment by skarlsson** [comment] 2016-09-15 14:47
same problem, both upgrading and on clean install centos 7

**Comment by garrettux** [comment] 2016-09-15 19:50
same, able to reproduce in a clean vagrant centos 7.2 VM.  more details:

```
[vagrant@mesos-00 ~]$ cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)

[vagrant@mesos-00 ~]$ uname -a
Linux mesos-00 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[vagrant@mesos-00 ~]$ sudo yum list marathon
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repos.forethought.net
 * extras: centos.mirror.ndchost.com
 * updates: mirrors.seas.harvard.edu
Available Packages
marathon.x86_64                                                                                                                  1.3.0-1.0.506.el7                                                                                                                  mesosphere

[vagrant@mesos-00 ~]$ sudo yum install marathon
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repos.forethought.net
 * extras: centos.mirror.ndchost.com
 * updates: mirrors.seas.harvard.edu
Resolving Dependencies
--> Running transaction check
---> Package marathon.x86_64 0:1.3.0-1.0.506.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================================================================================================
 Package                                                        Arch                                                         Version                                                                   Repository                                                        Size
==============================================================================================================================================================================================================================================================================
Installing:
 marathon                                                       x86_64                                                       1.3.0-1.0.506.el7                                                         mesosphere                                                        17 M

Transaction Summary
==============================================================================================================================================================================================================================================================================
Install  1 Package

Total download size: 17 M
Installed size: 89 M
Is this ok [y/d/N]: y
Downloading packages:
marathon-1.3.0-1.0.506.el7.x86_64.rpm                                                                                                                                                                                                                  |  17 MB  00:00:14
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : marathon-1.3.0-1.0.506.el7.x86_64                                                                                                                                                                                                                          1/1
Error unpacking rpm package marathon-1.3.0-1.0.506.el7.x86_64
error: unpacking of archive failed on file /usr/bin/marathon;57dafadd: cpio: read
  Verifying  : marathon-1.3.0-1.0.506.el7.x86_64                                                                                                                                                                                                                          1/1

Failed:
  marathon.x86_64 0:1.3.0-1.0.506.el7

Complete!

[mesosphere]
name=Mesosphere Packages for EL 7 - $basearch
baseurl=http://repos.mesosphere.io/el/7/$basearch/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mesosphere

[mesosphere-noarch]
name=Mesosphere Packages for EL 7 - noarch
baseurl=http://repos.mesosphere.io/el/7/noarch/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mesosphere

[mesosphere-source]
name=Mesosphere Packages for EL 7 - $basearch - Source
baseurl=http://repos.mesosphere.io/el/7/SRPMS/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mesosphere
```

**Comment by Daniel-ltw** [comment] 2016-09-15 21:48
Any resolution for this issue?

**Comment by lloesche** [comment] 2016-09-19 11:20
I'm looking into this right now. At a first glance the packages that were transferred over to the repository import server were incomplete. Their headers were intact but they are truncated. Instead of 80MB they are 10-20MB. Interestingly both `dpkg-sig` and `rpm` were able to sign the packages and later verify the signature.

Package on repo:
```
$ rpm -K marathon-1.3.0-1.0.506.el7.x86_64.rpm
marathon-1.3.0-1.0.506.el7.x86_64.rpm: rsa sha1 (md5) pgp md5 OK
$ rpm2cpio marathon-1.3.0-1.0.506.el7.x86_64.rpm |  cpio -idmv
cpio: ./usr/bin/marathon not created: newer or same age version exists
cpio: premature end of file
```

Package generated by CI system:
```
$ rpm -K marathon-1.3.0-1.0.506.el7.x86_64.rpm
marathon-1.3.0-1.0.506.el7.x86_64.rpm: rsa sha1 (md5) pgp md5 OK
$ rpm2cpio marathon-1.3.0-1.0.506.el7.x86_64.rpm |  cpio -idmv
./usr/bin/marathon
./usr/lib/systemd/system/marathon.service
181426 blocks
```

Looking at the TeamCity Job we're using scp to copy the files from CI system to signing system. It's therefor possible that network issues cause incomplete transfers. I'm just surprised that neither the rpm nor deb repo tools caught this issue and signed and imported the truncated packages without throwing an error (which would have aborted the import). I just confirmed this by splitting a valid RPM in half and being able to `rpm --resign` the first half without a problem.

I will now:
1) manually remove all broken 1.3.0 and related release packages from the repo and resync it to S3 (where repos.mesosphere.com is hosted)
2) re-import the packages from the CI system
3) switch the transfer process from scp to using rsync over ssh with checksumming so we can't get any broken imports in the future

**Comment by liquid-sky** [comment] 2016-09-19 13:06
@lloesche I was able to install `1.3.0-1.0.506.ubuntu1404` just now 👍

**Closed** 2016-09-19 14:19 UTC
Labels: blocker, bug

**Comment by JayH5** [comment] 2016-09-19 14:26
Thank you! 🍰

**Comment by drcrallen** [comment] 2016-09-19 17:49
Great! 1.3.0-1.0.506.ubuntu1404 seems to be deploying correctly. Thanks!

**Comment by stahnma** [comment] 2016-10-08 04:16
I'm still showing an older package in repos.mesosphere.com/el/7/

 (1.0.1-2.0.93.centos701406)

**Comment by lloesche** [comment] 2016-10-10 19:21
@stahnma that's correct, the latest stable release of Mesos is 1.0.1.

We do provide nightly builds if you enable the unstable repo.
E.g.
```
$ yum --enablerepo=mesosphere-unstable list mesos
```
should show you the latest nightly build.

If that repo is not available on your system I recommend installing our repo via `rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm`.

Hope that helps.
