### ISSUE TITLE
Marathon cannot pull docker image from AWS ECR

### ISSUE THREAD

**Issue by anhcuong** [mesosphere/marathon#3448] opened 2016-03-09 19:34 UTC
Hi, 

I followed this [https://mesosphere.github.io/marathon/docs/native-docker-private-registry.html](tutorial) . However it seems does not work with AWS ECR even I configed to be able to pull from aws ecr using command line under all the user group.

The mesos slave log show that I have fetched and untar the docker.tar.gz (image)
![marathon-pull](https://cloud.githubusercontent.com/assets/7950613/13647740/6bf11bd0-e670-11e5-8453-8715e4b075d7.png)

The marathon last failure show:

```
Failed to launch container: Failed to 'docker -H unix:///var/run/docker.sock pull AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/cloud:otp10Mar2016v4': exit status = exited with status 1 stderr =
```

The docker API showing:

```
INFO[44509] POST /v1.21/images/create?fromImage=AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com%2Fcloud%3Aotp10Mar2016v4

INFO[44388] POST /v1.21/images/create?fromImage=AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com%2Fcloud%3Aotp10Mar2016v2

ERRO[44509] Handler for GET /v1.21/containers/AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/IMAGE_ID:TAG/json returned error: no such id: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/IMAGE_ID:TAG
ERRO[44509] HTTP Error                                    err=no such id: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/IMAGE_ID:TAG statusCode=404
INFO[44509] GET /v1.21/images/AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/IMAGE_ID:TAG/json
ERRO[44509] Handler for GET /v1.21/images/AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/IMAGE_ID:TAG/json returned error: No such image: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/IMAGE_ID:TAG
ERRO[44509] HTTP Error                                    err=No such image: AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/IMAGE_ID:TAG statusCode=404
INFO[44509] POST /v1.21/images/create?fromImage=AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com%2Fcloud%3Aotp10Mar2016v4
```

PS: I am using Marathon version 0.15.2, Mesos 0.26.

**Comment by weitzj** [comment] 2016-04-09 11:16
You have to reauthenticate every 12 hours on AWS ECR to get new credentials which you can use in your `docker pull ` or `.docker` directory before you create your docker.tar.gz file. 
I wonder if there is a `aws-cli` plugin/framework, which you can run automatically before each docker pull

**Comment by anhcuong** [comment] 2016-04-10 08:04
I did the same thing. Even I manually login successfully from the worker itself, the marathon still cannot pull the image. 
However, I found out this might be a bug from aws ecr and host it my self using marathon and it works great!

**Comment by aquamatthias** [comment] 2016-04-28 10:03
Seems a AWS ECR problem. Close this issue.

**Comment by bchav** [comment] 2016-05-05 17:54
Hi! We'd love to help fix this issue. Feel free to reach out to me directly.

**Comment by thefotios** [comment] 2016-05-05 18:21
I'm having the same issue. Maybe it's a combination of ECR configs and my app definition, but can't seem to get this working.

Anybody have any luck?

**Comment by weitzj** [comment] 2016-05-05 18:38
My Workaround is right now to have a cronjob on every nide, which does an aws ecr get-login

**Comment by anhcuong** [comment] 2016-05-06 01:12
I recommend  to move away from aws ecr because it seems not stable yet and I have encountered some funny issues with it (my last try was 2 months ago). 
Instead, we host docker registry ourself using marathon on mesos. It is working very well now.

**Comment by OferE** [comment] 2016-09-18 05:16
did anyone succeeded in this - as this is critical to me?

**Comment by gengmao** [comment] 2016-09-18 21:35
@OferE I use https://github.com/awslabs/amazon-ecr-credential-helper with a .docker/config.json like below:
```
{
    "credsStore":"ecr-login",
    "auths": {
        "123456789012.dkr.ecr.us-west-2.amazonaws.com": {
        }
    }
}
```
And I package it into a docker.tar.gz file and set it to marathon's "uris" parameter as described in https://mesosphere.github.io/marathon/docs/native-docker-private-registry.html, it worked. 

But the .docker/config.json doesn't work with the new --docker_config option (see http://mesos.apache.org/documentation/latest/docker-containerizer/) which is brought in Mesos 1.0. I created the https://issues.apache.org/jira/browse/MESOS-6169 to track it.

**Comment by OferE** [comment] 2016-09-19 02:50
@gengmao thanks for the info!

**Comment by gengmao** [comment] 2016-09-20 07:53
@OferE I found https://issues.apache.org/jira/browse/MESOS-6169 is not a bug. 
Just remember to have the "auths" part in .docker/config.json, without it mesos-agent won't be able to pull docker image. Without it the https://github.com/awslabs/amazon-ecr-credential-helper can't pull image when docker build too, see https://github.com/awslabs/amazon-ecr-credential-helper/issues/9. 
As long as your "auths" part exists (with your registry in it), the new --docker_config option works fine with ECR.

**Comment by mhausenblas** [comment] 2016-11-11 19:03
I would strongly recommend re-opening this issue @aquamatthias and at the very list provide a workaround. Happy to chime in with docs if that helps …

**Comment by bchav** [comment] 2016-11-11 19:07
Hi everyone, hopefully this can help: https://aws.amazon.com/blogs/apn/automating-ecr-authentication-on-marathon-with-the-amazon-ecr-credential-helper/

**Comment by aquamatthias** [comment] 2016-11-14 07:59
@bchav Thanks for the documentation link.
@mhausenblas By the time this ticket was closed, it looked like an ECR issue. Happy to reopen. 
We should document a manual setup for ECR with Marathon as described by @bchav.
@mhausenblas any help is appreciated.

**Comment by jasongilanfarr** [comment] 2016-11-23 17:24
@sascala can you add usage of ECR as referenced above to the docs?

**Comment by meichstedt** [comment] 2017-03-06 20:45
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4333. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment] 2017-03-07 11:54
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4333. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Closed** 2017-03-27 07:42 UTC
