### ISSUE TITLE
Timezone offset in UI

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1038] opened 2015-01-19 09:39 UTC
In `/v2/tasks` api:

```json
    {
      "appId": "/topface/prod-test/app",
      "id": "topface_prod-test_app.e6c6c92a-9fbd-11e4-b3e6-56847afe9799",
      "host": "web309",
      "ports": [
        31307
      ],
      "startedAt": "2015-01-19T09:33:43.770Z",
      "stagedAt": "2015-01-19T09:31:09.738Z",
      "version": "2015-01-19T09:30:03.738Z",
      "servicePorts": [
        14000
      ],
      "healthCheckResults": [
        {
          "taskId": "topface_prod-test_app.e6c6c92a-9fbd-11e4-b3e6-56847afe9799",
          "firstSuccess": "2015-01-19T09:33:45.460Z",
          "lastSuccess": "2015-01-19T09:34:11.721Z",
          "lastFailure": null,
          "consecutiveFailures": 0,
          "alive": true
        }
      ]
    }
```

In UI:

![screen shot 2015-01-19 at 12 37 50](https://cloud.githubusercontent.com/assets/89186/5798428/03295fb6-9fd8-11e4-926d-bc8bb18f34ec.png)

JS timezone offset from firefox 35 console:

```
12:35:14.197 new Date().getTimezoneOffset();
12:35:14.200 -180
```

I'm in Europe/Moscow, UTC+3. It was UTC+4 some time ago.

**Comment by aldipower** [comment] 2015-08-06 13:41
The UI uses the updatedAt-field, which isn't reflected in this JSON I can see here.
Maybe the updatedAt differs in some case and lead to confusion.
In order we had a bigger refactoring of Marathon UI in the meantime and I can't reproduces this issue, I will close this now.
If you provide newer information with current UI version, we can reopen this of course.

**Closed** 2015-08-06 13:41 UTC
Labels: analyze, bug, gui, OKR Usability

**Comment by bobrik** [comment] 2015-08-06 13:48
Well, I physically change my timezone twice and now I don't see this issue.
