### ISSUE TITLE
Marathon keeps trying to start docker containers, even though instances are set at 1

### ISSUE THREAD

**Issue by sarlindo** [mesosphere/marathon#2555] opened 2015-11-03 16:11 UTC
I am running into an issue where marathon keeps trying to start docker containers, even though instances are set at 1.

**My Environment:**

marathon version 0.11.1, docker version 1.8.3 running on ubuntu 14.04.

**Steps:**

a) through the marathon gui I created a new app with the following command that will startup a jenkins container.

sudo docker run -d -u root -p 8090:8080 -v /var/jenkins_home csanchez/jenkins-for-volumes

instances are set to 1.

**Results:**

marathon starts the container properly because when I do a "docker ps" i see the container running and I can also navigate to the jenkins app without issue.

However, marathon for some reason keeps trying to execute the container.

In the mesos framework UI "sandbox" in the stdout logs I see the first start of the container, which is good:

> Registered executor on node2
> 
> 
> > 
> > Starting task jenkins.0c3759e5-8240-11e5-a1f1-0800271b9791 sh -c 'sudo
> > docker run -d -u root -p 8090:8080 -v /var/jenkins_home
> > csanchez/jenkins-for-volumes ' Forked command at 2694
> > effba5cc78bc810e6e4cce3b578fbe7381035f47c6e912d0ac951aec432d0ef9
> > Command exited with status 0 (pid: 2694)

BUT, then I see a bunch of failures after because marathon is trying to start another container and failing on port binding as can be seen in the "stderr" logs:

> I1103 15:31:19.721882  2792 exec.cpp:134] Version: 0.25.0 I1103
> 15:31:19.769901  2797 exec.cpp:208] Executor registered on slave
> d2bf6a4e-f666-4d92-a2a6-74a8f5daf9a3-S1 Error response from daemon:
> Cannot start container
> 1d4eb6c91afeecf60e6ca258c6f85df7e51ef33ec0fcfa2514b6209f408345fd: Bind
> for 0.0.0.0:8090 failed: port is already allocated

This to me seems like some sort of bug? Why does marathon keep trying to start up containers?

**Comment by pierlo-upitup** [comment] 2015-11-10 10:05
Hi @sarlindo 

to run Docker containers you do not need to supply the docker run command. Simply fill in the `Container settings` part of the UI create dialog, or supply the relevant JSON fields [as described in the docs](https://mesosphere.github.io/marathon/docs/native-docker.html). Have you tried doing that?

**Comment by hotstepper13** [comment] 2015-11-10 10:54
This is not a BUG in Marathin. You have to remove the "-d" parameter as it will detach the docker container from the running shell, avoiding that marathon knows if the process is running or not.

First stop your marathon deployment (and maybe remove the application from marathon).

Now kill all existing containers (docker ps -a and docker kill are your friends).

Also i recommend to add the "--rm" switch to your docker command. This will remove the container as soon as it stops.

Marathon needs to hold the handle on the running container. If the container stops, maraton will recognize this and restart the container.

**Comment by pierlo-upitup** [comment] 2015-11-10 14:44
Thanks for chiming in, @hotstepper13 ! 
@sarlindo does that help?

**Comment by sarlindo** [comment] 2015-11-10 14:49
Hi Pierlo,

I have tried using the container settings of the UI in marathon, but whats not clear is where to put the actual command to run? I see an input box named "Command", but it says "may be left blank if a container image is supplied".

So from the command line without using marathon, I am now trying this command that doesn't involve volumes for now and works just fine without marathon.

sudo docker run -d -p=6379:6379 build/redis /usr/bin/redis-server

Now in the GUI, I have tried the following:

a) in the command input box, I placed /usr/bin/redis-server
b) in the container settings in the image input box, i placed build/redis
c) in the container settings in the network, i selected bridged
d) in the container settings or container port and host port, i placed 6379

This seems to do nothing and doesn't start any containers.

Also, i have tried using the json yet.

**Comment by sarlindo** [comment] 2015-11-10 15:04
Hi hotstepper13,

Your the man!

Running this command as you suggested seems to work fine.

sudo docker run --rm -p=6379:6379 build/redis /usr/bin/redis-server     (I removed the daemon flag)

Yes and "docker ps" and  "docker rm $(docker ps -aq)" are my friends, but I have found that the "docker rm" is really really slow and makes my cpu spike, maybe a separate issue?

**Comment by pierlo-upitup** [comment] 2015-11-10 15:13
That's great news @sarlindo ! Thanks @hotstepper13 for your help. 
Yeah, I'd say your performance issues are not part of this issue, so I'm closing it.

**Comment by sarlindo** [comment] 2015-11-10 15:51
Pierlo,

before closing can you advise on the proper way to use the container settings of the UI? are the steps i did correct?

**Comment by pierlo-upitup** [comment] 2015-11-10 17:13
@sarlindo 
the UI steps you reported all seem correct to me. I tried to reproduce, and the only issue I had was with the docker image naming (ie `redis` vs `build/redis`) 

Since Marathon 0.11 there is a Debug tab inside the application details page. Click on your app and look at this tab, it will tell you relevant info about the last task failures. Please take a look at the linked Mesos Sandbox for your tasks and take a look at the std_err and std_out to troubleshoot what else might have gone wrong.

Let me know when you have more details.

**Comment by sarlindo** [comment] 2015-11-10 18:11
some more details:

the build/redis is an image that is already downloaded locally on the slave node that this task will run on (only have one slave).

so logging into the slave node and doing a " docker images", it lists out my local image named "build/redis"

In marathon, it seems to be stuck on "waiting" and nothing is entered into the debug tab in terms of any details, also in the mesos UI, it doesn't show this task listed either in active or completed tasks. 

Is it smart enough to try to look for the image locally before going out to docker hub?

**Comment by philipnrmn** [comment] 2015-11-11 09:58
Hi @sarlindo,

The steps you describe in your [earlier comment](https://github.com/mesosphere/marathon/issues/2555#issuecomment-155439767) look like a good start to me. You may wish to check that the `build/redis` Docker image is available to marathon and that you have issued enough resources for the image to run. 

[Here's an example configuration](https://github.com/mesosphere/docker-mesos-marathon-screencast/blob/master/redis.json) for running Redis as a marathon app. 

In general it's a better idea to run Docker apps using Marathon's Docker settings than by issuing `docker run` commands to applications.

**Comment by sarlindo** [comment] 2015-11-12 20:19
@philipnrmn

As i mentioned, i went directly onto the VM running the mesos slave (along with docker) and did a "docker images" command and I see my image "build/redis" listed. So I assume this in essences makes it available to Marathon?  Or must my image reside on the Master node where mesos master and marathon framework are installed?

**Comment by kolloch** [comment] 2015-11-17 15:46
Hi @sarlindo,

you most likely have a problem with the hostPort not being available. If you specify a host port, it has to be available in the "offer" that Marathon receives from the "agent" (usually there is one mesos agent per host). Otherwise it will not start the task.

 By default the port that you specified is not offered by the mesos agent. See here for hints for the configuration: http://mesos.apache.org/documentation/attributes-resources/

I will close this for now but if it does not solve your problem, please reopen this issue.

**Closed by kolloch** 2015-11-17 15:46 UTC

**Comment by sarlindo** [comment] 2015-11-19 16:09
@kolloch, I see that in the documentation that you directed me to that mesos-slaves by default does not expose the ports that i specify and can configured with the --resources flag. 

BUT what I don't understand is that when I use the command in marathon to launch docker, the port assignment works for port 8080 and I can hit the application without issue?

such as:

"cmd": "sudo docker run --rm -p 8080:8080 sarlindo/wildfly-app"

However, if I don't use the command and instead use the container settings such as

container..
type: docker.. 
image ...
"portMappings" : [
   { "containerPort": 8080, "hostPort": 8080 etc....

This does not work and when I look at the marathon logs, it's complaining about that port not being available, which is what you hinted at.

Can you please explain the differences between both methods?

**Comment by kolloch** [comment] 2015-11-20 11:49
@sarlindo: Mesos does not isolate network ports by default. In addition, Marathon does not analyze the command you specify to guess what ports you are using. What your "sudo docker ..." command in effect does is:

* it opens a network connection to the docker daemon on that machine
* instructs it to create the specified app

That bypasses Mesos nearly completely.

The other possibility does use Mesos and thus runs into the restrictions that you saw.

**Comment by sarlindo** [comment] 2015-11-20 15:21
@kolloch : Understood thanks.

**Comment by jazzista88** [comment] 2016-03-02 17:59
Hil all
I am an italian student of telecommunication engineering at Bologna University. I'm starting my maater thesis nd i have to use marathon mesos docker and i have some questions to clarify my confusion.
Actually i made 5 virtual machines by means openstack: one master on which i installed marathon mesos chronos and docker, and 4 slaves. First question, i need to install docker on slaves too?
Second i understood how to make a simple http server using marathon UI but i dont inderstand how to make web apps using docker images on marathon, could you please tell me the steps to follow? I am completely new to marathon world so please be patient.
I tried to follow this tutorial:https://open.mesosphere.com/advanced-course/deploying-a-web-app-using-docker/

But it is not clear for me, when i try to run:
sudo docker run --publish 6060:8080 --name test --rm outyet
Marathon rins the app but after few seconds it is waiting and then running and always like this, every time i saw that when the app comes to run the port changes every time.
So i am too confused and i need help to understand which are the steps to make a web app using docker image on marathon.

Thanks all

Best regards!

**Comment by hotstepper13** [comment] 2016-03-03 06:53
Yes, you need to install Docker on each Slave that should be able to run docker commands. The Sudo might not be necessary if mesos-slave is running as root which means that the command will be executed with the same permissions. 

Dont be confused regarding the port Marathon shows you. As you "nail" you application to listen on port 6060 (that is the port outside of the container) you may reach the application. But this also means that you can have only one instance per Host and you must define the needed constraints for it 

  "constraints": [["hostname", "UNIQUE"]]


To make use of the dynamic port feauture just use the following command:

  docker run --publish $PORT0:8080 --name test --rm outyet

From my point of view you should use Marathon only for service orchestration which means to deploy you containers (apps/tasks). Your application run inside the containers and you have to take care of some sort of service discovery and so on. There are some Frameworks than can be directly deployed in Mesos but in my personal opinion we split the to use cases (Service Orchestration / Application)

If you need further help, please do not highjack any issue. Just create a new one and flag it as question.

Best regards
Frank

**Comment by vinodhbasavani** [comment] 2016-03-24 06:09
I have started the marathon and mesos services successfully.
I am able to run the docker commands without sudo.
and I am not able to create the containers from marathon gui?
can some one help me?
Best regards
vinodh

**Comment by muthulakshmi1990** [comment] 2017-01-10 07:59
can we install cassandra in mesos without docker container or by using the mesos default container?
