### ISSUE TITLE
Is it possible to notify the Marathon UI that there are Insufficient resources or other messages?

### ISSUE THREAD

**Issue by bernadinm** [mesosphere/marathon#3959] opened 2016-06-02 00:10 UTC
Running Marathon 1.1.1:

I have created a sleep101 application in marathon and it is just sitting there in deployments waiting. However from a users perspective marathon is not working, however Marathon is waiting for an acceptable offer from Mesos to launch the application but the user does not know that.

Can we at least place this information in the instances tab where it would rather show 

No Tasks Running
Running tasks will be shown here.

Instead show:

No Tasks Running
Received Insufficient resources from Mesos
Waiting for an acceptable offer
Running tasks will be shown here.

That goes for other issues for that fact.

Which at least will have best efforts to let the user know whats going on.

https://www.dropbox.com/s/mf8c2uibisc8h8o/Screenshot%202016-06-01%2017.05.48.png?dl=0

`Jun 01 23:57:08 ip-10-0-5-92.us-west-2.compute.internal java[1437]: [2016-06-01 23:57:08,664] INFO Offer [0c653b4f-e441-4325-b4d8-1368cebc16fa-O3713]. Insufficient resources for [/sleep101] (need cpus=1.0, mem=128.0, disk=0.0, ports=(1 dynamic), available in offer: [id { value: "0c653b4f-e441-4325-b4d8-1368cebc16fa-O3713" } framework_id { value: "0c653b4f-e441-4325-b4d8-1368cebc16fa-0000" } slave_id { value: "0c653b4f-e441-4325-b4d8-1368cebc16fa-S4" } hostname: "10.0.2.32" resources { name: "ports" type: RANGES ranges { range { begin: 1025 end: 1071 } range { begin: 1073 end: 1124 } range { begin: 1126 end: 1137 } range { begin: 1139 end: 1164 } range { begin: 1166 end: 1182 } range { begin: 1184 end: 1204 } range { begin: 1206 end: 1214 } range { begin: 1216 end: 1221 } range { begin: 1223 end: 1258 } range { begin: 1260 end: 1260 } range { begin: 1262 end: 1287 } range { begin: 1289 end: 1346 } range { begin: 1348 end: 1396 } range { begin: 1398 end: 1579 } range { begin: 1581 end: 1647 } range { begin: 1649 end: 1691 } range { begin: 1693 end: 1780 } range { begin: 1782 end: 1949 } range { begin: 1951 end: 2035 } range { begin: 2037 end: 2157 } range { begin: 2159 end: 2180 } range { begin: 2182 end: 2234 } range { begin: 2236 end: 2336 } range { begin: 2338 end: 2372 } range { begin: 2374 end: 2463 } range { begin: 2465 end: 2562 } range { begin: 2564 end: 2577 } range { begin: 2579 end: 2617 } range { begin: 2619 end: 2642 } range { begin: 2644 end: 2716 } range { begin: 2718 end: 2873 } range { begin: 2875 end: 3096 } range { begin: 3098 end: 3116 } range { begin: 3118 end: 3176 } range { begin: 3178 end: 3223 } range { begin: 3225 end: 3540 } range { begin: 3542 end: 3598 } range { begin: 3600 end: 3626 } range { begin: 3628 end: 3651 } range { begin: 3653 end: 3726 } range { begin: 3728 end: 3740 } range { begin: 3742 end: 3761 } range { begin: 3763 end: 3779 } range { begin: 3781 end: 3846 } range { begin: 3848 end: 3887 } range { begin: 3889 end: 3955 } range { begin: 3957 end: 3966 } range { begin: 3968 end: 4078 } range { begin: 4080 end: 4081 } range { begin: 4083 en`

**Comment by kamilchm** [comment] 2016-06-02 06:50
Duplicate of https://github.com/mesosphere/marathon/issues/1090 ?

**Comment by tmmi** [comment] 2016-06-02 06:51
It might be response https://github.com/mesosphere/marathon/issues/1090 to your problem.

**Comment by gkleiman** [comment] 2016-07-07 10:35
Closing as dupe of #1090.

**Closed by gkleiman** 2016-07-07 10:35 UTC
