### ISSUE TITLE
After I update groups, app not destroy, but groups said it's done

### ISSUE THREAD

**Issue by Guojian** [mesosphere/marathon#1294] opened 2015-03-12 07:46 UTC
I try to update groups and destroy all the apps it seems ok and /v2/groups show no apps anymore.

{
"id": "/",
"apps": [],
"groups": [
{
"id": "/group2",
"apps": [],
"groups": [],
"dependencies": [],
"version": "2015-03-12T07:36:23.755Z"
},
{
"id": "/group4",
"apps": [],
"groups": [],
"dependencies": [],
"version": "2015-03-12T07:36:23.755Z"
},
{
"id": "/group3",
"apps": [],
"groups": [],
"dependencies": [],
"version": "2015-03-12T07:36:23.755Z"
},
{
"id": "/group5",
"apps": [],
"groups": [],
"dependencies": [],
"version": "2015-03-12T07:36:23.755Z"
}
],
"dependencies": [],
"version": "2015-03-12T07:36:23.755Z"
}

but when I use /v2/apps to check,  apps still there

{
"apps": [
{
"id": "/group5/nginx3",
"cmd": null,
"args": [],
"user": null,
"env": {},
"instances": 3,
"cpus": 0.2,
"mem": 256,
"disk": 0,
"executor": "",
"constraints": [],
"uris": [],
"storeUrls": [],
"ports": [
0
],
"requirePorts": false,
"backoffSeconds": 1,
"backoffFactor": 1.15,
"maxLaunchDelaySeconds": 3600,
"container": {
"type": "DOCKER",
"volumes": [],
"docker": {
"image": "nginx",
"network": "BRIDGE",
"portMappings": [
{
"containerPort": 80,
"hostPort": 0,
"servicePort": 4444,
"protocol": "tcp"
}
],
"privileged": false,
"parameters": []
}
},
"healthChecks": [],
"dependencies": [],
"upgradeStrategy": {
"minimumHealthCapacity": 0.5,
"maximumOverCapacity": 0.2
},
"labels": {},
"version": "2015-03-12T07:19:05.701Z",
"tasksStaged": 0,
"tasksRunning": 3,
"deployments": []
}
]
}

If I want to destroy this app now, I have to scale the app first, then it appear again at /v2/groups and destroy it.

Not happen all the time, not sure whether the dependency issue.

**Comment by drexin** [comment] 2015-03-13 17:08
Thanks for reporting this, we'll investigate.

**Comment by kolloch** [comment] 2015-03-17 17:00
Hi Guojian,

Thanks for reporting the issue.

I am currently trying to reproduce the issue. You are using the Marathon API directly, correct?

That's what I tried to do:

1. Creating a group with a couple of apps by a PUT to /v2/groups/some
2. Waiting for the deployment...
3. Updating the group with an empty app array by a PUT to /v2/groups/some
4. Waiting for the deployment....
5. Checking GET /v2/groups and GET /v2/apps

=> Expected error: Still apps in the updated group

Of course, it might not be always reproducible. Do you have the logs of an error case? That would be great.

What do you mean with "not sure whether the dependency issue."?

Thanks!

**Comment by Guojian** [comment] 2015-03-19 10:08
Hi kolloch,

Yes, I use api directly.
I means some apps have dependency among them, the same as group.

I have check the marathon log and mesos log, but seems do not have any error.

I found that if I want to solve this problem, I have to update the problem app(just PUT the id), then app will appear to /v2/groups again, then I put empty array to /v2/groups again, the app will be deleted.

I think there is an error when sync from group to app.

**Comment by kolloch** [comment] 2015-03-20 16:11
Hi @Guojian ,

I didn't necessarily mean only error lines of the log. Just all of the log during the incident with a short explanation what apps were affected.

I could not reproduce the problem but it might be related to #1215 since it resulted in inconsistent apps/groups as well. After my patch has been accepted, it might be worth it to try again.

Do you have any other hints how to reproduce the problem?

Thanks!

**Comment by kolloch** [comment] 2015-04-02 10:46
Hi @Guojian,

can I close this since I cannot reproduce it or do you want to provide further information?

Thanks!

**Closed by kolloch** 2015-04-02 10:46 UTC
