### ISSUE TITLE
Scalar GPU Resource Support

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3795] opened 2016-04-18 14:15 UTC
From the design document referenced below:

"the focus is on supporting a narrow initial use case: homogenous machine-level GPU support (i.e. only 1 kind of GPU per machine)"

**Acceptance Criteria**

* [ ] Introduce a new field "gpus" in the app definition alongside "mem", "cpus" and "disk". Only integer values are allowed.
* [ ] Consume the appropriate amount of "gpus" when launching tasks. To be decided: Do we match a "SCALAR" "gpus" value or a "INTEGER_SCALAR" "gpus" value?
* [ ] Create the appropriate user-facing documentation.

Please note that this might not fulfill all requirements. E.g. look at [this user comment](https://github.com/mesosphere/marathon/issues/375#issuecomment-125449960) @air 

**Testing**

Can we test this by simply configuring a [scalar custom resource](http://mesos.apache.org/documentation/latest/attributes-resources/) "gpus" for now? For example:

```json
{ "name": "gpus", "type": "SCALAR", "scalar": { "value": 8 } }
```

Or is INTEGER_SCALAR support already available and we should rather use:

```json
{ "name": "gpus", "type": "INTEGER_SCALAR", "integer": { "value": 8 } }
```

I could not find it in [mesos.proto](https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L570-L575) yet.

/cc @bmahler @klueska 

**Related Issues**

* Support for arbitrary resource types #375

**References**

Internal [JIRA ticket MARATHON-209](https://mesosphere.atlassian.net/browse/MARATHON-209) and the [design document](https://docs.google.com/document/d/10GJ1A80x4nIEo8kfdeo9B11PIbS1xJrrB4Z373Ifkpo/edit?usp=sharing).

**Comment by seelam** [comment] 2016-05-05 13:39
any update on this?

**Comment by vditya** [comment] 2016-05-13 01:00
@kolloch We worked with @klueska on MESOS 4424, wondering what is the status on Marathon support for GPU. Have you started working on it? If not we can help to expedite the development for it. Let us know

**Comment by kolloch** [comment] 2016-05-15 12:26
Just FYI: Hi @vditya, I will not work on Marathon anymore. So better ask e.g. @aquamatthias

**Comment by vditya** [comment] 2016-05-16 04:22
Thanks for update, Hey Matthias @aquamatthias , any update on GPU support for Marathon effort. If it helps we can support that effort and work with Marathon engineer to enable it.

**Comment by Yubo-Li** [comment] 2016-05-25 14:26
@vditya I've just finished the marathon API support for "gpus". Can we contribute it to here if @aquamatthias confirmed this issue is still not solved?

**Comment by klueska** [comment] 2016-05-25 15:15
@Yubo-Li can you verity that it runs through this properly:
https://github.com/klueska-mesosphere/mesos-gpu-docker

**Comment by Yubo-Li** [comment] 2016-05-26 02:01
Sure, I'll try and give you the result.

**Comment by liyubobj** [comment] 2016-05-31 03:11
@klueska I verified my modification based on your docker scrpits, and it seems work fine:
```
root@ubuntu-x86-gpu:~/liyubo/mesos-gpu-docker# ./deploy-task.sh
{"id":"/gpu-test","cmd":"nvidia-smi; sleep 60;","args":null,"user":null,"env":{},"instances":1,"cpus":0.1,"mem":128,"disk":0,"gpus":1,"executor":"","constraints":[],"uris":[],"fetch":[],"storeUrls":[],"ports":[0],"portDefinitions":[{"port":0,"protocol":"tcp","labels":{}}],"requirePorts":false,"backoffSeconds":1,"backoffFactor":1.15,"maxLaunchDelaySeconds":3600,"container":null,"healthChecks":[],"readinessChecks":[],"dependencies":[],"upgradeStrategy":{"minimumHealthCapacity":1,"maximumOverCapacity":1},"labels":{},"acceptedResourceRoles":null,"ipAddress":null,"version":"2016-05-31T02:38:23.234Z","residency":null,"tasksStaged":0,"tasksRunning":0,"tasksHealthy":0,"tasksUnhealthy":0,"deployments":[{"id":"a8cd75e8-b69b-4f82-89f6-5767fbc5b62b"}],"tasks":[]} 
```
And the output of the command:
```
[root@ubuntu-x86-gpu d8ca7aab-e2c0-4ab8-a3fd-179d4c756a96]# ls
stderr  stdout
[root@ubuntu-x86-gpu d8ca7aab-e2c0-4ab8-a3fd-179d4c756a96]# cat stdout
Received SUBSCRIBED event
Subscribed executor on 9.186.57.67
Received LAUNCH event
Starting task gpu-test.becdd2cd-26d8-11e6-9c94-2ee1446b5607
Forked command at 28
sh -c 'nvidia-smi; sleep 60;'
Tue May 31 02:38:24 2016
+------------------------------------------------------+
| NVIDIA-SMI 346.46     Driver Version: 346.46         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 750     On   | 0000:02:00.0     N/A |                  N/A |
| 36%   35C    P8    N/A /  N/A |      6MiB /  1023MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0            C+G   Not Supported                                         |
+-----------------------------------------------------------------------------+
Command exited with status 0 (pid: 28)
```

**Comment by liyubobj** [comment] 2016-05-31 03:13
I have no server with 2GPUs on hand, so I tested on 1 GPU case. Also, to make the testing running on my local environment, I also made some modifications on the code. Please see the code diff here: 
https://github.com/liyubobj/mesos-gpu-docker/commit/b3e021fb10a625faa5829f3586e85b5edbc698f8
Two anothers things also need to do:
1) Add webUI support of GPU
2) Add test cases

**Comment by Sun-zhe** [comment] 2016-06-15 02:45
Hi, folks, Does anyone know what's going on right now? I'm interested in Marathon support GPU, who is working on it?

**Comment by Sun-zhe** [comment] 2016-06-15 07:26
Since Mesos-0.29 and 1.0 have already supported Nvidia GPUs, I am looking forward to that it happens to Marathon. 
Now I can find the code of GPU only in `./src/test/scala/mesosphere/mesos/ConstraintsTest.scala`, from the path, it seems it's only for test. And can not find any other GPU code in other files.

Does anyone know the progress of GPU in Marathon?

**Comment by liyubobj** [comment] 2016-06-15 07:42
I and @klueska are working on this now. The main function is ready, and I'm still working on the testing code and code review process. Will no long time for GPU landing to Marathon:)

**Comment by DaedalusX** [comment] 2016-06-15 09:29
I'm very much interested in this feature support and have a machine with dual Titan X that I would be willing to test on if you need a multi-GPU test env.

Also, perhaps unrelated to this specific item but is there any work being done to support images built for nvidia-docker?

**Comment by liyubobj** [comment] 2016-06-15 09:39
The mesos docker containerizer GPU support is still on-going, @klueska could give you more details.

**Comment by liyubobj** [comment] 2016-06-20 10:22
Test cases done.

**Comment by Sun-zhe** [comment] 2016-07-11 05:58
@liyubobj What the progress is going on?

**Comment by liyubobj** [comment] 2016-07-11 06:06
@Sun-zhe The basic function is ready but I still need to find somebody who can have a code review and give me feedback...

**Comment by klueska** [comment] 2016-07-11 18:44
@DaedalusX As of last week, Mesos now supports images that run on nvidia-docker (which will be included in the 1.0.0 release).  Marathon integration hasn't been added yet, but you should be able to run these images on Mesos with the mesos containerizer just fine. I am still working on full documentation for this, but it will all be ready by the time the 1.0.0 release comes out in the next week or so.

**Comment by DaedalusX** [comment] 2016-07-11 18:45
Fantastic, I'll give it a spin.

**Comment by klueska** [comment] 2016-07-11 19:02
Since the documentation isn't ready yet, here's a preview to see how I've
been testing it:

Start a master node:
sudo ./bin/mesos-master.sh \
--ip=127.0.0.1 \
--work_dir=/var/lib/mesos

Start an agent:
sudo bin/mesos-agent.sh \
--master=127.0.0.1:5050 \
--work_dir=/var/lib/mesos \
--isolation="cgroups/devices,gpu/nvidia,docker/runtime,filesystem/linux,namespaces/pid"
\
--image_providers=docker \
--executor_environment_variables="{}"

Run an nvidia-docker image:
src/mesos-execute \
    --master=127.0.0.1:5050
    --framework_capabilities="GPU_RESOURCES"
    --name=test
    --docker_image=nvidia/cuda
    --command="nvidia-smi"

**Comment by Sun-zhe** [comment] 2016-07-13 07:29
@liyubobj Hi, is the code in the branch 'nvidia-gpu' of yours?

**Comment by liyubobj** [comment] 2016-07-13 07:38
@Sun-zhe Yes, can you help review the code or find someone for it? The changes are not too much.

**Comment by liyubobj** [comment] 2016-07-13 07:51
@Sun-zhe liyubobj@cn.ibm.com. thanks！

**Comment by seelam** [comment] 2016-07-18 23:48
@Sun-zhe any update on the review:
https://github.com/liyubobj/mesos-gpu-docker/commit/b3e021fb10a625faa5829f3586e85b5edbc698f8
Thanks!

**Comment by chenqiangzhishen** [comment] 2016-08-03 09:17
@klueska , what's the result now of the documentation?

**Comment by liyubobj** [comment] 2016-08-05 04:51
fixed #4112

**Comment by liyubobj** [comment] 2016-08-05 04:52
@kolloch please close this issue, thanks!

**Comment by aquamatthias** [comment] 2016-08-05 09:34
Available in https://github.com/mesosphere/marathon/releases/tag/v1.3.0-RC1 Please test!

**Closed by aquamatthias** 2016-08-05 09:34 UTC
Labels: enhancement, service
