### ISSUE TITLE
Empty JSON being added to JSON editor

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#3394] opened 2016-03-03 14:29 UTC
If the user clicks on a section which contains an own attribute in the fields like 

- `healthChecks` 
- `lables`
- `container`

and afterwards opens the JSON editor those fields are present in the JSON but they are empty. At this point the user hasn't added any of these so it is slightly misleading and adds unnecessary noise to JSON.

The expected functionality is that the JSON only contains the default fields and the empty fields should be excluded.

### Current State
![image](https://cloud.githubusercontent.com/assets/156010/13497002/7a603b00-e153-11e5-9a55-73c6adda2edd.png)

### Expected State
![image](https://cloud.githubusercontent.com/assets/156010/13497206/7ab9b0a8-e154-11e5-9a74-3d4fbedeb2f9.png)

**Comment by pierlo-upitup** [comment] 2016-03-07 13:57
Isn't this a dupe of https://github.com/mesosphere/marathon/issues/3293 ? if so, please close. Thanks!

**Closed** 2016-03-07 13:59 UTC
Labels: gui, usability
