### ISSUE TITLE
As Dan I want to specify multiple Mesos roles for a single Marathon

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2237] opened 2015-09-11 09:44 UTC
As Dan, I would like to use a single Marathon instance to deploy apps to both the `admin` role and the `slave_public` role.

Assumptions
All roles are known at DCOS cluster create time. This is an important assumption because roles can only be specified at Mesos master startup (they are master config flags).

AC
... 

References:
~~https://issues.apache.org/jira/browse/MESOS-1763~~
https://issues.apache.org/jira/browse/MESOS-1142
https://mesosphere.atlassian.net/browse/MARATHON-252

**Comment by kolloch** [comment] 2015-11-04 13:46
This is not yet implemented in Mesos.

**Comment by mwasn** [comment] 2015-11-05 19:16
@kolloch What is exactly missing in Mesos to provide this feature? I only see one dependency to Mesos which is https://issues.apache.org/jira/browse/MESOS-1142 . Please advise.

**Comment by kolloch** [comment] 2015-11-05 21:00
MESOS-1142 is marked as duplicate of https://issues.apache.org/jira/browse/MESOS-1763. MESOS-1763 has been accepted but not implemented.

**Comment by EvanKrall** [comment] 2016-01-20 01:30
This would be very useful for us (Yelp), as we have some apps that don't want to be colocated with other apps. Because Marathon can only register with one role, we'll have to emulate this with constraints or run multiple a Marathon instance per role.

**Comment by meichstedt** [comment] 2017-03-07 12:46
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2775. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Closed** 2017-03-27 07:43 UTC
Labels: analyze, service
