### ISSUE TITLE
Marathon sometimes tries (and fails) to assign duplicated service ports.

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#2868] opened 2015-12-22 17:12 UTC
Steps to reproduce:

1. Start Marathon with the default service ports range: `[10000, 20000]` and no apps.
2. POST /v2/apps with:

```json
{
  "id": "/foo",
  "cmd": "sleep 1000",
  "ports": [0, 10000],
  "requirePorts": false
}
```

Marathon will then try to assign the following service ports: `[10000, 10000]`, fail and return a 422 with the following body:

```json
{
  "message": "Bean is not valid",
  "errors": [
    {
      "attribute": "ports",
      "error": "Elements must be unique"
    }
  ]
}
```

It should instead be cleverer and assign `[10001, 10000]`.

cc/ @vishnu2kmohan

**Comment by aquamatthias** [comment] 2016-01-20 09:08
@gkleiman can you retry with Marathon 0.14?
Could be a duplicate of #2734

**Comment by gkleiman** [comment] 2016-01-20 09:44
@aquamatthias this also happens on Marathon v0.14.0

**Closed** 2016-01-20 11:52 UTC
Labels: bug, in progress, service
