### ISSUE TITLE
Task stuck in killing after launch timeout state

### ISSUE THREAD

**Issue by dgromov** [mesosphere/marathon#1594] opened 2015-06-02 20:54 UTC
Hi,

We were trying to deploy a docker container that seemed to fail very early on in the launch process. No errors were thrown and the tasks are always shown as staging. After 5 minutes the deploy times out and marathon attempts to kill the running task but since the task hasn't started yet it has nothing to kill.

That leads to a state where marathon and mesos are showing the logs below. It is then possible to make marathon forget the deployment buy killing the created app and then rolling back the deployment that gets created from that. However, that leaves some rogue tasks in the Mesos UI, that I don't know how to get rid of besides by restarting the slaves.

I thought maybe this was https://issues.apache.org/jira/browse/MESOS-2583 but I am Mesos 0.22.1 and Marathon 0.8.1 so I'm assuming I should have the fix for it. Does anyone have any thoughts? 

Marathon logs
```
2015-06-02 20:36:40 WARN  TaskTracker:163 - Task 'xxx' was staged 2269s ago and has not yet started
2015-06-02 20:36:40 WARN  TaskTracker:163 - Task 'xxx' was staged 2269s ago and has not yet started
2015-06-02 20:36:40 WARN  MarathonScheduler:90 - There are 2 tasks stuck in staging for more than 300000ms which will be killed
2015-06-02 20:36:40 INFO  MarathonScheduler:92 - About to kill these tasks: List(id: "xxx"
host: "172.16.84.159"
ports: 41006
ports: 41007
staged_at: 1433275131615
version: "2015-06-02T19:58:18.592Z"
, id: "xxx"
host: "172.16.92.253"
ports: 41006
ports: 41007
staged_at: 1433275131627
version: "2015-06-02T19:58:18.592Z"
```

Mesos Logs

```
mesos-slave.INFO:I0602 16:51:53.312650 10715 slave.cpp:1144] Got assigned task xxx for framework 20150529-174259-672272556-5050-23484-0000
mesos-slave.INFO:I0602 16:51:53.312970 10715 slave.cpp:1254] Launching task xxx for framework 20150529-174259-672272556-5050-23484-0000
mesos-slave.INFO:I0602 16:51:53.322818 10715 slave.cpp:4208] Launching executor xxx of framework 20150529-174259-672272556-5050-23484-0000 in work directory yyy
mesos-slave.INFO:I0602 16:51:53.323889 10715 slave.cpp:1401] Queuing task 'xxx' for executor xxx of framework '20150529-174259-672272556-5050-23484-0000
mesos-slave.INFO:I0602 16:51:53.326159 10711 docker.cpp:626] Starting container 'b2e53771-95fa-4802-89e3-5b6a9ce6452b' for task 'xxx' (and executor 'xxx') of framework '20150529-174259-672272556-5050-23484-0000'
mesos-slave.INFO:I0602 16:56:53.323231 10709 slave.cpp:3605] Terminating executor xxx of framework 20150529-174259-672272556-5050-23484-0000 because it did not register within 5mins
mesos-slave.INFO:I0602 16:57:27.444165 10711 slave.cpp:1581] Asked to kill task xxx of framework 20150529-174259-672272556-5050-23484-0000
mesos-slave.INFO:W0602 16:57:27.444278 10711 slave.cpp:1706] Ignoring kill task xxx of framework 20150529-174259-672272556-5050-23484-0000 because the executor 'xxx' is terminating/terminated
mesos-slave.INFO:I0602 17:01:53.764524 10712 slave.cpp:1581] Asked to kill task xxx of framework 20150529-174259-672272556-5050-23484-0000
mesos-slave.INFO:W0602 17:01:53.764591 10712 slave.cpp:1706] Ignoring kill task xxx of framework 20150529-174259-672272556-5050-23484-0000 because the executor 'xxx' is terminating/terminated
```

**Comment by kolloch** [comment] 2015-06-03 08:53
Hi @dgromov, that sucks.

Am I correct in assuming that Marathon does not 

* get any update from Mesos after staging? (Look for "Received status update for task..." in the logs)
* get any response to the killing attempt from Mesos? No `TASK_LOST` or anything?

Thanks for checking.

**Comment by dgromov** [comment] 2015-06-03 13:03
Hi, @kolloch Thanks for looking into this. 

Both of your assumptions are correct. For the tasking in question I don't get any update after staging, and there is no TASK_LOST sent. Below are the messages, related to this task, that I see:

```
2015-06-02 21:28:48 INFO  MarathonScheduler:149 - Received status update for task xxx: TASK_STAGING (Reconciliation: Latest task state)
...
2015-06-02 21:31:19 WARN  TaskTracker:163 - Task 'xxx' was staged 300s ago and has not yet started
2015-06-02 21:31:19 INFO  MarathonScheduler:92 - About to kill these tasks: List(id: "xxx"
...
2015-06-03 13:00:45 WARN  TaskTracker:163 - Task 'xxx' was staged 56066s ago and has not yet started
```

Some more info: 

* Marathon claims that the app is in deployment this whole time.
* I can't kill the tasks that are having this issue because that leads to the same state as the timeout. However, killing it before the timeout seems to work.
* This task appears in the Queued Tasks of the associated executor according to Mesos.
* I am able to get marathon out of this state by killing the app, and then stopping the resulting deployment.

**Comment by dgromov** [comment] 2015-06-10 23:48
Just to add another data point to this. It also seems possible to get into this state by trying to rollback a deployment where the tasks cannot launch due to lack of resources on Mesos.

**Comment by kolloch** [comment] 2015-06-11 10:38
Thanks for the last info, that should allow us to reproduce the problem potentially!

I just checked. Even if you lost a slave, you should normally get a `TASK_LOST` latest 15min latest if you did not change the default configuration.

http://mesos.apache.org/documentation/latest/slave-recovery/

**Comment by aquamatthias** [comment] 2015-06-17 16:05
If a Kill Task operation is not executed by mesos and no reply is send to that operation, I would consider that as a mesos related bug. I will keep that open - perhaps somebody else has the same problem.

**Comment by nugend** [comment] 2015-06-17 18:50
Think I just hit this while using local Mesos (a dev test instance). The task can't be killed manually either, if that makes it any more interesting. I'm not using the Docker containerizer.

Is there maybe a way to turn on additional logging for the local Mesos instance?

**Comment by bernadinm** [comment] 2015-06-30 23:03
I am also having the same problem. Mesos slave simply goes in a loop asking to kill a task and then ignoring the killing of that task stating that its already being terminated or already terminated. Marathon also does not display this application in the Apps GUI. So I think it shouldn't be running any longer on the Mesos slave, but it is.

I0630 15:47:18.528388 641881 slave.cpp:1372] Asked to kill task zzz.6a30fcc9-1f78-11e5-9944-089e0150898e of framework 20150304-161802-1420689674-5050-25118-0000
W0630 15:47:18.528399 641881 slave.cpp:1490] Ignoring kill task zzz.6a30fcc9-1f78-11e5-9944-089e0150898e of framework 20150304-161802-1420689674-5050-25118-0000 because the executor 'zzz.6a30fcc9-1f78-11e5-9944-089e0150898e' is terminating/terminated
I0630 15:47:18.528411 641881 slave.cpp:1372] Asked to kill task rrr.2d57e648-1f78-11e5-9944-089e0150898e of framework 20150304-161802-1420689674-5050-25118-0000
W0630 15:47:18.528422 641881 slave.cpp:1490] Ignoring kill task rrr.2d57e648-1f78-11e5-9944-089e0150898e of framework 20150304-161802-1420689674-5050-25118-0000 because the executor 'rrr.2d57e648-1f78-11e5-9944-089e0150898e' is terminating/terminated
I0630 15:47:18.528437 641881 slave.cpp:1372] Asked to kill task xxx.90f6d46b-1f78-11e5-9944-089e0150898e of framework 20150304-161802-1420689674-5050-25118-0000
W0630 15:47:18.528448 641881 slave.cpp:1490] Ignoring kill task xxx.90f6d46b-1f78-11e5-9944-089e0150898e of framework 20150304-161802-1420689674-5050-25118-0000 because the executor 'xxx.90f6d46b-1f78-11e5-9944-089e0150898e' is terminating/terminated
I0630 15:47:18.857525 641873 slave.cpp:3321] Current usage 9.49%. Max allowed age: 5.635845503025243days

**Comment by tony-kerz** [comment] 2015-08-28 13:14
i think i have the same thing:
```
I0828 13:04:53.376031 19079 slave.cpp:1581] Asked to kill task hgbot.ea805b4e-4b77-11e5-a260-56847afe9799 of framework 20150727-161809-2248474634-5050-1172-0000
W0828 13:04:53.376132 19079 slave.cpp:1706] Ignoring kill task hgbot.ea805b4e-4b77-11e5-a260-56847afe9799 of framework 20150727-161809-2248474634-5050-1172-0000 because the executor 'hgbot.ea805b4e-4b77-11e5-a260-56847afe9799' is terminating/terminated
```
@dgromov you say:
> I am able to get marathon out of this state by killing the app, and then stopping the resulting deployment.

do you do that via the web interface or cli? does it need to be timed correctly or anything? thx!

**Comment by dgromov** [comment] 2015-08-28 14:34
I did it through the web interface. I've since found that you may also have to restart the mesos-slave with the stuck-task between stopping the deployment and killing the app to get the app to actually die.

**Comment by aquamatthias** [comment] 2015-12-04 09:14
Please create a Mesos issue here: https://issues.apache.org/jira/secure/Dashboard.jspa. I will close this ticket, since there is nothing we can do in Marathon.

**Closed by aquamatthias** 2015-12-04 09:14 UTC
Labels: bug, mesos

**Comment by caussourd** [comment] 2016-03-14 13:53
Was a Mesos issue created? Any link to this issue? Thanks a lot

**Comment by kolloch** [comment] 2016-03-14 15:08
@caussourd I couldn't find an exact matching issue in a timely fashion [here](https://issues.apache.org/jira/browse/MESOS-759?jql=project%20%3D%20MESOS%20AND%20text%20~%20%22Ignoring%20kill%20task%22). If you find something, please comment it here in the issue. Thanks!

**Comment by adam-mesos** [comment] 2016-06-20 08:58
Looks like this finally made it into a MESOS JIRA: https://issues.apache.org/jira/browse/MESOS-5482
