### ISSUE TITLE
Add option to disable HTTP access if HTTPS is enabled.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1360] opened 2015-04-02 20:30 UTC
We could either redirect to the HTTPS port or just turn it off.  Either way, allowing HTTP when HTTPS is enabled seems like a bad situation.  This will require some changes to Chaos.

**Comment by ConnorDoyle** [comment] 2015-04-02 20:31
CC @kolloch @guenter this ticket is "high priority".  Let's try to get this done before the end of the week.

**Comment by guenter** [comment] 2015-04-03 04:02
It's more secure and easier to implement to just turn http off. Let's introduce a new option `--disable-http` so we don't break backwards compat.

**Comment by kolloch** [comment] 2015-04-07 09:57
I agree with Tobi's (@guenter) suggestion. I will try to do that latest by tomorrow so that we still have one review cycle over night left.

**Comment by kolloch** [comment] 2015-04-07 10:43
This is actually a duplicate of #474, do you agree? @guenter @ConnorDoyle 

And it is actually a chaos issue, correct? 

https://github.com/mesosphere/chaos/issues/14

**Closed by kolloch** 2015-04-07 10:43 UTC
Labels: blocker, cleanup, Size: M

**Comment by guenter** [comment] 2015-04-07 17:32
Yes, this is a dupe
