### ISSUE TITLE
Is there a way to perform an HTTPS health Check?

### ISSUE THREAD

**Issue by achalupa74** [mesosphere/marathon#2758] opened 2015-12-03 12:53 UTC
I have a docker container that only exposes and SSL interface (https).  Is there a way to configure the marathon health checks to perform a check on this interface?  The only options for healCheck 'protocol' appear to be HTTP, TCP and COMMAND.  I tried specifying HTTPS and it didn't reject the deployment of the application but it also never completed a successful health check:

"healthChecks": [
    {
      "protocol": "HTTPS",
      "portIndex": 0,
      "path": "/api/version",
      "gracePeriodSeconds": 180,
      "intervalSeconds": 30,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3
    } 

Is there some other way to tell marathon to use https?

I'm using Meso version 0.25.0 and Marathon version 0.13.0.

Thanks!

**Comment by Poogles** [comment] 2015-12-05 14:12
Try setting a specific command as per; https://mesosphere.github.io/marathon/docs/health-checks.html.

You'll want to use something like `curl -k http://$HOST:$PORT0/health`.  I'm guessing it's being marked as healthy due to certificate errors.

**Comment by achalupa74** [comment] 2015-12-17 18:03
I tried changing the health check to run with -k but it still isn't working.  I don't think the COMMAND health check is even firing.  See issue #2760.

**Comment by achalupa74** [comment] 2015-12-18 03:24
We found a work around for this problem. by adding these environment variable to the application json we now see the command health checks firing

"env": {

"MESOS_LAUNCHER_DIR": "/usr/libexec/mesos"
},

taken from here: https://issues.apache.org/jira/browse/MESOS-3738

It would still be nice if marathon could natively support HTTPS health checks so we wouldn't have to use COMMAND checks in their place.  Might be ok to close this issue for now.  or change it into an enhancement request to support https health checks.

**Comment by gkleiman** [comment] 2015-12-18 13:18
Marathon already supports HTTPS healthchecks natively. They might be failing because of an invalid/self-signed certificate.

**Comment by achalupa74** [comment] 2015-12-18 13:20
Can you tell/show me how to implement an HTTPS health check WITHOUT using the 'COMMAND' Health Check protocol?

**Comment by gkleiman** [comment] 2015-12-21 13:51
@achalupa74 the JSON should look exactly like the one you posted.

You can hopefully find the cause of the failing HTTPS health checks in the logs of the Marathon leader, since HTTPS health checks are performed by Marathon and not by Mesos.

**Closed** 2016-02-15 15:58 UTC
Labels: question, service
