### ISSUE TITLE
[UI] Cannot view/modify docker task 'args'

### ISSUE THREAD

**Issue by jolexa** [mesosphere/marathon#3159] opened 2016-02-04 15:22 UTC
Hello,

It seems like something was lost in the latest UI iterations (or maybe it was never there). I can no longer view/edit the docker entrypoint args in the ui.

Steps to reproduce:
1) Upload a app definition that uses args, perhaps like the one below
``` json
{
    "id": "test-dns",
    "cpus": 0.1,
    "mem": 128.0,
    "instances": 1,
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "buildpack-deps:jessie-curl",
            "network": "BRIDGE"
        }
    },
    "env": {
        "MARATHON_HOST": "http://marathon.mesos:8080"
    },
    "args": [
        "sh", "-c", "apt-get update && apt-get -y install dnsutils && host google.com && host marathon.mesos ; sleep 100000"
    ]
}
```
2) View task in UI, try to edit args and redeploy.
3) Notice that args is not present in any UI function

**Comment by philipnrmn** [comment] 2016-02-05 12:26
Hi @jolexa, thanks for the report. 

It's not possible to edit `args` via the modal at present, and to the best of my recollection it never has been. This is because `args` duplicates some of the responsibility of `cmd`, and we felt that offering both was rather confusing and could lead the user into frustrating invalid app configurations. 

I know there are some circumstances in which the `args` field is preferable to `cmd` - for those I'd suggest you use `curl` or possibly check out my [current pet PR](https://github.com/mesosphere/marathon-ui/pull/598).

**Comment by jolexa** [comment] 2016-02-05 16:18
Oohh, json editor looks great!

Regarding the app modal: how about a read only view of "args" if present? I
really think the user should be able to see the entire app definition that
is used, not just part of it.

**Comment by philipnrmn** [comment] 2016-02-06 09:39
The problem we keep circling back to is that there are a lot of optional fields in an app configuration, and the more we add to the modal, the more unwieldy the app creation process seems. We do provide a full overview of the definition in the configuration tab, but it's not possible to edit from that view so you have to choose between reading and writing, which is really not ideal. 

In the long term I think it's worth considering whether a single modal form is the best way to create applications in the UI. It might make sense to move to a more segmented approach.

**Comment by pierlo-upitup** [comment] 2016-02-08 16:06
@jolexa thanks for your feedback! As @philipnrmn already said, "read only" mode to the `args` is already available in the app's Configuration tab. For editing, we believe the best possible solution is going to be via the JSON editor, which is likely to ship in the next major version.
I'm closing this issue for now, but saving your feedback!

**Closed by pierlo-upitup** 2016-02-08 16:06 UTC
Labels: gui

**Comment by memelet** [comment] 2016-03-04 10:33
I don't see args in the Configuration tab for 0.15.2. I thought I did in some previous version though.

For some of our apps most of the configuration are in the args. I don't really care about the model (never use it), but just read only in the Configuration tab for all values set would be very nice

**Comment by jolexa** [comment] 2016-03-05 15:23
@memelet I agree. 

@pierlo-upitup or @philipnrmn - any reasoning here that we aren't aware of?

**Comment by pierlo-upitup** [comment] 2016-03-07 09:51
@jolexa @memelet thanks for bringing this up. After double-checking I can confirm `args` was not being shown in the configuration page. I've opened a PR to have at least that part of the issue closed.

**Comment by pierlo-upitup** [comment] 2016-03-07 10:48
To clarify: the changes introduced in the PR will be part of the upcoming 0.16 release.
