### ISSUE TITLE
Persistent application instance ( sequence? ) id

### ISSUE THREAD

**Issue by andlaz** [mesosphere/marathon#2796] opened 2015-12-08 17:48 UTC
hello-

i was wondering if you see any sense in eventually providing a unique ( or even sequence ) instance id _that persists through the "relocation" of the application instance it is associated with_

consider the following use case:
for any stateful clustered application, currently i need to configure as many applications ( within or outside an application group ) as nodes/members i have in the clustered application, just so i can pass in a unique, persistent ( often sequence ) id for each one of them. The use of this id is to recover state from a remote volume management facility so upon relocation, my nodes' data moves along with it.

This causes my application definitions to explode with duplicated data as cluster size grows ( and of course instead of scaling it, i need to re-launch the entire thing if using an application group, or just add additional applications when not )

i understand this is probably not a trivial change.
I also understand this is probably not the first time  the issue comes up and i apologize if i missed any existing issues on it.

thanks,
Andras

**Comment by Augi** [comment] 2016-01-16 15:21
If I understand your use-case correctly, what about externalizing of application configuration? Like use [Consul](https://www.consul.io/) as configuration storage, or just as ID-assignment authority.

**Comment by andlaz** [comment] 2016-01-25 18:55
in my docker containerized application, i ended up using the "exclusive lock" zookeeper pattern in the entry point to get/create an instance-exclusive ID and a forked, long running client process keep it locked to the running task. This does not guarantee that multiple relocating tasks ( instances ) will use the "same" id, but, with a sufficiently short zookeeper timeout and some sleeping at start, they will at least use the "same set" of IDs, which is sufficient for my use-case.

**Comment by wleese** [comment] 2016-02-29 08:25
related to https://github.com/mesosphere/marathon/issues/1242

**Comment by meichstedt** [comment] 2016-02-29 09:02
Hey @andlaz we're currently adding support for Mesos [Persistent Volumes](http://mesos.apache.org/documentation/latest/persistent-volume/) to Marathon and I'd be great if you can share some thoughts about this.

In your original question, you asked for a persistent ID that survives relocation. That's a sane request since Marathon will relocate unless you specify constraints that prevent that. Now, Persistent Volumes will effectively tie an application to a node so it will keep having access to its Persistent Volume even after a relaunch – which still leaves the question of replicating/backing up your data up to you.

Question 1: Does this scenario change your use case in any way?
Question 2: Are you aware of the efforts regarding Network Storage solutions described [here](http://blog.emccode.com/category/storage-2/mesos-module-dvdi/) and [here](https://github.com/emccode/mesos-module-dvdi)?

Thanks for input
Matthias

**Comment by andlaz** [comment] 2016-02-29 20:37
@meichstedt , thanks for following up. For me, Persistent Volumes make sense when you need the simplicity ( and possibly performance ) of locally hosted data over the high availability and "portability" of task state in shared storage solutions such as the nice integration EMC is cooking up. We are committed to be looking at the latter closely soon and will be evaluating the former for applications that bring their own HA ( such as Cassandra)

However, for now i was looking at the simplest solution for an MVP, with all that is implemented today, and that has turned out to be "mount same volume over all slaves; use the "same set" of unique ids coordinated with zookeeper to formulate data directories"

Having a persistent task id would have simplified this a great deal.

so, i guess
q1: it does not
q2: yes i am

regards,
Andras

**Comment by kolloch** [comment] 2016-04-06 07:52
Seems related to (if not a duplicate of) #1242.

In the context of resident apps (apps with local volumes), I am highly sympathetic with this idea. Resident apps enforce an upgrade strategy that replaces the tasks one by one -- instead of first starting updated tasks and then killing the old tasks as the standard upgradeStrategy does.

**Comment by meichstedt** [comment] 2017-03-06 20:47
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3269. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment] 2017-03-07 12:27
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3269. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Closed** 2017-03-27 07:43 UTC
Labels: analyze, question
