### ISSUE TITLE
Marathon delaying app start by 70min after cluster reboot

### ISSUE THREAD

**Issue by lloesche** [mesosphere/marathon#1456] opened 2015-05-04 15:33 UTC
## Environment
3 node Mesos cluster with master/slave/marathon on all nodes.

## Steps
a) start an app with health checks in Marathon
b) reboot all nodes at the same time
c) upon reboot it will take 70 Minutes for the app to restart

## Complete Marathon Log
https://gist.githubusercontent.com/lloesche/7fe8139fe1463cf80762/raw/gistfile1.txt

## Description
When the cluster rebooted Mesos showed no running tasks. However inside Marathon the app was still shown as running. It took 10 minutes before Marathon recognised that the tasks were no longer running (might have to do with task reconciliation timeout).
After the 10 minutes the Marathon UI showed a Deployment for the App but didn't start any tasks. Inspection of the Log showed
`INFO Delaying /tools/oauth-server due to backoff. Time left: 57 minutes 1 seconds 69 milliseconds. (mesosphere.marathon.tasks.TaskQueue:113)`
The backoff was so high because of the failed health checks during the initial 10 minute wait period.

**Comment by bobrik** [comment] 2015-05-04 15:39
Launch delay strikes again (#1087). I suggest to decrease default max launch delay to something less extreme than 1 hour. 10 minutes?

I don't think that failed health checks in provided scenario should raise backoff to launch new tasks.

Just my 2¢.

**Comment by lloesche** [comment] 2015-05-04 15:53
@bobrik I can see how that alleviates the problem. However waiting 20 minutes instead of 70 is still sort of meh.

**Comment by kolloch** [comment] 2015-05-04 16:27
Thanks for the excellent bug report and the good work around suggestion :)

I see that in `mesosphere.marathon.health.HealthCheckActor#checkConsecutiveFailures` the actor tries to repeatedly kill the task without a response from Mesos (probably because the task does not exist). For every kill try the launch delay is increased which is not helpful.

**Comment by kolloch** [comment] 2015-05-05 14:48
@lloesche: After talking to @drexin it became pretty apparent to me that it is a very unusual use case: Shutting down your whole cluster.

Part of the problem is potentially that your slaves didn't have time to deregister from the mesos master. Thus the mesos master has to wait for the slaves to reconnect potentially. The tasks should be in the LOST state:

http://mesos.apache.org/documentation/latest/high-availability/

This seems to have happened:

```
[...]
May 04 14:31:25 srv3-prod marathon[749]: [2015-05-04 14:31:25,091] INFO Requesting task reconciliation with the Mesos master (mesosphere.marathon.SchedulerActions:472)
[...]
May 04 14:32:30 srv3-prod marathon[749]: [2015-05-04 14:32:30,644] WARN Task [tools_oauth-server.abf6420c-ef42-11e4-b605-4e3d91c04549] for app [/tools/oauth-server] was killed for failing too many health checks (mesosphere.marathon.MarathonScheduler:218)
[...]
[... some other kills ...]
[...]
May 04 14:41:11 srv3-prod marathon[749]: [2015-05-04 14:41:11,155] INFO Received status update for task tools_oauth-server.bdd4fedd-ef42-11e4-b605-4e3d91c04549: TASK_LOST (Reconciliation: Task is unknown) (mesosphere.marathon.MarathonScheduler:149)
```

What is strange is that the TASK_LOST status notifications came ~10 minutes (!) after the reconcileTasks call and ~9 minutes after the kill.

@rukletsov What do you think? Can we improve this somehow?

**Comment by drexin** [comment] 2015-05-05 14:56
10 minutes is the default reregistration timeout. Before that elapses, the tasks will not be marked as lost, because the master is waiting for the slaves to come back.

**Comment by lloesche** [comment] 2015-05-05 21:51
@kolloch I've had entire data centers experience a complete power outage more than once in my life. It's not exactly uncommon and when it happens I bet people are grateful if they don't have to wait an hour for their cluster to recover.
And even if this scenario never hits me in production it's certainly something I (or Dan the DC Operator) will test before deciding for or against a piece of software. From a user point of view this is just odd behaviour (for which there might be valid technical reasons).

**Comment by drexin** [comment] 2015-05-06 04:14
Failing health checks should not increase the task delay, we'll fix that. But the delay because of Mesos eaiting for the slaves to reregister is something Marathon can not influence. The timeout can be configured in Mesos.

**Comment by kolloch** [comment] 2015-05-18 10:56
I think that we cannot improve that further easily.

**Closed by kolloch** 2015-05-18 10:56 UTC
Labels: bug
