### ISSUE TITLE
Remove deprecated ZooKeeper leader election library

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1310] opened 2015-03-18 01:33 UTC
This twitter library is deprecated and should be removed: https://github.com/twitter-archive/scala-zookeeper-client

**Comment by kolloch** [comment] 2015-04-27 09:01
+1

Most build failures currently are because of resolve failures involving the twitter maven repository.

**Comment by air** [comment] 2015-08-30 19:29
Are there other impacts caused by this? Trying to understand for prioritization. Thanks.

**Comment by janisz** [comment] 2016-12-01 22:02
Closed by https://github.com/mesosphere/marathon/pull/3777

**Comment by jeschkies** [comment] 2017-01-23 14:09
Old Twitter leader election has been removed with https://github.com/mesosphere/marathon/commit/b476f32a9dae14674bd758ff650c7fd2fe6f778e.

**Closed by jeschkies** 2017-01-23 14:09 UTC
Labels: debt, in progress, OKR Stability, service
