### ISSUE TITLE
forcePullImage resets after editing app in UI

### ISSUE THREAD

**Issue by Punkrex** [mesosphere/marathon#2674] opened 2015-11-18 21:46 UTC
I've noticed that when you make an edit via the web UI to an app, it will revert forcePullImage to false after a seemingly random number of config changes. 

It can be reset manually by hitting the api, but it is something that has become an annoyance that is keeping me from moving more things into marathon.

**Comment by meichstedt** [comment] 2015-11-19 08:47
@Punkrex Thanks for reporting this!

**Comment by kolloch** [comment] 2015-11-19 13:55
I think that the UI should generally preserve fields it does not know about. Do you agree @philipnrmn ? Should we create a separate issue for that?

**Comment by philipnrmn** [comment] 2015-11-20 08:31
@kolloch absolutely, we should either create a new issue or expand this issue to the general case.

**Comment by philipnrmn** [comment] 2015-12-14 16:07
According to [this comment on the generalised issue](https://github.com/mesosphere/marathon/issues/2693#issuecomment-159891611), there is a bug directly related to `forcePullImage` which is separate to the general case. 

I'd like to fix it but unfortunately I can't reproduce it. Can anybody help me with that? Maybe @aldipower?

**Comment by aldipower** [comment] 2015-12-16 10:49
We exposing ```forcePullImage``` in the application edit modal now, so it shouldn't reset anymore.
https://github.com/mesosphere/marathon-ui/pull/498
Of course this doesn't solve the general issue that unknown options in nested objects aren't preserved.
https://github.com/mesosphere/marathon/issues/2693#issuecomment-159891611
But I think we can close this specfic issue here after https://github.com/mesosphere/marathon-ui/pull/498 is merged.

**Closed** 2015-12-16 10:55 UTC
Labels: analyze, gui, Story-598
