### ISSUE TITLE
GitHub pages configuration is using a deprecated Markdown engine

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#3202] opened 2016-02-09 17:21 UTC
Got a warning when I pushed up the latest docs to the `gh-pages` branch.

```
The page build completed successfully, but returned the following warning:

You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions you can contact us by replying to this email.
```

**Comment by kolloch** [comment] 2016-04-18 08:18
#3489 is a duplicate of this. Since it already got assigned, I am closing this original entry.

**Closed by kolloch** 2016-04-18 08:18 UTC
Labels: docs
