### ISSUE TITLE
Can keyboard shortcuts interfere 

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2033] opened 2015-08-18 17:25 UTC
I've been told that the `c` shortcut to create an app is interfering with native copy/paste. Let's investigate all the keyboard shortcuts across the various os/browser combinations and fix or remove any which are causing issues.

**Comment by aldipower** [comment] 2015-08-18 21:03
It can't because the command for copy is "Ctrl+c" what is not "c". Just tested it and it is not interfering.
Also Moustrap takes care of focus on input fields. If you typing somewhere Mousetrap is disabled.
This issue could be closed, if I don't miss something.

**Comment by air** [comment] 2015-08-18 22:17
Having a 'c' shortcut is not a sin by itself. e.g. Press 'c' in JIRA to get a Create modal in your face.

Maybe the scope of this issue is a review of the shortcuts we have (I've never seen a list).

Useful design ref: https://medium.com/@sashika/j-k-or-how-to-choose-keyboard-shortcuts-for-web-applications-a7c3b7b408ee

**Comment by philipnrmn** [comment] 2015-08-19 13:29
Maybe we could get @pyronicide to clarify the circumstances in which he's seen this happen. Given it's `ctrl+c` causing the problem ref #2032, it would have to be Linux or Windows.

**Comment by philipnrmn** [comment] 2015-08-19 13:35
Here's a current list of keyboard shortcuts (taken from [Marathon.jsx](https://github.com/mesosphere/marathon-ui/blob/master/src/js/components/Marathon.jsx#L42)):

`esc` closes any open modal
`c` opens the create modal
`g a` navigates to the Apps page
`g d` navigations to the Deployments page
`g v` shows the current UI version number
`⇧+,` shows the about modal

**Comment by air** [comment] 2015-08-19 23:14
Perhaps @pyronicide typo'ed `ctrl-c` and was surprised to get a `c` modal?

**Comment by pierlo-upitup** [comment] 2015-09-02 08:49
Can't reproduce – assuming typo. Closing issue.

**Closed by pierlo-upitup** 2015-09-02 08:49 UTC
Labels: analyze, gui, usability
