### ISSUE TITLE
Updating a Label without new deployment.

### ISSUE THREAD

**Issue by ajays20078** [mesosphere/marathon#4057] opened 2016-07-01 11:41 UTC
Is it possible to update a label without triggering a new deployment?

 Currently any label which get updated triggers a new deployment. The Label may not be of significance to the instances  themselves and may be used by LB( HAPROXY_ prefixed labels supported by marathon-lb,),lets say there is a label HAPROXY_WEIGHT, which can dynamically change weight of instance in LB, but it donesn't directly effect the running instances in any way, even for such changes currently there is a new deployment.

So is there  a way to update the labels in configuration without triggering a new deployment?

**Comment by janisz** [comment] 2016-07-01 12:42
Similar to #3945

**Comment by gkleiman** [comment] 2016-07-01 16:50
Closing as dupe of #3945 and labelling #3945 appropriately.

**Closed by gkleiman** 2016-07-01 16:50 UTC
