### ISSUE TITLE
[Feature Request] Expose instance number as ENV to running tasks

### ISSUE THREAD

**Issue by aseppala** [mesosphere/marathon#4593] opened 2016-10-17 11:03 UTC
It would be useful is running tasks would know their instance number. I.e. when application is scaled to 2, instances would know if they are instance number *1* or *2*.

This would help for applications that run in a pull mode to get control on which pool of tasks each instance pulls. Think sharded processing.

**Comment by janisz** [comment] 2016-10-17 15:09
Similar to https://github.com/mesosphere/marathon/issues/1242

**Comment by jdef** [comment] 2016-10-17 15:13
closing this as a duplicate of #1242

**Closed by jdef** 2016-10-17 15:13 UTC

**Comment by isavcic** [comment] 2016-12-12 15:11
Since this one is closed as being the duplicate, is #1242 in the pipeline to get implemented at all?
