### ISSUE TITLE
Marathon api update app doesn't work

### ISSUE THREAD

**Issue by jacob-koren** [mesosphere/marathon#4280] opened 2016-08-31 13:32 UTC
marathon Version 1.3.0-RC4 in dc/os 1.8
Using the RestAPI PUT /v2/apps/{appId} does not update the application.

Currently, I'm deleting and creating the application as a workaround but that means downtime.

**Comment by unterstein** [comment] 2016-08-31 15:09
Hi @jacob-koren,

can you give me an example app definition and an example update request?

Thanks
Johannes

**Comment by colin-msphere** [comment] 2016-08-31 15:47
I have encountered this problem as well. I can use the same payload as a `POST` and the application is created and launched. Using a `PUT` (update) returns a `422` and `ValidationError` stack trace.

App Definition:

```
{
  "id": "testapp",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "<valid docker image name>",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 4000,
          "hostPort": 0
        }
      ]
    }
  },
  "acceptedResourceRoles": [
    "slave_public"
  ],
  "instances": 1,
  "cpus": 0.1,
  "mem": 128
}
```

**Comment by colin-msphere** [comment] 2016-08-31 16:05
Attaching stack trace. This was generated using the app definition in my previous comment.

[app-update-422.txt](https://github.com/mesosphere/marathon/files/447736/app-update-422.txt)

**Comment by colin-msphere** [comment] 2016-08-31 16:14
Attaching HTTP/curl exchange.
[curl.txt](https://github.com/mesosphere/marathon/files/447762/curl.txt)

**Comment by philipnrmn** [comment] 2016-08-31 16:54
That's odd, when I tried to reproduce this I also got success on `POST` and error on `PUT`, but my error was different:

```
{
  "message": "Invalid JSON",
  "details": [
    {
      "path": "",
      "errors": [
        "error.expected.jsarray"
      ]
    }
  ]
}
```

**Comment by philipnrmn** [comment] 2016-08-31 17:48
This is working correctly for me in Marathon v1.3.0-RC3 on DC/OS 1.8, so I guess the issue is specific to RC4.

**Comment by colin-msphere** [comment] 2016-08-31 18:58
My testing was against `1.3.0-RC4`.

**Comment by unterstein** [comment] 2016-09-01 08:12
Hi @colin-msphere, @philipnrmn 

is it possible to re-test this behavior on RC6? RC6 was merged recently to DC/OS.

Thanks
Johannes

**Comment by unterstein** [comment] 2016-09-01 10:30
Hi @colin-msphere, @philipnrmn, @jacob-koren,

Is it possible that https://github.com/mesosphere/marathon/pull/4269 describes your problem?

Kind regards
Johannes

**Comment by unterstein** [comment] 2016-09-01 10:33
Hi @colin-msphere, @philipnrmn, @jacob-koren,

Is it possible that #4269 describes your problem?

Kind regards
Johannes

**Comment by aquamatthias** [comment] 2016-09-01 11:33
With RC4 I get the following validation error:
```
HTTP/1.1 422 
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json
Date: Thu, 01 Sep 2016 11:30:18 GMT
Expires: 0
Pragma: no-cache
Server: Jetty(9.3.6.v20151106)
Transfer-Encoding: chunked
X-Marathon-Leader: http://wrk-2.local:8080

{
    "details": [
        {
            "errors": [
                "AppDefinition must either contain one of 'cmd' or 'args', and/or a non-Mesos 'container'."
            ], 
            "path": "/"
        }
    ], 
    "message": "Object is not valid"
}
```

Which has be fixed in RC6 where I get:
```
HTTP/1.1 201 Created
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json; qs=2
Date: Thu, 01 Sep 2016 11:31:36 GMT
Expires: 0
Location: http://localhost:8080/v2/apps/fo/fo
Pragma: no-cache
Server: Jetty(9.3.6.v20151106)
Transfer-Encoding: chunked
X-Marathon-Leader: http://wrk-2.local:8080

{
    "deploymentId": "6af22783-3e92-48dc-8e3c-b8386dbf254f", 
    "version": "2016-09-01T11:31:36.318Z"
}
```

**Closed by aquamatthias** 2016-09-01 11:33 UTC
Labels: analyze, service
