### ISSUE TITLE
Update Deployment Design Docs

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2616] opened 2015-11-11 08:05 UTC
This is outdated and should be updated:
https://mesosphere.github.io/marathon/docs/deployment-design-doc.html

Most of the proposed new features are implemented.

**Comment by kolloch** [comment] 2015-11-11 13:09
That's a duplicate of https://github.com/mesosphere/marathon/issues/1350, correct?

**Closed by kolloch** 2015-11-11 13:09 UTC
Labels: docs
