### ISSUE TITLE
Tasks health column shows different health status

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2627] opened 2015-11-12 15:31 UTC
The health column on the app tasks lists shows an 'Unknown' health-state on 'Unhealthy'-tasks.
![unknown-health](https://cloud.githubusercontent.com/assets/859154/11122269/bc5949b2-895a-11e5-80a3-d4bfd0ccbb6d.png)

**Comment by aldipower** [comment] 2015-11-12 15:53
OK, some additional information, the base of the data differs.

The health bar that shows the 2 unhealthy tasks uses the health returned by the application.
```javascript
app = {
  tasksRunning: 2,
  taslsUnhealthy: 2
};
```
vs.

The tasks columns are getting their health from the task health check.
![hcr](https://cloud.githubusercontent.com/assets/859154/11122968/cdb357d6-895d-11e5-84eb-bc85efe9ca70.png)

Could be a service related problem.

Ping @gkleiman ?

**Comment by aldipower** [comment] 2015-11-12 15:56
This is my erroneous health check, the http-port isn't existent.

```javascript
[
  {
    "path": "/",
    "protocol": "HTTP",
    "portIndex": 0,
    "gracePeriodSeconds": 300,
    "intervalSeconds": 60,
    "timeoutSeconds": 20,
    "maxConsecutiveFailures": 1,
    "ignoreHttp1xx": false
  }
]
```

**Comment by gkleiman** [comment] 2015-11-13 13:54
@aldipower How did you manage to create that app?

I tried to reproduce this, but I always got:

```json
{
  "error": "Health check port indices must address an element of the ports array or container port mappings."
}
```

**Comment by gkleiman** [comment] 2015-11-13 14:07
Could this be related to #2633?

**Comment by aldipower** [comment] 2015-11-13 14:39
@gkleiman This is my app configuration.
Sorry for posting a screenshot. We need a download json config button in the UI. ;)
![app-config](https://cloud.githubusercontent.com/assets/859154/11148382/c133ed8a-8a1c-11e5-89db-a160fc24e2c3.png)

**Comment by philipnrmn** [comment] 2015-11-13 15:27
Another side-effect of this is that apps with unhealthy tasks go into 'deploying' state.

**Comment by philipnrmn** [comment] 2015-11-13 15:28
@gkleiman yep, #2633 is a duplicate of this bug - hopefully the information in there is useful though.

**Comment by philipnrmn** [comment] 2015-11-13 16:22
So it looks like we handle the healthCheck wrong in the JSON - if it's `alive: false` that's explicitly unhealthy, whereas we show it to be unknown.

**Comment by aldipower** [comment] 2015-11-13 16:23
@philipnrmn If this is true, then this is a bug from the early beginning of the MarathonUI. Wow.

**Closed** 2015-11-17 12:39 UTC
Labels: bug, gui, ready for review

**Comment by mwasn** [comment] 2015-11-18 12:49
@aldipower +1 for the download button
