### ISSUE TITLE
MARATHON_SINGLE_INSTANCE_APP should be a property, not a label

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/marathon#4160] opened 2016-07-29 20:30 UTC
See https://mesosphere.github.io/marathon/docs/recipes.html

Why is this a label?

**Comment by unterstein** [comment] 2016-08-18 15:45
Hi Michael,

this is a good question! We are aware of this and will hopefully refactor this within v3. I`ll close this issue as duplicate of https://github.com/mesosphere/marathon/issues/4225 (your ticket was opened earlier, but @ssk2 has more details).

Kind regards
Johannes

**Closed by unterstein** 2016-08-18 15:45 UTC
