### ISSUE TITLE
Marathon don't match correctly the resources for a defined role

### ISSUE THREAD

**Issue by gomes** [mesosphere/marathon#1520] opened 2015-05-13 05:02 UTC
*Using Marathon 0.8.2-RC2 and Mesos 0.22.1*

I started Marathon with  mesos_role setted as "fixed", a role to aggregate apps with fixed ports. I have another Marathon without mesos_role.
```--mesos_role fixed```

The mesos-slave has the following config:
```--resources=ports(fixed):[31999-32000, 8080-8080, 80-80, 8081-8081, 9000-9000];ports(*):[31000-31998]```

When I launch the app on Marathon, I have this log:
```
[2015-05-13 04:01:50,542] INFO All assigned host ports must be present in the resource offer.
Assigned: [PortMapping(8000,31999,10000,tcp), PortMapping(8080,8080,10001,tcp), PortMapping(80,80,10002,tcp)] (mesosphere.marathon.tasks.PortsMatcher:49)
[2015-05-13 04:01:50,542] WARN App ports are not available in the offer. (mesosphere.mesos.ResourceMatcher$:50)
[2015-05-13 04:01:50,543] INFO No matching offer for /bamboo-sd/v1 (need cpus=1.0, mem=1024.0, disk=0.0, ports=Vector(31999, 8080, 80)) : id {
  value: "20150510-200829-1403029514-5050-25155-O3746573"
}
framework_id {
  value: "20150508-182649-1403029514-5050-22921-0000"
}
slave_id {
  value: "20150510-200829-1403029514-5050-25155-S63"
}
hostname: "10.134.100.50"
resources {
  name: "ports"
  type: RANGES
  ranges {
    range {
      begin: 31000
      end: 31499
    }
    range {
      begin: 31503
      end: 31998
    }
  }
  role: "*"
}
resources {
  name: "cpus"
  type: SCALAR
  scalar {
    value: 7.6000000000000005
  }
  role: "*"
}
resources {
  name: "mem"
  type: SCALAR
  scalar {
    value: 14256.0
  }
  role: "*"
}
resources {
  name: "disk"
  type: SCALAR
  scalar {
    value: 25084.0
  }
  role: "*"
}
resources {
  name: "ports"
  type: RANGES
  ranges {
    range {
      begin: 31999
      end: 32000
    }
    range {
      begin: 8080
      end: 8080
    }
    range {
      begin: 80
      end: 80
    }
    range {
      begin: 8081
      end: 8081
    }
    range {
      begin: 9000
      end: 9000
    }
  }
  role: "fixed"
}
 (mesosphere.mesos.TaskBuilder:37)
```
My app needs ports 31999, 8080 and 80, the slave did the offer, but Marathon don't match.

**Comment by drexin** [comment] 2015-05-13 08:23
Thanks for reporting this issue. It seems to be a bug in the mesos-utils library (https://github.com/mesosphere/mesos-utils). Expect it to be fixed in the next release. For now a workaround is to set the port ranges on the slave to the port you want and the next higher one. E.g. for port 8080 set it to 8080-8081, for 9000 to 9000-9001 and so on. I know this is not a great solution, but it will work until it has been fixed in Marathon.

**Comment by drexin** [comment] 2015-05-13 08:36
Hm, I may have misinterpreted something in the mesos-utils code. I will keep investigating and let you know when I find the cause.

**Closed** 2015-05-28 13:43 UTC
Labels: blocker, bug, ready for review
