### ISSUE TITLE
Resident Tasks: Flaky test: persistent volume will be re-attached and keep state

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3563] opened 2016-03-23 15:51 UTC
```
[14:24:16][Step 3/3] - persistent volume will be re-attached and keep state *** FAILED *** (30 seconds, 378 milliseconds)
[14:24:16][Step 3/3]   java.lang.AssertionError: Waiting for event deployment_success to arrive took longer than 30 seconds. Give up.
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.setup.WaitTestSupport$.next$1(WaitTestSupport.scala:30)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.setup.WaitTestSupport$.waitFor(WaitTestSupport.scala:36)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.setup.MarathonCallbackTestSupport$class.waitForEventMatching(MarathonCallbackTestSupport.scala:48)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForEventMatching(ResidentTaskIntegrationTest.scala:16)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.setup.MarathonCallbackTestSupport$class.waitForEventWith(MarathonCallbackTestSupport.scala:52)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForEventWith(ResidentTaskIntegrationTest.scala:16)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.setup.MarathonCallbackTestSupport$class.waitForEvent(MarathonCallbackTestSupport.scala:32)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.waitForEvent(ResidentTaskIntegrationTest.scala:16)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$3.apply(ResidentTaskIntegrationTest.scala:56)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$3.apply(ResidentTaskIntegrationTest.scala:44)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply$mcV$sp(ResidentTaskIntegrationTest.scala:225)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:225)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest$$anonfun$test$1.apply(ResidentTaskIntegrationTest.scala:225)
[14:24:16][Step 3/3]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[14:24:16][Step 3/3]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[14:24:16][Step 3/3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[14:24:16][Step 3/3]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[14:24:16][Step 3/3]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:158)
[14:24:16][Step 3/3]   at org.scalatest.Suite$class.withFixture(Suite.scala:1121)
[14:24:16][Step 3/3]   at org.scalatest.FunSuite.withFixture(FunSuite.scala:1559)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:155)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:167)
[14:24:16][Step 3/3]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:167)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.org$scalatest$BeforeAndAfter$$super$runTest(ResidentTaskIntegrationTest.scala:16)
[14:24:16][Step 3/3]   at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.runTest(ResidentTaskIntegrationTest.scala:16)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:200)
[14:24:16][Step 3/3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[14:24:16][Step 3/3]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[14:24:16][Step 3/3]   at scala.collection.immutable.List.foreach(List.scala:381)
[14:24:16][Step 3/3]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[14:24:16][Step 3/3]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[14:24:16][Step 3/3]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:200)
[14:24:16][Step 3/3]   at org.scalatest.FunSuite.runTests(FunSuite.scala:1559)
[14:24:16][Step 3/3]   at org.scalatest.Suite$class.run(Suite.scala:1423)
[14:24:16][Step 3/3]   at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1559)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:204)
[14:24:16][Step 3/3]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[14:24:16][Step 3/3]   at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:204)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.org$scalatest$BeforeAndAfterAllConfigMap$$super$run(ResidentTaskIntegrationTest.scala:16)
[14:24:16][Step 3/3]   at org.scalatest.BeforeAndAfterAllConfigMap$class.liftedTree1$1(BeforeAndAfterAllConfigMap.scala:248)
[14:24:16][Step 3/3]   at org.scalatest.BeforeAndAfterAllConfigMap$class.run(BeforeAndAfterAllConfigMap.scala:247)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.org$scalatest$BeforeAndAfter$$super$run(ResidentTaskIntegrationTest.scala:16)
[14:24:16][Step 3/3]   at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
[14:24:16][Step 3/3]   at mesosphere.marathon.integration.ResidentTaskIntegrationTest.run(ResidentTaskIntegrationTest.scala:16)
[14:24:16][Step 3/3]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:444)
[14:24:16][Step 3/3]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:651)
[14:24:16][Step 3/3]   at sbt.ForkMain$Run$2.call(ForkMain.java:294)
[14:24:16][Step 3/3]   at sbt.ForkMain$Run$2.call(ForkMain.java:284)
[14:24:16][Step 3/3]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:24:16][Step 3/3]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:24:16][Step 3/3]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:24:16][Step 3/3]   at java.lang.Thread.run(Thread.java:745)
[14:24:16][Step 3/3]   + Given An app that writes into a persistent volume 
[14:24:16][Step 3/3]   + When a task is launched 
[14:24:16][Step 3/3]   + Then it successfully writes to the persistent volume and then finishes 
```

**Comment by gkleiman** [comment] 2016-03-23 15:51
See https://teamcity.mesosphere.io/viewLog.html?buildId=176705&buildTypeId=Oss_Marathon_IntegrationScaleTests&tab=buildLog#_

**Comment by timcharper** [comment] 2016-11-29 20:20
This test has been marked unstable temporarily. Here is a recent failure: https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-marathon-unstable/lastCompletedBuild/testReport/mesosphere.marathon.integration/ResidentTaskIntegrationTest/resident_task_can_be_deployed_and_write_to_persistent_volume/

**Comment by timcharper** [comment] 2016-12-02 01:13
The present state is that this test is correctly reporting failure. There appears to have been a regression since 1.3.x and I am working on a resolution for Marathon 1.4

**Comment by timcharper** [comment] 2016-12-02 22:46
Resolved by the following patch: https://phabricator.mesosphere.com/D263

**Closed** 2016-12-06 04:12 UTC
Labels: blocker, build, debt, Epic-Tests, flaky-test, ready for review
