### ISSUE TITLE
/v2/schemas/app serves an incorrect schema

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/marathon#1976] opened 2015-08-10 19:19 UTC
The docs show healthChecks.command to be an object with a single 'value' property, but the schema served says it's type 'string'.

**Comment by kolloch** [comment] 2015-08-11 08:19
Thanks for reporting this! This is a duplicate of a recently filed issue,
though.

https://github.com/mesosphere/marathon/issues/1958

**Comment by aquamatthias** [comment] 2015-08-12 12:57
duplicates #1958

**Closed by aquamatthias** 2015-08-12 12:57 UTC
