### ISSUE TITLE
Cassandra in docker is killed

### ISSUE THREAD

**Issue by kbokh** [mesosphere/marathon#4136] opened 2016-07-25 12:34 UTC
I' v tried to launch a cassandra cluster on my mesos cluster in docker by using official docker image. When I launch by using mesos docker executor cassandra process is killed. 

Mesos error log:

> I0725 15:04:20.726328 28366 exec.cpp:143] Version: 0.28.2
> I0725 15:04:20.732655 28372 exec.cpp:217] Executor registered on slave 43a8c5a2-3547-445f-8fc9-d502e32c0893-S0
> Killed

Mesos stdout:

> --container="mesos-43a8c5a2-3547-445f-8fc9-d502e32c0893-S0.955fc319-bbda-4de5-9a08-9221c74157c4" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/usr/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slaves/43a8c5a2-3547-445f-8fc9-d502e32c0893-S0/frameworks/3889d507-0556-46fc-b5d6-72f543fbb4c0-0000/executors/cassandra-test.eb045886-525f-11e6-a795-0242234b032a/runs/955fc319-bbda-4de5-9a08-9221c74157c4" --stop_timeout="0ns"
> --container="mesos-43a8c5a2-3547-445f-8fc9-d502e32c0893-S0.955fc319-bbda-4de5-9a08-9221c74157c4" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/usr/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slaves/43a8c5a2-3547-445f-8fc9-d502e32c0893-S0/frameworks/3889d507-0556-46fc-b5d6-72f543fbb4c0-0000/executors/cassandra-test.eb045886-525f-11e6-a795-0242234b032a/runs/955fc319-bbda-4de5-9a08-9221c74157c4" --stop_timeout="0ns"
> Registered docker executor on 192.168.1.176
> Starting task cassandra-test.eb045886-525f-11e6-a795-0242234b032a

Here is my marathon json:

``` javascript
{
  "id": "/cassandra-test",
  "instances": 3,
  "cpus": 0.5,
  "mem": 128,
  "args": ["cassandra","-f"],
  "constraints": [
    [
      "rack",
      "CLUSTER",
      "system"
    ],
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "HOST",
      "forcePullImage": true,
      "image": "cassandra",
      "parameters": [
                { "key": "user", "value": "cassandra" }
            ]
    }
  },
  "env": {
    "CASSANDRA_CLUSTER_NAME": "Test Cluster",
    "CASSANDRA_SEEDS": "192.168.1.171,192.168.1.176,192.168.1.177",
    "CASSANDRA_DC": "test",
    "CASSANDRA_RACK": "test",
    "CASSANDRA_ENDPOINT_SNITCH": "GossipingPropertyFileSnitch",
    "CASSANDRA_START_RPC": "true"
  }
}
```

But cassandra starts without any problems when docker is launched directly :

``` javascript
{
  "id": "/cassandra-test",
  "cmd": "docker run --net=host --rm --name cassandra -e CASSANDRA_CLUSTER_NAME=\"Test Cluster\" -e CASSANDRA_SEEDS=192.168.1.171,192.168.1.176,192.168.1.177 -e CASSANDRA_DC=test -e CASSANDRA_RACK=test -e CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch -e CASSANDRA_START_RPC=true  cassandra",
  "cpus": 2,
  "mem": 3000,
  "disk": 0,
  "instances": 4,
  "constraints": [
    [
      "rack",
      "CLUSTER",
      "system"
    ],
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "portDefinitions": [
    {
      "port": 10004,
      "protocol": "tcp",
      "labels": {}
    }
  ]
}
```

**Comment by samek** [comment] 2016-07-25 12:42
What are exited docker logs? 
Anyway as for cassandra cluster use a cassandra framework.

**Comment by timcharper** [comment] 2016-07-25 14:25
I would bet a significant sum that you are getting an OOM exception. See `"mem": 128`. This means if your JVM goes over 128mb in ram, it will get killed. These limits are enforced by docker and the settings to do so are turned on by the mesos containerizer. This is not a bug. Recommend close.

**Comment by timcharper** [comment] 2016-07-25 14:26
@samek I'm running Cassandra with Marathon. WHICH Cassandra framework should we use? There's the DC/OS only one, which we tried and voted no on DC/OS because it got in our way in several points, and then the Mesos one which is marked as "experimental".

**Comment by samek** [comment] 2016-07-25 17:43
Tim, 

I have used this https://github.com/mesosphere/cassandra-mesos <https://github.com/mesosphere/cassandra-mesos> one for at least half a year. I switched back  to managed cluster. 

Seams it’s deprecated :(

anyway  you could probably  still run the DC/OS version without DC/OS at the end it’s just a json which is posted to marathon.

**Comment by samek** [comment] 2016-07-25 17:46
Anyway as for the original question as @timcharper  noticed 128mb for cassandra just isn't enough.

**Comment by timcharper** [comment] 2016-07-25 18:01
Cool, thanks for responding @samek. We're running quite fine with Cassandra / Marathon / Docker / Weave. We use weave's DNS for node discovery to bootstrap. I'm not sure what we would gain by moving to a framework, but that's my ignorance talking I'm sure. We did have to do a bit of leg work to get the rack property set properly (our solution is to distribute an environment variable file across our cluster describing the mesos-slave on which a container is running, and then mounting that file inside of the container, etc. etc.)

**Comment by meichstedt** [comment] 2017-03-06 20:43
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1761. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment] 2017-03-07 11:24
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1761. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Closed** 2017-03-27 07:42 UTC
Labels: question
