### ISSUE TITLE
Web interface does not handle container parameters correctly

### ISSUE THREAD

**Issue by cmeiklejohn** [mesosphere/marathon#2370] opened 2015-10-07 01:55 UTC
Parameters specified as part of a configuration for launching a docker container if supplied via the REST endpoint and viewed in the web GUI are missing.  Additionally, if parameters are entered through the user interface and saved, they will not persist in the configuration.

**Comment by heyMcFly** [comment] 2015-10-07 07:51
Related to https://github.com/mesosphere/marathon/issues/2338 I guess

**Comment by gkleiman** [comment] 2015-10-07 10:04
Dupe of #2338, the next release will include a fix for this bug.

**Closed by gkleiman** 2015-10-07 10:04 UTC

**Comment by philipnrmn** [comment] 2015-10-12 13:51
Fixed in mesosphere/marathon-ui#290
