### ISSUE TITLE
Empty response for GET /v2/apps?

### ISSUE THREAD

**Issue by kamilchm** [mesosphere/marathon#1585] opened 2015-05-29 08:32 UTC
Marathon 0.8.1 sometimes returns empty responses for ``GET /v2/apps``:
```
$ curl -v mesos-master1:8080/v2/apps
* Hostname was NOT found in DNS cache
*   Trying 192.168.1.79...
* Connected to mesos-master1 (192.168.1.79) port 8080 (#0)
> GET /v2/apps HTTP/1.1
> User-Agent: curl/7.35.0
> Host: mesos-master1:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 0
* Server Jetty(8.y.z-SNAPSHOT) is not blacklisted
< Server: Jetty(8.y.z-SNAPSHOT)
< 

* Connection #0 to host mesos-master1 left intact
```
Grepping syslog gives:
```
May 29 07:04:37 mesos-master1 marathon[25603]: [2015-05-29 07:04:37,806] INFO 192.168.1.77 - [29/May/2015:07:04:37 +0000] "GET /v2/apps HTTP/1.1" 200 0 "-" "curl/7.35.0" (mesosphere.chaos.http.ChaosRequestLog:15)
```

I got 14 of these for 2000 valid responses:
```
May 29 07:04:51 mesos-master1 marathon[25603]: [2015-05-29 07:04:51,313] INFO 192.168.1.77 - [29/May/2015:07:04:48 +0000] "GET /v2/apps HTTP/1.1" 200 3993 "-" "curl/7.35.0" (mesosphere.chaos.http.ChaosRequestLog:15)
```
Any clues?

**Comment by aquamatthias** [comment] 2015-06-16 13:10
@kamilchm did you tried that with 0.8.2? Is it the same result?
I tried this several times, but are not able to reproduce. 
Can you provide some more information, how to achieve this?

**Comment by kamilchm** [comment] 2015-06-22 10:38
I'm updating to 0.8.2 and won't investigate it more with 0.8.1. You can close it for now and I'll try to give you more info if I find the same issue after update.

**Comment by aquamatthias** [comment] 2015-06-22 18:24
Hey @kamilchm. Please make sure, the Marathon instances are configured in a way, that they can find and talk to each other. If not, that could possibly lead to the described behavior. Since there are other issues solved in later versions,  I close this ticket for now. Please reopen, if you still experience this problem.

**Closed by aquamatthias** 2015-06-22 18:24 UTC
Labels: question
