### ISSUE TITLE
Add error if user adds an app with unknown properties

### ISSUE THREAD

**Issue by tamarrow** [mesosphere/marathon#2341] opened 2015-10-02 10:44 UTC
Right now if the user adds an app with extra properties, marathon simply ignores them. It would be nice if the user could be alerted on properties that don't do anything. This is especially helpful when you have a typo in a property name or you think specify conditions to your app that don't exist.

**Comment by meichstedt** [comment] 2015-10-02 11:47
Thanks for suggesting this – we already thought about that, I'll therefore close this as a duplicate of #2164

**Closed by meichstedt** 2015-10-02 11:47 UTC
Labels: usability
