### ISSUE TITLE
API Docs page stops rendering properly part way down

### ISSUE THREAD

**Issue by jobob2992** [mesosphere/marathon#5001] opened 2017-01-20 18:43 UTC
https://mesosphere.github.io/marathon/docs/rest-api.html#server-info
If you look at the last couple sections of this page they stop being rendered and start just being straight HTML. I'm hoping the owner sees these issues or someone knows who owns it.

**Comment by jasongilanfarr** [comment] 2017-01-20 18:44
Duplicate of #4996

**Closed by jasongilanfarr** 2017-01-20 18:44 UTC
