### ISSUE TITLE
Apps created from inside a group have a double forward-slash in their ID

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3663] opened 2016-04-05 14:43 UTC
- Create a group
- Open the group in the UI
- Open the create modal
- id looks like `/group-name//`

ID should look like `/group-name/`

**Comment by pierlo-upitup** [comment] 2016-04-07 09:13
I can't reproduce on current master:

![doubleslash](https://cloud.githubusercontent.com/assets/1078545/14346249/ad047660-fcb1-11e5-89e5-8dd4498da514.gif)

@philipnrmn I wonder if you can reproduce somehow – if not, let's close this issue.

**Comment by philipnrmn** [comment] 2016-04-07 09:37
You can reproduce it by navigating in from the breadcrumb. I wouldn't regard it as a blocker at all, it's just a bit messy. 

![](https://s3.amazonaws.com/f.cl.ly/items/103p1N2d0f2o1s0o0e2p/Screen%20Recording%202016-04-07%20at%2011.36%20AM.gif?v=319fe51f)

**Closed** 2016-04-07 12:54 UTC
Labels: bug, gui, ready for review
