### ISSUE TITLE
Create Design Document for persistent offers and dynamic reservations

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2242] opened 2015-09-14 07:55 UTC

**Comment by mwasn** [comment] 2015-09-14 08:28
Duplicate of https://github.com/mesosphere/marathon-enterprise/issues/3

**Comment by kolloch** [comment] 2015-09-14 17:46
I would suggest prototyping this instead -- it is very hard to foresee all problems without this. Also note that I have some notes about this. Just approach me if you need more info.

**Closed** 2015-09-28 10:52 UTC
Labels: service
