### ISSUE TITLE
Endpoints link uses wrong scheme

### ISSUE THREAD

**Issue by christianparpart** [mesosphere/marathon#3025] opened 2016-01-19 14:49 UTC
With Marathon 0.14.0-RC1 (mesosphere/marathon docker container was used) the endpoints in the details page of an application's task are prefixing the URL with `//` instead of `http://`, which causes it to let the browser choose the HTTP/HTTPS scheme depending on how you serve the Marathon web interface.

In our case we serve Marathon over SSL, that is, the https scheme, but the services we spawn are exposing HTTP (no SSL), and as configured in the health checks - HTTP.

As a fix, the Marathon task's detail page must not use `//` to to auto-select the scheme depending on marathon's view but hard-wire it down the the configured protocol, that is, `http://$HOST:$PORTn/`

**Comment by meichstedt** [comment] 2016-01-19 15:58
FE: is this already fixed in a newer RC?

**Comment by aldipower** [comment] 2016-01-19 16:14
Duplicate of https://github.com/mesosphere/marathon/issues/2974

**Closed** 2016-01-19 16:30 UTC
Labels: analyze, bug, duplicate, gui
