### ISSUE TITLE
Tooltip for health bar in App Collection View

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2657] opened 2015-11-17 13:02 UTC
As a user I want to get more information on the health status of my apps when I hover the health status bar.

Context:

GIVEN is an application group containing apps and/or more groups
WHEN a user hovers the health status bar of the group 
THEN a tooltip is shown summarizing the health state of all underlying tasks
   BUT a barbershop style bar is shown when any app is in state Deploying

GIVEN is an application
WHEN a user hovers the health status bar of the group 
THEN a tooltip is shown summarizing the health state of all underlying tasks
   BUT a barbershop style bar is shown when any app is in state Deploying

Design: https://projects.invisionapp.com/share/RK3D7OUCW#/screens/103316412

**Comment by kolloch** [comment] 2015-11-17 13:25
I don't like the "barbershop style bar" when the app is in state Deploying since it hides useful information. What's the rational behind that?

**Comment by mwasn** [comment] 2015-11-19 15:38
@kolloch This issue doesn´t implement the "barbershop style bar". Please have a look on MARATHON-368 to see the details for that. 

Basically we discussed your concern but decided to take the current approach. If you have many tasks of an app it might be the case that you don´t see that a deployment is going on as the part of the bar might be too small.

**Comment by philipnrmn** [comment] 2015-11-19 17:18
There may by up to six states in the aggregated tooltip:
```
  HEALTHY: 0,
  UNHEALTHY: 1,
  UNKNOWN: 2,
  STAGED: 3,
  OVERCAPACITY: 4,
  UNSCHEDULED: 5
```

Ensure that the tooltip does not overflow the viewport.

**Comment by philipnrmn** [comment] 2015-11-19 17:18
Percentages in the tooltip should be rounded to the nearest integer.

**Comment by kolloch** [comment] 2015-11-23 12:29
@mwasn Maybe we can clarify what is inside a story and what is context information? A headline "context" after the first paragraph would suffice for me.

**Comment by mwasn** [comment] 2015-11-23 12:52
Good idea!

**Comment by philipnrmn** [comment] 2015-11-27 00:59
Re [my earlier comment](https://github.com/mesosphere/marathon/issues/2657#issuecomment-158125203) on states, I'm not convinced that since mesosphere/marathon-ui#438 was merged we should show anything other than healthy, unhealthy and unknown, as in the app detail page.

**Comment by philipnrmn** [comment] 2015-11-27 01:04
Also in relation to the app detail page, we should remove the tooltip from the health bar there to avoid showing the same information twice.

**Comment by philipnrmn** [comment] 2015-11-27 11:40
Are the three Healthy/Unhealthy/Unknown fields always shown in the tooltip, even when their value is 0? If not, what should be displayed when an app is deploying and all are 0?

**Comment by mwasn** [comment] 2015-11-27 12:00
@philipnrmn 
Agree that we shouldn´t show the tooltip on app detail page to avoid duplicated information
I would say that we should always show the values even if their value is 0.

**Comment by philipnrmn** [comment] 2015-11-27 13:25
:+1: makes sense

**Comment by aldipower** [comment] 2015-11-30 10:47
Sorry for hooking in that late on the states.
Only showing ```health```, ```unhealthy``` and ```unknown``` (the actual health) and not displaying the other states like ```staged``` and ```over-capacity``` feels like a regression to me.
I could be fine with that, but I want to here some opinions before we finally decide to remove functionality we have.
@aquamatthias @leemunroe 

At least the ```over-capacity``` you could see at the numbers, but ```staged``` completely went away.
![hb-3](https://cloud.githubusercontent.com/assets/859154/11469623/02cc5366-9758-11e5-8e3d-8dbe621516f5.png)

**Comment by philipnrmn** [comment] 2015-11-30 16:46
Here's how the tooltip looks with all fields (we'd obviously need to add coloured dots for the other three states)

<img width="260" alt="2657-all-fields" src="https://cloud.githubusercontent.com/assets/2989362/11477831/1a32cf3a-978a-11e5-9017-17edc8022e09.png">

**Comment by philipnrmn** [comment] 2015-11-30 17:19
This wasn't a huge amount of work so I did a quick test implementation of @mwasn's suggestion:

![](https://s3.amazonaws.com/f.cl.ly/items/2J2X1j230k3j0101153D/Screen%20Recording%202015-11-30%20at%2006.18%20pm.gif)

**Comment by aldipower** [comment] 2015-11-30 17:21
@philipnrmn: Kewl.

**Comment by pierlo-upitup** [comment] 2015-11-30 17:21
That looks great to me. Regarding the additional "dots" – I think we can reuse the unknown dot as it's neutral.

**Comment by philipnrmn** [comment] 2015-11-30 17:22
We have the colours in the health bar already, it was just a matter of adding a couple of variables.

**Comment by pierlo-upitup** [comment] 2015-11-30 17:22
Oh yeah, that is true.

**Comment by philipnrmn** [comment] 2015-11-30 17:23
Patch here if you like:
[Add_optional_fields_in_app_health_tooltip.patch.txt](https://github.com/mesosphere/marathon/files/47566/Add_optional_fields_in_app_health_tooltip.patch.txt)

**Comment by mwasn** [comment] 2015-11-30 18:15
LGTM

**Comment by philipnrmn** [comment] 2015-12-01 13:44
Sorry, fat fingers moment

**Comment by leemunroe** [comment] 2015-12-01 14:17
+1 for showing the other states (staged, overcapacity, unscheduled) if not zero.

**Comment by philipnrmn** [comment] 2015-12-01 14:42
Cool, thanks @leemunroe.

**Closed** 2015-12-07 12:22 UTC
Labels: gui, ready for review, Story-407
