### ISSUE TITLE
Allow access to Mesos sandbox logs from Marathon UI

### ISSUE THREAD

**Issue by bsideup** [mesosphere/marathon#1871] opened 2015-07-24 08:44 UTC
Currently logs are missing in Marathon UI, and you have to open Mesos UI and search for sandbox to find logs

**Comment by pierlo-upitup** [comment] 2015-07-24 09:08
Duplicate of https://github.com/mesosphere/marathon/issues/878

**Closed by pierlo-upitup** 2015-07-24 09:08 UTC

**Comment by bsideup** [comment] 2015-07-24 09:10
@pierlo-upitup not duplicate. I don't want to open mesos to see logs, I expect this functionality from Marathon OOTB like Singularity did :)

**Comment by pierlo-upitup** [comment] 2015-07-24 09:12
@bsideup You are right – I misinterpreted your description. I think this issue is more representative of your idea https://github.com/mesosphere/marathon/issues/1309 ?

**Comment by bsideup** [comment] 2015-07-24 09:13
@pierlo-upitup yes, sorry, didn't saw #1309 before. Mine is duplicate of #1309  :) Thanks!

**Comment by pierlo-upitup** [comment] 2015-07-24 09:14
Perfect, thank you!
