### ISSUE TITLE
Command health checks do not survive Marathon restart

### ISSUE THREAD

**Issue by sttts** [mesosphere/marathon#916] opened 2014-12-26 23:59 UTC
Create an app with a COMMAND health checks. When the app turns healthy, restart Marathon (probably a leader change will also be sufficient). The app will stay grey. 

The Mesos COMMAND health check is still running at this point because its output is visible in the task's stdout/err, but Marathon does not see the health check results anymore.

**Comment by hekaldama** [comment] 2015-10-26 21:04
@sttts does #963 fix this for you?

**Comment by sttts** [comment] 2015-10-30 19:06
Currently I lack the setup to test this unfortunately. But I believe to remember that even a task reconciliation did not help.

**Comment by aquamatthias** [comment] 2015-12-04 09:08
Need to analyze, if this problem still exists.

**Comment by kensipe** [comment] 2016-06-29 10:12
This is a duplicate of an issue being worked on:  https://github.com/mesosphere/marathon/issues/3957

Closing this issue!

**Closed by kensipe** 2016-06-29 10:12 UTC
Labels: analyze, bug
