### ISSUE TITLE
Marathon treats working tasks as unhealthy and kills them

### ISSUE THREAD

**Issue by IharKrasnik** [mesosphere/marathon#2874] opened 2015-12-23 14:55 UTC
Hi, I have a bunch of applications deployed in dockers on Mesos (v0.22.1) and Marathon (v0.9.0).
Sometimes services restarting in Mesos (completed tasks status is KILLED).

Services use HTTP health checks (intervalSeconds = 30, maxConsecutiveFailures = 3, timeoutSeconds = 20).
It happens randomly and sometimes I even can see when task turns red at Marathon UI even so http check works well in browser (so service is healthy) and then Marathon kills and restart service that impacts overall system performance.

Log:
I1223 12:23:45.058763 32718 slave.cpp:1581] Asked to kill task prod-tracker-backend-processor.63dbfa9b-a965-11e5-a046-e24e
30c7374f of framework 20150527-135958-3712123914-5050-2238-0000

I1223 12:23:45.189750 32720 slave.cpp:2531] Handling status update TASK_KILLED (UUID: 09e76bce-f24c-4999-8933-270baf023c62
) for task prod-tracker-backend-processor.63dbfa9b-a965-11e5-a046-e24e30c7374f of framework 20150527-135958-3712123914-505
0-2238-0000 from executor(1)@10.132.66.219:33503

I1223 12:23:45.214113 32718 docker.cpp:1009] Updated 'cpu.shares' to 102 at /sys/fs/cgroup/cpu/docker/9e0bc3b40ad9b37c4a0f
6133ca1316c2addd2e2c5a7941e56a4e1770d7afd3a2 for container 9dad82a5-34e1-4bf9-a641-17129464a226

W1223 12:23:45.214740 32718 docker.cpp:1021] Container 9dad82a5-34e1-4bf9-a641-17129464a226 does not appear to be a member
 of a cgroup where the 'memory' subsystem is mounted

I1223 12:23:45.216114 32724 status_update_manager.cpp:317] Received status update TASK_KILLED (UUID: 09e76bce-f24c-4999-89
33-270baf023c62) for task prod-tracker-backend-processor.63dbfa9b-a965-11e5-a046-e24e30c7374f of framework 20150527-135958
-3712123914-5050-2238-0000

I1223 12:23:45.216359 32724 status_update_manager.hpp:346] Checkpointing UPDATE for status update TASK_KILLED (UUID: 09e76
bce-f24c-4999-8933-270baf023c62) for task prod-tracker-backend-processor.63dbfa9b-a965-11e5-a046-e24e30c7374f of framework
 20150527-135958-3712123914-5050-2238-0000

I1223 12:23:45.221278 32720 slave.cpp:2776] Forwarding the update TASK_KILLED (UUID: 09e76bce-f24c-4999-8933-270baf023c62)
 for task prod-tracker-backend-processor.63dbfa9b-a965-11e5-a046-e24e30c7374f of framework 20150527-135958-3712123914-5050
-2238-0000 to master@10.132.8.65:5050

I1223 12:23:45.222024 32720 slave.cpp:2709] Sending acknowledgement for status update TASK_KILLED (UUID: 09e76bce-f24c-499
9-8933-270baf023c62) for task prod-tracker-backend-processor.63dbfa9b-a965-11e5-a046-e24e30c7374f of framework 20150527-13
5958-3712123914-5050-2238-0000 to executor(1)@10.132.66.219:33503

I1223 12:23:45.233886 32725 status_update_manager.cpp:389] Received status update acknowledgement (UUID: 09e76bce-f24c-499
9-8933-270baf023c62) for task prod-tracker-backend-processor.63dbfa9b-a965-11e5-a046-e24e30c7374f of framework 20150527-13
5958-3712123914-5050-2238-0000

**Comment by gkleiman** [comment] 2015-12-29 17:53
A lot has changed since Marathon v0.9.0. Does this also happen with a more recent version?

HTTP health checks are performed by the Marathon leader. It would be useful to get the Marathon logs corresponding to the failing health checks.

**Comment by IharKrasnik** [comment] 2016-01-05 16:33
@gkleiman thanks for reply, I am migrating to the newer marathon and mesos versions now
Where can I find Marathon logs?

**Comment by gkleiman** [comment] 2016-01-05 16:37
@IharKrasnik by default Marathon will log to stdout, but depending your configuration you might also find the logs somewhere in /var/log/

**Comment by jgarcia-mesosphere** [comment] 2016-02-09 00:39
@IharKrasnik I'm looking at this in relation to another issue. Are you still seeing the problem?

**Comment by IharKrasnik** [comment] 2016-02-09 09:50
@jgarcia-mesosphere hi, yes I still have this issue but only with Marathon 0.9.0 + Mesos 0.22.1. The newer cluster with Marathon 0.13.0 and Mesos 0.26.0 seems to be ok

**Comment by mdulla** [comment] 2016-04-25 21:49
I have the same issue on RHEL7 system. Basically at random times the container is getting killed and an message is getting thrown out in the log as  "...slave.cpp:1890] Asked to kill task....". Does anybody know if there is a possible solution discussed somewhere?
Below is my current setup:
Marathon: 0.15.0
Mesos: 0.27.0
Docker: 1.7.1

**Comment by nitram509** [comment] 2016-07-07 09:59
+1 same problem :(

Our environment looks like this:
* CentOS 7
* Marathon: 0.15.2
* Mesos: 0.28.1
* Docker: 1.10.3

### Our Observations

Services running inside docker are killed and restarted, when they do number crunching and/or are close to the memory limit for a few minutes.1

#### background information

* typically we have Java microservices, e.g. running with memory limit "-Xmx512m"
   * the service is doing weather forecast, which just consumes ~400m Heap and runs ~3 hours on a macbook
   * BUT after ~3minutes marathon will kill/restart
   * during the number crunching the /health response times are within range 100ms ... 1200ms, always "200 OK"
* we set marathon / docker limits to "--memory=512m"
   * we also tried marathon / docker limit set to  "--memory=600m" ==> same issue, but happens later
* we set marathon "CPU=0.1"

### Marathon Configuration

Health Checks configuration
```
[
  {
    "path": "/health",
    "protocol": "HTTP",
    "portIndex": 0,
    "gracePeriodSeconds": 30,
    "intervalSeconds": 10,
    "timeoutSeconds": 180,
    "maxConsecutiveFailures": 6,
    "ignoreHttp1xx": false
  }
]
```

Any ideas, what to do to find the root cause?

**Comment by waswrongassembled** [comment] 2016-07-07 10:08
+1 same issue

**Comment by teeschke** [comment] 2016-07-07 10:08
+1

**Comment by tomderuijter** [comment] 2016-07-07 10:09
+1

**Comment by erikpetzold** [comment] 2016-07-07 10:09
+1

**Comment by wavermartijn** [comment] 2016-07-07 10:15
+1 important

**Comment by gkleiman** [comment] 2016-07-07 10:26
@nitram509 can you please post the Marathon leader logs at the time that the task was killed?

One of the health checks probably timed out, making Marathon believe that the task was unhealthy.

**Comment by baralc** [comment] 2016-07-07 10:35
+1

**Comment by gkleiman** [comment] 2016-07-07 10:59
I'm afraid that I cannot help you without logs, so please post some logs instead of +1's ;-)

**Comment by nikhilRP** [comment] 2016-07-07 11:02
+1

**Comment by kensipe** [comment] 2016-07-07 11:35
@nitram509 with java mx and app mem both set to 512m you are certain to get tasks being killed.   It is unclear if 600m is enough headroom for a java process.   we commonly use 1.35x is a starting point which is just under 700m.   You have to account for the JRE memory + heap + perm or metaspace.  JNI etc will also have an impact... it also matters which version of Java you are running.

the difference in your scenario vs the original posts is it is highly possible you are having tasks killed by the OOM cgroup manager instead of marathon.   If this is the case you will see `OOM notifier is triggered for container` in the journal logs of the agent the task was running on.

based on information you provided I would guess you are not seeing issues with marathon but require adjustments in your configuration.   The logs should reveal this either way.

The original post by @IharKrasnik clearly shows the agent log being asked to kill the container.  We need the marathon logs to diagnose that issue.

**Comment by bogue1979** [comment] 2016-07-07 15:32
I have gathered the marathon logs for @nitram509:

```
Jul  7 12:42:34 ip-10-4-1-10 marathon[941]: [2016-07-07 12:42:34,900] INFO Received health result for app [/haarp/air-quality-service/prod] version [2016-07-07T09:38:22.760Z]: [Healthy(haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd,2016-07-07T09:38:22.760Z,2016-07-07T12:42:34.900Z)] (mesosphere.marathon.health.HealthCheckActor:marathon-akka.actor.default-dispatcher-10)
Jul  7 12:42:44 ip-10-4-1-10 marathon[941]: [2016-07-07 12:42:44,921] INFO Received health result for app [/haarp/air-quality-service/prod] version [2016-07-07T09:38:22.760Z]: [Healthy(haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd,2016-07-07T09:38:22.760Z,2016-07-07T12:42:44.921Z)] (mesosphere.marathon.health.HealthCheckActor:marathon-akka.actor.default-dispatcher-20)
Jul  7 12:42:54 ip-10-4-1-10 marathon[941]: [2016-07-07 12:42:54,940] INFO Received health result for app [/haarp/air-quality-service/prod] version [2016-07-07T09:38:22.760Z]: [Healthy(haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd,2016-07-07T09:38:22.760Z,2016-07-07T12:42:54.940Z)] (mesosphere.marathon.health.HealthCheckActor:marathon-akka.actor.default-dispatcher-21)
Jul  7 12:43:04 ip-10-4-1-10 marathon[941]: [2016-07-07 12:43:04,963] INFO Received health result for app [/haarp/air-quality-service/prod] version [2016-07-07T09:38:22.760Z]: [Healthy(haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd,2016-07-07T09:38:22.760Z,2016-07-07T12:43:04.963Z)] (mesosphere.marathon.health.HealthCheckActor:marathon-akka.actor.default-dispatcher-10)
Jul  7 12:43:18 ip-10-4-1-10 marathon[941]: [2016-07-07 12:43:18,855] INFO Received health result for app [/haarp/air-quality-service/prod] version [2016-07-07T09:38:22.760Z]: [Unhealthy(haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd,2016-07-07T09:38:22.760Z,ConnectionAttemptFailedException: Connection attempt to 10.4.1.176:31478 failed,2016-07-07T12:43:18.855Z)] (mesosphere.marathon.health.HealthCheckActor:marathon-akka.actor.default-dispatcher-16)
Jul  7 12:43:19 ip-10-4-1-10 mesos-master[896]: I0707 12:43:19.160756  1646 master.cpp:4763] Status update TASK_FAILED (UUID: befdfd61-cb35-48a0-bca2-e069146ca3a7) for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000 from slave 89a2da04-f31b-401c-84e9-71abbf621399-S9 at slave(1)@10.4.1.176:5051 (10.4.1.176)
Jul  7 12:43:19 ip-10-4-1-10 mesos-master[896]: I0707 12:43:19.160811  1646 master.cpp:4811] Forwarding status update TASK_FAILED (UUID: befdfd61-cb35-48a0-bca2-e069146ca3a7) for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000
Jul  7 12:43:19 ip-10-4-1-10 mesos-master[896]: I0707 12:43:19.160887  1646 master.cpp:6421] Updating the state of task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000 (latest state: TASK_FAILED, status update state: TASK_FAILED)
Jul  7 12:43:19 ip-10-4-1-10 marathon[941]: [2016-07-07 12:43:19,161] INFO Received status update for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd: TASK_FAILED (Docker container run error: Container exited on error: exited with status 137) (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$c6c05dfe:Thread-155280)
Jul  7 12:43:19 ip-10-4-1-10 marathon[941]: [2016-07-07 12:43:19,165] DEBUG Ignoring status for [haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd] with no health information (mesosphere.marathon.health.MarathonHealthCheckManager$$EnhancerByGuice$$f9adff8e:ForkJoinPool-2-worker-119)
Jul  7 12:43:19 ip-10-4-1-10 marathon[941]: [2016-07-07 12:43:19,165] INFO Sending event notification for task [haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd] of app [/haarp/air-quality-service/prod]: TASK_FAILED (mesosphere.marathon.core.task.update.impl.steps.PostToEventStreamStepImpl$$EnhancerByGuice$$176ee50:ForkJoinPool-2-worker-73)
Jul  7 12:43:19 ip-10-4-1-10 marathon[941]: [2016-07-07 12:43:19,166] INFO initiating a scale check for app [/haarp/air-quality-service/prod] after task [haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd}] terminated (mesosphere.marathon.core.task.update.impl.steps.ScaleAppUpdateStepImpl$$EnhancerByGuice$$b159d64b:ForkJoinPool-2-worker-73)
Jul  7 12:43:19 ip-10-4-1-10 mesos-master[896]: I0707 12:43:19.166882  1646 master.cpp:3918] Processing ACKNOWLEDGE call befdfd61-cb35-48a0-bca2-e069146ca3a7 for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000 (marathon) at scheduler-d8efffe0-6462-4383-87a9-65b42d3e11ad@10.4.1.10:59403 on slave 89a2da04-f31b-401c-84e9-71abbf621399-S9
Jul  7 12:43:19 ip-10-4-1-10 mesos-master[896]: I0707 12:43:19.166919  1646 master.cpp:6487] Removing task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd with resources cpus(*):0.1; mem(*):600; ports(*):[31478-31479] of framework 413348e3-a215-4a98-a517-8f3784d86691-0000 on slave 89a2da04-f31b-401c-84e9-71abbf621399-S9 at slave(1)@10.4.1.176:5051 (10.4.1.176)
```

Unfortunately I can only see the ConnectionAttemptFailedException from marathon master.
The last healthy response was at 12:43:18 but one second later the task was updated to TASK_FAILED state. How comes this together with the health check configuration?
   
```
    "intervalSeconds": 10,
    "timeoutSeconds": 180,
    "maxConsecutiveFailures": 6,
```
The logs from the mesos agent regarding this task_id:

```
I0707 11:51:41.991942  4295 status_update_manager.cpp:824] Checkpointing ACK for status update TASK_RUNNING (UUID: 150e9b01-afea-4769-97b4-9b0539f46e8a) for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000

I0707 12:43:19.079092  4288 slave.cpp:3002] Handling status update TASK_FAILED (UUID: befdfd61-cb35-48a0-bca2-e069146ca3a7) for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000 from executor(1)@10.4.1.176:35355
I0707 12:43:19.156324  4295 status_update_manager.cpp:320] Received status update TASK_FAILED (UUID: befdfd61-cb35-48a0-bca2-e069146ca3a7) for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000
I0707 12:43:19.156390  4295 status_update_manager.cpp:824] Checkpointing UPDATE for status update TASK_FAILED (UUID: befdfd61-cb35-48a0-bca2-e069146ca3a7) for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000
I0707 12:43:19.160081  4290 slave.cpp:3400] Forwarding the update TASK_FAILED (UUID: befdfd61-cb35-48a0-bca2-e069146ca3a7) for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000 to master@10.4.1.10:5050
I0707 12:43:19.160192  4290 slave.cpp:3310] Sending acknowledgement for status update TASK_FAILED (UUID: befdfd61-cb35-48a0-bca2-e069146ca3a7) for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000 to executor(1)@10.4.1.176:35355
I0707 12:43:19.167239  4295 status_update_manager.cpp:392] Received status update acknowledgement (UUID: befdfd61-cb35-48a0-bca2-e069146ca3a7) for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000
I0707 12:43:19.167330  4295 status_update_manager.cpp:824] Checkpointing ACK for status update TASK_FAILED (UUID: befdfd61-cb35-48a0-bca2-e069146ca3a7) for task haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd of framework 413348e3-a215-4a98-a517-8f3784d86691-0000
I0707 12:43:20.163040  4295 slave.cpp:3886] Executor 'haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd' of framework 413348e3-a215-4a98-a517-8f3784d86691-0000 exited with status 0
I0707 12:43:20.163080  4295 slave.cpp:3990] Cleaning up executor 'haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd' of framework 413348e3-a215-4a98-a517-8f3784d86691-0000 at executor(1)@10.4.1.176:35355
I0707 12:43:20.163343  4291 gc.cpp:55] Scheduling '/var/lib/mesos/slaves/89a2da04-f31b-401c-84e9-71abbf621399-S9/frameworks/413348e3-a215-4a98-a517-8f3784d86691-0000/executors/haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd/runs/996f332c-7376-4ccb-8d91-513665c6d0bb' for gc 6.99999811042667days in the future
I0707 12:43:20.163404  4291 gc.cpp:55] Scheduling '/var/lib/mesos/slaves/89a2da04-f31b-401c-84e9-71abbf621399-S9/frameworks/413348e3-a215-4a98-a517-8f3784d86691-0000/executors/haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd' for gc 6.99999810962963days in the future
I0707 12:43:20.163439  4291 gc.cpp:55] Scheduling '/var/lib/mesos/meta/slaves/89a2da04-f31b-401c-84e9-71abbf621399-S9/frameworks/413348e3-a215-4a98-a517-8f3784d86691-0000/executors/haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd/runs/996f332c-7376-4ccb-8d91-513665c6d0bb' for gc 6.99999810916741days in the future
I0707 12:43:20.163475  4291 gc.cpp:55] Scheduling '/var/lib/mesos/meta/slaves/89a2da04-f31b-401c-84e9-71abbf621399-S9/frameworks/413348e3-a215-4a98-a517-8f3784d86691-0000/executors/haarp_air-quality-service_prod.2b2c3195-4439-11e6-8f67-02f576c4e3bd' for gc 6.99999810887704days in the future
```

**Comment by gkleiman** [comment] 2016-07-07 15:45
@bogue1979 what those logs show is that Marathon didn't kill the task, so the health checks are just a red herring and not the root cause of the termination. Marathon got a status update from Mesos saying that the task had failed, but it didn't initiate the kill.

I'd hope to find the root cause of the task failure in the Agent logs or in the task sandbox.

**Comment by bogue1979** [comment] 2016-07-07 15:55
@gkleiman Thank you for pointing in the right direction. Will investigate further.

**Comment by nitram509** [comment] 2016-07-08 09:38
We've checked on this machine the kernel log, via 

```journalctl -f _TRANSPORT=kernel```

But there is no log in this relevant time window.

**Comment by gkleiman** [comment] 2016-07-08 11:29
I'm closing this issue, as the logs point to an application or Mesos failure, but not to a bug in Marathon.

**Closed by gkleiman** 2016-07-08 11:29 UTC
Labels: analyze, service

**Comment by nitram509** [comment] 2016-07-11 15:17
Thank you all for your support.

Just for your information, these are the kernel logs, which clearly show, that our concrete JVM process hits the cgroup mem-limit and get's killed.

@kensipe Unfortunately, in our case the factor of 1.35 is not enough, because we use a lot of DirectBuffer (a.k.a. off-heap).

```
kernel: java invoked oom-killer: gfp_mask=0xd0, order=0, oom_score_adj=0
kernel: java cpuset=8efb22f5a09b6621b9aa2507c3a0c35e1b0399588dbb3a073130893cbcdf0c25 mems_allowed=0
kernel: CPU: 1 PID: 9949 Comm: java Tainted: P           OE  ------------   3.10.0-327.13.1.el7.x86_64 #1
kernel: Hardware name: Xen HVM domU, BIOS 4.2.amazon 05/12/2016
kernel:  ffff8801ec262e00 000000008430afbc ffff880072f63cd0 ffffffff8163571c
kernel:  ffff880072f63d60 ffffffff816306bc ffff8802ecd5f330 0000000000000001
kernel:  0000000000000003 ffff880072f63d30 ffffffff8116ca56 ffff880077dd10e8
kernel: Call Trace:
kernel:  [<ffffffff8163571c>] dump_stack+0x19/0x1b
kernel:  [<ffffffff816306bc>] dump_header+0x8e/0x214
kernel:  [<ffffffff8116ca56>] ? find_lock_task_mm+0x56/0xc0
kernel:  [<ffffffff8116ceee>] oom_kill_process+0x24e/0x3b0
kernel:  [<ffffffff81088dae>] ? has_capability_noaudit+0x1e/0x30
kernel:  [<ffffffff811d3bb5>] mem_cgroup_oom_synchronize+0x575/0x5a0
kernel:  [<ffffffff811d2f80>] ? mem_cgroup_charge_common+0xc0/0xc0
kernel:  [<ffffffff8116d764>] pagefault_out_of_memory+0x14/0x90
kernel:  [<ffffffff8162eaec>] mm_fault_error+0x68/0x12b
kernel:  [<ffffffff81641652>] __do_page_fault+0x3e2/0x450
kernel:  [<ffffffff816416e3>] do_page_fault+0x23/0x80
kernel:  [<ffffffff8163d948>] page_fault+0x28/0x30
kernel: Task in /docker/8efb22f5a09b6621b9aa2507c3a0c35e1b0399588dbb3a073130893cbcdf0c25 killed as a result of limit of /docker/8efb22f5a09b6621b9aa2507c3a0c35e1b0399588dbb3a073130893cbcdf0c25
kernel: memory: usage 712704kB, limit 712704kB, failcnt 3707
kernel: memory+swap: usage 712704kB, limit 1425408kB, failcnt 0
kernel: kmem: usage 0kB, limit 9007199254740991kB, failcnt 0
kernel: Memory cgroup stats for /docker/8efb22f5a09b6621b9aa2507c3a0c35e1b0399588dbb3a073130893cbcdf0c25: cache:184KB rss:712480KB rss_huge:583680KB mapped_file:24KB swap:0KB inactive_anon:0KB active_anon:712480KB inactive_file:0KB active_file:80KB unevictable:0KB
kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
kernel: [ 9931]     0  9931  1010807   177506     435        0             0 java
kernel: Memory cgroup out of memory: Kill process 16368 (java) score 998 or sacrifice child
kernel: Killed process 9931 (java) total-vm:4043228kB, anon-rss:710024kB, file-rss:0kB
kernel: docker0: port 4(veth5389cf8) entered disabled state
kernel: docker0: port 4(veth5389cf8) entered disabled state
kernel: device veth5389cf8 left promiscuous mode
kernel: docker0: port 4(veth5389cf8) entered disabled state
```
