### ISSUE TITLE
is there any way to specify the container's name? 

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3743] opened 2016-04-12 09:00 UTC
like this:
"parameters": [
    { "key": "name", "value": "test-name" }
]
but this doesn't work.

thanks!

**Comment by gkleiman** [comment] 2016-04-12 12:39
This is not supported by Mesos, see https://www.mail-archive.com/user@mesos.apache.org/msg05869.html (dupe of #3610)

**Closed by gkleiman** 2016-04-12 12:39 UTC
