### ISSUE TITLE
Jumping tasksRunning numbers when scaling in the UI

### ISSUE THREAD

**Issue by sttts** [mesosphere/marathon#1062] opened 2015-01-21 11:29 UTC
When scaling via the UI, the numbers in the "Tasks / Instances" column first show the new values, then jump back to the old ones after a second. Then the deployment starts and the target values are reached eventually.

**Comment by drexin** [comment] 2015-01-21 11:31
The problem is, that the value is being updated in the UI when the update call returns, but by then the app definition has not been updated in the storage. So if a refresh occurs before the update happened, it flips back to the old value.

**Comment by drexin** [comment] 2015-01-21 11:32
@mlunoe @aldipower Could one of you please look into this? I think we should just wait for the value to be refreshed in the storage.

**Comment by mlunoe** [comment] 2015-01-21 17:07
This should not be critical. Maybe we could push it to another RC

**Comment by sttts** [comment] 2015-01-21 17:17
there is also a life after the 0.8.0. This is only cosmetics.

**Comment by mlunoe** [comment] 2015-01-21 17:18
:)

**Comment by pierlo-upitup** [comment] 2015-07-13 14:43
Can't reproduce. Probably fixed in 0.10 Flux refactoring?

![out](https://cloud.githubusercontent.com/assets/1078545/8652289/29a587fc-297e-11e5-8eec-029064622544.gif)

**Comment by pierlo-upitup** [comment] 2015-07-22 10:06
Closing this issue (can't reproduce).

**Closed by pierlo-upitup** 2015-07-22 10:06 UTC
Labels: bug, gui, OKR Usability, question
