### ISSUE TITLE
Marathon Should Automatically Stop Re-Deploying the App if there is a error in Docker Image Name

### ISSUE THREAD

**Issue by raghu999** [mesosphere/marathon#3985] opened 2016-06-15 22:30 UTC
Hello Mesosphere Team,
      Really Appreciate Your work on Mesosphere. We noticed that while deploying an app in Marathon if there is an error in Container settings like Image name Marathon will try to redeploy the app Continuously is there a way we can make Marathon to stop Redeploying and Error-Out.

**Comment by jasongilanfarr** [comment] 2016-06-16 09:34
Duplicate of #3954

**Closed by jasongilanfarr** 2016-06-16 09:34 UTC

**Comment by kamilchm** [comment] 2016-06-24 10:57
I don't know why the STOP button should be considered harmful as it was stated in https://github.com/mesosphere/marathon-ui/pull/739?
I work with many new Marathon users and they don't know what to do when their app fails with new version. They want to stop any actions to make app in the known state and work it out themselves because they know what to do better than Marathon in cases where simple restarting wont help.

**Comment by meichstedt** [comment] 2016-06-30 14:22
@kamilchm Consider a deployment that affects a group with several apps (A, B, C). If you try to change the configuration of one of the affected apps (e.g. app B), it will fail because there's _a deployment_ in progress. If you choose to force-stop that deployment, deploying new versions for apps A, B and C will be stopped, leaving the cluster in an unclear state. (e.g. no instance for A because all have been killed but none started yet, 2 old and 1 new instances for C).

Since it is not obvious what will be affected by stopping the deployment, we chose to remove that option.

**Comment by kamilchm** [comment] 2016-06-30 15:08
> no instance for A because all have been killed but none started yet

When you use rolling upgrade with health checks you wont affect you service then and leave all old instances untouched. This is the difference between force-stop and rollback. Rollback will kill your old instances and try to bring it back even when they are ok after failed deployment. Although we can treat it as a bug in rollback functionality and make sure that rollback wont kill tasks that have are no different between the version that we are trying to rollback to and could be done in https://github.com/mesosphere/marathon/issues/4046.
