### ISSUE TITLE
Add more inline task information

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2972] opened 2016-01-13 11:20 UTC
This is how task list looked like in 0.10:

![image](https://cloud.githubusercontent.com/assets/89186/12292725/0b3111e8-b9e7-11e5-92e6-1e19f2325067.png)

This is how it looks like now in 0.14:

![image](https://cloud.githubusercontent.com/assets/89186/12292741/20e63a40-b9e7-11e5-9b49-e94f0bdedac1.png)

Before 0.14 I could go to task in 1 click, now I have to make 2. If I run specific tasks that are pinned to machines, I cannot quickly figure out what of 10 machines is out. While it's not marathon's job to tell me such things (alerting is there to notify me), it could make it more convenient.

In fact, I'd like to have the following info inlined:

* host + all ports (like before)
* machine attributes (ex: `lb:true`, `rack:123`)
* link to mesos sandbox

**Comment by philipnrmn** [comment] 2016-01-13 13:43
Thanks for the feedback @bobrik!

@leemunroe let's re-evaluate this decision.

**Comment by aldipower** [comment] 2016-01-13 13:49
That was definitely a regression.

**Comment by pierlo-upitup** [comment] 2016-01-13 14:49
This was introduced in https://github.com/mesosphere/marathon/issues/2776

**Comment by philipnrmn** [comment] 2016-01-13 15:38
Moving this out of v0.14.0 as it's really a feature request/discussion for the backlog.

**Comment by abraithwaite** [comment] 2016-01-13 17:17
FWIW, I think this would be very useful as well.  I can't find the other ticket ATM, but I think it goes pretty nicely along with collapsable application hierarchies (instead of opening a new page each time) since it provides the most flexibility and the densest information.

Anything that can help me debug my deployment more quickly is a boon to my workflow.

**Comment by leemunroe** [comment] 2016-01-14 00:14
+1. I can't remember why we removed them.

@bobrik Thanks for feedback. You mentioned you'd also like an inline link to mesos sandbox. For what reason? I ask as we're [looking at a solution](https://invis.io/KG5JYBUZ5) to bring logs into the Marathon UI and wondering if that solves your use case or not.

**Comment by bobrik** [comment] 2016-01-14 00:41
Sandbox is not just about logs, although they are the most important thing. I like the proposal, but this would require mesos (masters and slaves) and marathon to work over the same protocol (be that HTTP or HTTPS) for user. This is not always possible. Slaves usually live in the private trusted network that users don't have access to. Often slaves are HTTP, but Marathon is HTTPS.

The obvious solution is to make it work on the same protocol. Another solution would be to proxy logs through Marathon to avoid the need to expose mesos endpoints to users.

Another thing I just remembered: people often interested not in sandbox, but in the page one level up, where executor stats live and you can see actual resource usage. This link could be better than sanbox. Actual resource usage can be shown in Marathon UI to minimize the need to go to Mesos UI. That'd be great, but has the same drawbacks as logs from the sandbox.

Hope this helps.

**Comment by pierlo-upitup** [comment] 2016-01-14 07:53
Thanks a lot for your feedback, @bobrik . I also would love to see Marathon proxying Mesos logs, as it would solve a lot of edge cases as you mentioned.

**Comment by pierlo-upitup** [comment] 2016-01-14 07:55
cc @gkleiman

**Comment by kamilchm** [comment] 2016-01-14 08:33
:+1: for host and ports information

**Closed** 2016-01-14 13:27 UTC
Labels: gui, in progress

**Comment by bobrik** [comment] 2016-01-14 13:31
Do we want to have a separate issue for sandbox / executor page links to mesos ui and host attributes, since this one is closed?
