### ISSUE TITLE
Are we leader?

### ISSUE THREAD

**Issue by Spritekin** [mesosphere/marathon#3866] opened 2016-05-06 00:32 UTC
Hi,

I'm running Marathon 1.1.1 on Mesos 0.28.0. I have 3 master nodes. 

Today I got this message in one node:

```
May 06 10:15:55 ip-172-31-33-40.aws.cmcrc.com docker[1170]: [2016-05-06 00:15:55,694] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.33.40:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp215638041-567)
May 06 10:15:55 ip-172-31-33-40.aws.cmcrc.com docker[1170]: [2016-05-06 00:15:55,946] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.33.40:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp215638041-567)
May 06 10:15:56 ip-172-31-33-40.aws.cmcrc.com docker[1170]: [2016-05-06 00:15:56,200] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.33.40:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp215638041-567)
May 06 10:15:56 ip-172-31-33-40.aws.cmcrc.com docker[1170]: [2016-05-06 00:15:56,452] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.33.40:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp215638041-567)
May 06 10:15:56 ip-172-31-33-40.aws.cmcrc.com docker[1170]: [2016-05-06 00:15:56,703] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.33.40:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp215638041-567)
May 06 10:15:56 ip-172-31-33-40.aws.cmcrc.com docker[1170]: [2016-05-06 00:15:56,955] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.33.40:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp215638041-567)
```

Looks like the marathon leadership can't be reliably stablished. The other two marathon services were pointing to this server as the marathon leader, however this leader was unable to define its leadership.

I just restarted the 3 marathon services and all was ok, they agreed on a leader (the same node above) and all was ok.

Not sure what happened here.

Luck!
Guimo

**Comment by Spritekin** [comment] 2016-05-06 00:37
FYI, before I started the nodes, looks like mesos got tired of waiting and kicked marathon out of the framework list. However the registered IP for the marathon framework before being kicked out was not the one above but one of the other leaders (which was the marathon leader previously but no longer).

After the restart, when the new node got leadership it was correctly registered.

Not sure if this helps.

**Comment by gkleiman** [comment] 2016-05-11 10:15
Looks like a dupe of #3866 which was fixed in v1.1.1.

**Comment by searover** [comment] 2016-05-24 02:37
I have the same problem, but when I start marathon, the console log shows "MESOS_NATIVE_JAVA_LIBRARY is not set. Searching in /usr/lib /usr/local/lib.", then I realized that I've pass the --prefix=/usr/local/mesos option when configure the mesos source code,so the libmesos.so cannot be found in marathon.
So I set the environment value MESOS_NATIVE_JAVA_LIBRARY to the right path(the location of libmesos.so), then it works well.

**Comment by Spritekin** [comment] 2016-05-25 04:07
@gkleiman 
This ticket is a duplicate of this ticket? :)
I run from the docker image 1.1.1 which is the version you mention should be fixed.
I think this ticket shouldn't be closed.

**Comment by Spritekin** [comment] 2016-05-27 00:15
It happened again. The mesos leadership changed and marathon is again unable to claim leaderhsip. The assigned leader keeps asking if he is leader.
```
May 27 10:11:22 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:22,851] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
May 27 10:11:23 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:23,103] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
May 27 10:11:23 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:23,355] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
May 27 10:11:23 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:23,607] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
May 27 10:11:23 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:23,859] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
May 27 10:11:24 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:24,111] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
May 27 10:11:24 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:24,362] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
May 27 10:11:24 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:24,614] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
May 27 10:11:24 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:24,866] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
May 27 10:11:25 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:25,118] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
May 27 10:11:25 ip-172-31-35-90.aws.cmcrc.com docker[3114]: [2016-05-27 00:11:25,370] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(172.31.35.90:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp1074976188-48)
```

**Comment by krestjaninoff** [comment] 2016-06-28 17:26
I have the same problem running 1.1.1:

```
Jun 28 10:41:21 ip-10-1-4-231 marathon[25194]: [2016-06-28 10:41:21,434] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(10.1.4.231:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp650679
Jun 28 10:41:21 ip-10-1-4-231 marathon[25194]: [2016-06-28 10:41:21,437] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(10.1.4.231:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp650679
Jun 28 10:41:21 ip-10-1-4-231 marathon[25194]: [2016-06-28 10:41:21,458] INFO Do not proxy to myself. Waiting for consistent leadership state. Are we leader?: false, leader: Some(10.1.4.231:8080) (mesosphere.marathon.api.Lead
Jun 28 10:41:21 ip-10-1-4-231 marathon[25194]: [2016-06-28 10:41:21,460] INFO Waiting for consistent leadership state. Are we leader?: false, leader: Some(10.1.4.231:8080) (mesosphere.marathon.api.LeaderProxyFilter$:qtp650679
```

Stopping all (3) the marathon instances and starting them one by one solves the problem.

**Comment by gkleiman** [comment] 2016-07-04 10:56
This should hopefully be fixed by 2a1bbe4.

**Comment by Spritekin** [comment] 2016-07-07 02:25
Awesome... waiting for 1.2 then!

**Comment by kopax** [comment] 2016-07-18 10:20
same bug here

**Comment by jasongilanfarr** [comment] 2016-11-23 17:16
Please reopen if this is still a problem on 1.3

**Closed by jasongilanfarr** 2016-11-23 17:16 UTC
Labels: bug, Hacktoberfest, OKR Scalability, OKR Stability, scaling, service
