### ISSUE TITLE
Affected apps of an deployment in the UI is empty

### ISSUE THREAD

**Issue by sttts** [mesosphere/marathon#987] opened 2015-01-13 14:39 UTC

**Comment by mlunoe** [comment] 2015-01-13 18:00
Yes, I noticed that the API has changed, when working with it. I will create a fix for review.

**Comment by drexin** [comment] 2015-01-13 18:23
What exactly changed? We may have to fix the API instead.

**Comment by mlunoe** [comment] 2015-01-13 19:11
Here are the changes committed:
https://github.com/mesosphere/marathon/commit/dc77d96855a314ca44eff4e4212d1a3f3ef11b46
https://github.com/mesosphere/marathon/commit/31246a58baa88330703f232ea5081bada2f3ea4d

It should probably also have been changed here, with that commit, but yeah I'm not sure why this change to API was added:
https://github.com/mesosphere/marathon/blob/master/src/main/resources/assets/js/components/DeploymentComponent.jsx#L50
https://github.com/mesosphere/marathon/blob/master/src/main/resources/assets/js/components/DeploymentComponent.jsx#L57

**Comment by drexin** [comment] 2015-01-13 19:35
Okay, seems like a valid change with some forgotten ones ;-).

**Comment by bobrik** [comment] 2015-01-15 16:32
I built master from a9bccfa6f619984eed4145f22f1960e8cb78ec3f and affected apps are still missing. See #1018.

**Comment by ConnorDoyle** [comment] 2015-01-20 20:06
@mlunoe could you please look into this one?  It's been reproduced since the PR that was supposed to fix it.

**Comment by mlunoe** [comment] 2015-01-21 06:45
Did you make sure to rebuild the frontend? I can only reproduce this if the frontend is not rebuild.
Here's a guide to build the frontend: https://github.com/mesosphere/marathon/tree/master/src/main/resources/assets

**Comment by bobrik** [comment] 2015-01-21 08:53
@mlunoe I used `Dockerfile` to build an image if that helps.

**Comment by drexin** [comment] 2015-01-21 10:06
@mlunoe You're right. We really should integrate that step into the sbt build.

**Closed by drexin** 2015-01-21 10:06 UTC
