### ISSUE TITLE
Unannounced UI Change - Intentional?  

### ISSUE THREAD

**Issue by JohnOmernik** [mesosphere/marathon#3178] opened 2016-02-06 18:25 UTC
I was wondering if there was conscious decision a specific UI change between the version. Basically when I click an App in 0.13, it shows all the instances running with a "darker" grey right below the instance representation of which node it's running on .

In 0.14 this has gone away, it's cleaner, I will give it that, however I find I it's really annoying and I am missing it... here's why. 

When I am doing updates/changes to my cluster, I may have a situation where I am running 6 of an app, on 6 nodes.  Now, I want to kill and scale to 5 nodes, a nice feature. When I don't have the nodes, on the initial app landing page, now I have to click on the instance, and validate the node, memorize the instance ID, then find it, check the box and kill and scale. 

This seems like a minor thing, but say I have 25 nodes, and want to kill and scale 5 of them, there is a lot of manually back and forth to figure out which 5 I want to kill and scale. 

I am curious on the thought process here, and if I could make a request: Please put the nodename/port on the initial app landing page (per instance) or make it a setting that a user can save to display or not display.

**Comment by pierlo-upitup** [comment] 2016-02-09 09:39
@WalterDalton thanks for reporting this. 

Could you please type `g v` after loading Marathon UI and report what version you are running? 
If I understand correctly, what you are describing here should be a duplicate of https://github.com/mesosphere/marathon/issues/2972  which was fixed in https://github.com/mesosphere/marathon-ui/pull/549 and shipped with Marathon UI version `0.14.2`. Thanks!

**Comment by pierlo-upitup** [comment] 2016-04-18 14:05
Closing the issue for lack of response – please reopen if necessary.

**Closed by pierlo-upitup** 2016-04-18 14:05 UTC
Labels: analyze, design, gui
