### ISSUE TITLE
HDFS doesn't complete Deployment on Testing Branch

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2290] opened 2015-09-21 16:24 UTC
The HDFS framework doesn't complete deployment according to Marathon on testing/continuous clusters.

The Framework is healthy from it's perspective.  It launches all needed Tasks.  It responds to all health check requests appropriately.  It responds to client requests as designed etc.

This defect makes it impossible for us to programmatically determine the health of an HDFS deployment.

https://mesosphere.atlassian.net/browse/MARATHON-317

**Comment by kolloch** [comment] 2015-09-22 11:14
@gabrielhartmann  I just created a DCOS cluster and started HDFS with `dcos package install hdfs`. I saw this in the error log which doesn't look healthy at all:

```
15/09/22 10:56:51 WARN hdfs.DFSClient: DataStreamer Exception
org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /hdfs-framework-healthcheck/test1.txt._COPYING_ could only be replicated to 0 nodes instead of minReplication (=1).  There are 0 datanode(s) running and no node(s) are excluded in this operation.
	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget(BlockManager.java:1504)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3065)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:615)
	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.addBlock(AuthorizationProviderProxyClientProtocol.java:188)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:476)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:587)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1026)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2013)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2009)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Unknown Source)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1642)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2007)

	at org.apache.hadoop.ipc.Client.call(Client.java:1411)
	at org.apache.hadoop.ipc.Client.call(Client.java:1364)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
	at com.sun.proxy.$Proxy9.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:391)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy10.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1473)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1290)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:536)
put: File /hdfs-framework-healthcheck/test1.txt._COPYING_ could only be replicated to 0 nodes instead of minReplication (=1).  There are 0 datanode(s) running and no node(s) are excluded in this operation.
I0922 10:56:51.865679  1272 main.cpp:100] Ignoring failure as health check still in grace period
```

Furthermore, in the slave logs I found the following:

```
I0922 11:01:48.026366  1099 slave.cpp:2696] Handling status update TASK_RUNNING (UUID: 59f65583-165d-43c2-bd81-32b519898ec9) for task hdfs.12d7cd56-6118-11e5-95c5-421f79ce4c65 in health state unhealthy of framework 20150922-104356-3892576266-5050-1219-0000 from executor(1)@10.0.1.188:35511
I0922 11:01:48.026757  1097 status_update_manager.cpp:322] Received status update TASK_RUNNING (UUID: 59f65583-165d-43c2-bd81-32b519898ec9) for task hdfs.12d7cd56-6118-11e5-95c5-421f79ce4c65 in health state unhealthy of framework 20150922-104356-3892576266-5050-1219-0000
I0922 11:01:48.026805  1097 status_update_manager.cpp:826] Checkpointing UPDATE for status update TASK_RUNNING (UUID: 59f65583-165d-43c2-bd81-32b519898ec9) for task hdfs.12d7cd56-6118-11e5-95c5-421f79ce4c65 in health state unhealthy of framework 20150922-104356-3892576266-5050-1219-0000
I0922 11:01:48.028033  1099 slave.cpp:2975] Forwarding the update TASK_RUNNING (UUID: 59f65583-165d-43c2-bd81-32b519898ec9) for task hdfs.12d7cd56-6118-11e5-95c5-421f79ce4c65 in health state unhealthy of framework 20150922-104356-3892576266-5050-1219-0000 to master@10.0.4.232:5050
I0922 11:01:48.028142  1099 slave.cpp:2905] Sending acknowledgement for status update TASK_RUNNING (UUID: 59f65583-165d-43c2-bd81-32b519898ec9) for task hdfs.12d7cd56-6118-11e5-95c5-421f79ce4c65 in health state unhealthy of framework 20150922-104356-3892576266-5050-1219-0000 to executor(1)@10.0.1.188:35511
I0922 11:01:48.031659  1095 status_update_manager.cpp:394] Received status update acknowledgement (UUID: 59f65583-165d-43c2-bd81-32b519898ec9) for task hdfs.12d7cd56-6118-11e5-95c5-421f79ce4c65 of framework 20150922-104356-3892576266-5050-1219-0000
I0922 11:01:48.031724  1095 status_update_manager.cpp:826] Checkpointing ACK for status update TASK_RUNNING (UUID: 59f65583-165d-43c2-bd81-32b519898ec9) for task hdfs.12d7cd56-6118-11e5-95c5-421f79ce4c65 in health state unhealthy of framework 20150922-104356-3892576266-5050-1219-0000
I0922 11:01:48.125778  1095 slave.cpp:2696] Handling status update TASK_KILLED (UUID: d1c354e1-5826-4dbd-971b-58bac23ad618) for task hdfs.12d7cd56-6118-11e5-95c5-421f79ce4c65 in health state unhealthy of framework 20150922-104356-3892576266-5050-1219-0000 from executor(1)@10.0.1.188:35511
```

Therefore Mesos considers the task as unhealthy. If Mesos considers the task unhealthy, Marathon will as well. So please investigate why Mesos considers the task unhealthy.

If that's not the case in your setup, please provide all relevant logs to debug the problem:

* Marathon
* Mesos Master
* The relevant slave
* HDFS stderr/stdout
* state.json

On a side note, I also so this which should probably optimized:

```
15/09/22 10:58:00 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
```

**Comment by gabrielhartmann** [comment] 2015-09-22 14:47
All those error messages you provide are expected and have always occurred, except for those in the Slave logs.  Furthermore, HDFS deployed flawlessly on Stable clusters, and is only now encountering the situation where it is constantly listed as Deploying by Marathon.  Prior to the the new 0.10.1 release HDFS worked well.  Post that release it doesn't work well.  This doesn't have the hallmarks of an HDFS problem.  Let me reiterate, that HDFS is working properly and I have observed no failed tasks.

I have provided a repro so I won't be spending a great deal of time collecting a lot of logs.  Deploying HDFS on any cluster is sufficient now (as stable has been upgraded to 0.10.1).  I'm deploying a repro now and will leave the cluster up for 24 hours and leave the address here.

**Comment by gabrielhartmann** [comment] 2015-09-22 16:42
We had a face-to-face call.  I'll re-file an issue when I get a repro today with the more detailed information you need.

**Comment by gabrielhartmann** [comment] 2015-09-22 18:09
Here is [a live cluster with the repro](http://dcos-fram-elasticl-16trb6nukb0l-281043533.us-west-2.elb.amazonaws.com/mesos/#/).  I was wrong previously.  The HDFS scheduler is not __continuously__ passing it's healthcheck, but the last thing it did was to pass it's healthcheck.  We can see this in the scheduler (hdfs task) stderr log.  [Marathon notes that HDFS is still deploying](http://dcos-fram-elasticl-16trb6nukb0l-281043533.us-west-2.elb.amazonaws.com/service/marathon/#/deployments).

In the past I have tried stopping the deployment and then reinstalling (restarting the scheduler essentially) and this sometimes solves the issue and sometimes doesn't.  I can also just restart the scheduler and this never resolves the problem, but the Scheduler will begin passing the healtcheck __continuously__.

The expected output for the healthcheck is:
```
15/09/22 17:06:49 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/09/22 17:06:51 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
15/09/22 17:06:53 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/09/22 17:06:55 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
15/09/22 17:06:57 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/09/22 17:07:00 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
15/09/22 17:07:02 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/09/22 17:07:04 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
15/09/22 17:07:06 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
W0922 17:07:07.336280  1341 main.cpp:375] Health check failed Command check failed with reason: status still pending after timeout 1mins
15/09/22 17:07:08 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
15/09/22 17:07:08 INFO fs.TrashPolicyDefault: Namenode trash configuration: Deletion interval = 0 minutes, Emptier interval = 0 minutes.
Deleted hdfs://hdfs/hdfs-framework-healthcheck
```
Sorry it's so ugly.  We'll be working on improving logging.  The cluster is set to expire in 5 days, which can be extended.  Please let me know if you need any additional information.  Please note that HDFS is operational now.  It will successfully respond to client queries, and has passed it's healthcheck, although this is no longer being run.

**Comment by kolloch** [comment] 2015-09-23 09:16
Just quick feedback @gabrielhartmann, I will continue my investigation. I was not able to retrieve the marathon logs or the slave logs of the relevant time interval. Either because of my lack of journalctl knowledge or because those logs have been rotated away. I am now trying to reproduce the problem by restarting the hdfs service. "Unfortunately", after restarting the service so far always starts up correctly. (I do a "stop" on the deployment in the UI and then "restart" the app in the UI)

Generally, you are seriously helping me a lot if you save the logs when the problem appears.

**Comment by kolloch** [comment] 2015-09-23 09:32
It would be great if you had saved the logs as described above when you reproduce the bug. Please let's do that in the future.

I could not reproduce the problem by restarting the hdfs service for several times. I did most of the restarts while having the spark app suspended (to keep the logs focussed) but just to check that the problem doesn't result from interference with spark, I started spark again and repeated some restarts of the hdfs service after that. That allowed me to reproduce the error, finally.

I will continue my investigation.

**Comment by kolloch** [comment] 2015-09-23 10:15
Unfortunately, hdfs just took a while until becoming healthy. When Mesos reported healthy status, the old task was stopped and the deployment stopped (excerpt from the Marathon log):

```
Sep 23 09:25:51 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [2015-09-23 09:25:51,179] INFO Received status update for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5: TASK_RUNNING () (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$4feea61a:100)
Sep 23 09:26:50 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [2015-09-23 09:26:50,741] INFO Received status update for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5: TASK_RUNNING (Reconciliation: Latest task state) (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$4feea61a:100)
Sep 23 09:26:50 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [2015-09-23 09:26:50,745] INFO Received status update for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5: TASK_RUNNING (Reconciliation: Latest task state) (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$4feea61a:100)
Sep 23 09:31:14 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [2015-09-23 09:31:14,277] INFO Received status update for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5: TASK_RUNNING () (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$4feea61a:100)
Sep 23 09:31:14 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [2015-09-23 09:31:14,278] INFO Received status for [hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5] with version [2015-09-23T09:25:35.547Z] and healthy [true] (mesosphere.marathon.health.MarathonHealthCheckManager$$EnhancerByGuice$$60c84ed1:165)
Sep 23 09:31:14 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [2015-09-23 09:31:14,279] INFO Forwarding health result [Healthy(hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5,2015-09-23T09:25:35.547Z,2015-09-23T09:31:14.278Z)] to health check actor [Actor[akka://marathon/user/$ab#874294670]] (mesosphere.marathon.health.MarathonHealthCheckManager$$EnhancerByGuice$$60c84ed1:186)
Sep 23 09:31:14 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [INFO] [09/23/2015 09:31:14.279] [marathon-akka.actor.default-dispatcher-16] [akka://marathon/user/$ab] Received health result: [Healthy(hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5,2015-09-23T09:25:35.547Z,2015-09-23T09:31:14.278Z)]
Sep 23 09:31:14 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [INFO] [09/23/2015 09:31:14.279] [marathon-akka.actor.default-dispatcher-12] [akka://marathon/user/MarathonScheduler/$a/DeploymentManager/8823c0e4-3040-4bcb-b7fb-86defbdcc0d0/$a] Killing old task hdfs.ddadbd6c-61d4-11e5-84a9-1a46da8345c5 because hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 became reachable
Sep 23 09:31:14 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [INFO] [09/23/2015 09:31:14.279] [marathon-akka.actor.default-dispatcher-12] [akka://marathon/user/MarathonScheduler/$a/DeploymentManager/8823c0e4-3040-4bcb-b7fb-86defbdcc0d0/$a] All tasks for /hdfs are healthy
Sep 23 09:31:14 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [INFO] [09/23/2015 09:31:14.279] [marathon-akka.actor.default-dispatcher-19] [akka://marathon/user/MarathonScheduler/$a] Deployment of / successful
Sep 23 09:31:14 ip-10-0-6-210.us-west-2.compute.internal java[1352]: [INFO] [09/23/2015 09:31:14.279] [marathon-akka.actor.default-dispatcher-12] [akka://marathon/user/MarathonScheduler/$a/DeploymentManager] Removing 8823c0e4-3040-4bcb-b7fb-86defbdcc0d0 from list of running deployments
```

And the matching excerpt from the slave.log:

```
I0923 09:25:38.948685  1086 slave.cpp:1249] Got assigned task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 for framework 20150922-165631-3523608586-5050-1307-0000
I0923 09:25:38.949239  1086 slave.cpp:1365] Launching task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 for framework 20150922-165631-3523608586-5050-1307-0000
I0923 09:25:38.956179  1086 slave.cpp:4799] Launching executor hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 of framework 20150922-165631-3523608586-5050-1307-0000 with resources cpus(*):0.1; mem(*):32 in work directory '/var/lib/mesos/slave/slaves/20150922-165631-3523608586-5050-1307-S5/frameworks/20150922-165631-3523608586-5050-1307-0000/executors/hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5/runs/3ea99853-19a3-4fea-ac96-4c335f5a70e1'
I0923 09:25:38.956701  1086 slave.cpp:1583] Queuing task 'hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5' for executor hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 of framework '20150922-165631-3523608586-5050-1307-0000
I0923 09:25:38.957082  1086 containerizer.cpp:633] Starting container '3ea99853-19a3-4fea-ac96-4c335f5a70e1' for executor 'hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5' of framework '20150922-165631-3523608586-5050-1307-0000'
I0923 09:25:38.966505  1088 containerizer.cpp:855] Checkpointing executor's forked pid 2519 to '/var/lib/mesos/slave/meta/slaves/20150922-165631-3523608586-5050-1307-S5/frameworks/20150922-165631-3523608586-5050-1307-0000/executors/hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5/runs/3ea99853-19a3-4fea-ac96-4c335f5a70e1/pids/forked.pid'
I0923 09:25:51.171690  1088 slave.cpp:2358] Got registration for executor 'hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5' of framework 20150922-165631-3523608586-5050-1307-0000 from executor(1)@10.0.2.171:50363
I0923 09:25:51.173938  1088 slave.cpp:1739] Sending queued task 'hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5' to executor 'hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5' of framework 20150922-165631-3523608586-5050-1307-0000
I0923 09:25:51.176723  1086 slave.cpp:2696] Handling status update TASK_RUNNING (UUID: 6a0b387a-3ab4-4e7e-8471-7820d257d63e) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 of framework 20150922-165631-3523608586-5050-1307-0000 from executor(1)@10.0.2.171:50363
I0923 09:25:51.176925  1086 status_update_manager.cpp:322] Received status update TASK_RUNNING (UUID: 6a0b387a-3ab4-4e7e-8471-7820d257d63e) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 of framework 20150922-165631-3523608586-5050-1307-0000
I0923 09:25:51.177189  1086 status_update_manager.cpp:826] Checkpointing UPDATE for status update TASK_RUNNING (UUID: 6a0b387a-3ab4-4e7e-8471-7820d257d63e) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 of framework 20150922-165631-3523608586-5050-1307-0000
I0923 09:25:51.180034  1085 slave.cpp:2975] Forwarding the update TASK_RUNNING (UUID: 6a0b387a-3ab4-4e7e-8471-7820d257d63e) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 of framework 20150922-165631-3523608586-5050-1307-0000 to master@10.0.6.210:5050
I0923 09:25:51.180198  1085 slave.cpp:2905] Sending acknowledgement for status update TASK_RUNNING (UUID: 6a0b387a-3ab4-4e7e-8471-7820d257d63e) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 of framework 20150922-165631-3523608586-5050-1307-0000 to executor(1)@10.0.2.171:50363
I0923 09:25:51.183645  1086 status_update_manager.cpp:394] Received status update acknowledgement (UUID: 6a0b387a-3ab4-4e7e-8471-7820d257d63e) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 of framework 20150922-165631-3523608586-5050-1307-0000
I0923 09:25:51.183753  1086 status_update_manager.cpp:826] Checkpointing ACK for status update TASK_RUNNING (UUID: 6a0b387a-3ab4-4e7e-8471-7820d257d63e) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 of framework 20150922-165631-3523608586-5050-1307-0000
I0923 09:31:14.271569  1085 slave.cpp:2696] Handling status update TASK_RUNNING (UUID: a6c8b038-a677-4c3d-b2cd-5229e86931ab) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 in health state healthy of framework 20150922-165631-3523608586-5050-1307-0000 from executor(1)@10.0.2.171:50363
I0923 09:31:14.271834  1085 status_update_manager.cpp:322] Received status update TASK_RUNNING (UUID: a6c8b038-a677-4c3d-b2cd-5229e86931ab) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 in health state healthy of framework 20150922-165631-3523608586-5050-1307-0000
I0923 09:31:14.274528  1085 status_update_manager.cpp:826] Checkpointing UPDATE for status update TASK_RUNNING (UUID: a6c8b038-a677-4c3d-b2cd-5229e86931ab) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 in health state healthy of framework 20150922-165631-3523608586-5050-1307-0000
I0923 09:31:14.277241  1089 slave.cpp:2975] Forwarding the update TASK_RUNNING (UUID: a6c8b038-a677-4c3d-b2cd-5229e86931ab) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 in health state healthy of framework 20150922-165631-3523608586-5050-1307-0000 to master@10.0.6.210:5050
I0923 09:31:14.277700  1089 slave.cpp:2905] Sending acknowledgement for status update TASK_RUNNING (UUID: a6c8b038-a677-4c3d-b2cd-5229e86931ab) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 in health state healthy of framework 20150922-165631-3523608586-5050-1307-0000 to executor(1)@10.0.2.171:50363
I0923 09:31:14.283279  1085 status_update_manager.cpp:394] Received status update acknowledgement (UUID: a6c8b038-a677-4c3d-b2cd-5229e86931ab) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 of framework 20150922-165631-3523608586-5050-1307-0000
I0923 09:31:14.283396  1085 status_update_manager.cpp:826] Checkpointing ACK for status update TASK_RUNNING (UUID: a6c8b038-a677-4c3d-b2cd-5229e86931ab) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 in health state healthy of framework 20150922-165631-3523608586-5050-1307-0000
```

**Comment by kolloch** [comment] 2015-09-23 10:17
If you manage to reproduce the problem, please save the logs. I'll have to close this until then.

**Comment by gabrielhartmann** [comment] 2015-09-23 22:43
Here are the [logs for the Agent hosting the HDFS scheduler](https://gist.github.com/gabrielhartmann/68b1355efecae5e3a9ec).
Here are the [stderr logs for from the scheduler itself](https://gist.github.com/gabrielhartmann/19042e87b98575fa59df).

Note that the stack traces etc. at the end of the scheduler logs are the health-check failing because HDFS hadn't recovered yet.  That's just spew from running hadoop commands.  [The health check is this](https://gist.github.com/gabrielhartmann/393d6473157f0cb759b9).

[The cluster](http://dcos-fram-elasticl-19mg5o52x7eq4-1356402263.us-west-2.elb.amazonaws.com/mesos) should be stuck in this state forever.  I've extended its lifespan for 5 days again.  In this case we're not stuck in a "Deploying" state.  We're just stuck in an indeterminate health state.  We never converge to Healthy or Unhealthy.  Note that the whole healthcheck failure took 45 seconds.  Our intervalSeconds is 60, and our timeoutSeconds is 60.  gracePeriodSeconds is 300 and maxConsecutiveFailures is 3.

I don't know how to get Marathon logs.  Let me know if they're lost by the time you get around to this.

**Comment by kolloch** [comment] 2015-09-24 08:24
Your theory is that mesos detects that the task is healthy and Marathon does not react appropriately, correct?

Then there should be something like 

```
I0923 09:31:14.277241  1089 slave.cpp:2975] Forwarding the update TASK_RUNNING (UUID: a6c8b038-a677-4c3d-b2cd-5229e86931ab) for task hdfs.0da34453-61d5-11e5-84a9-1a46da8345c5 in health state healthy of framework 20150922-165631-3523608586-5050-1307-0000 to master@10.0.6.210:5050
```

in the slave log. But I am not seeing that. I get the only the following:

```shell
$ grep "Forwarding" slave.log | grep "hdfs."
```
```
Sep 23 22:09:47 ip-10-0-1-109.us-west-2.compute.internal mesos-slave[813]: I0923 22:09:47.318738   825 slave.cpp:2975] Forwarding the update TASK_RUNNING (UUID: 1135b032-2bf0-4055-941e-127cfbbb8ef7) for task hdfs.c5013396-623f-11e5-baf1-920390a3dcf7 of framework 20150923-213844-1862729738-5050-1392-0000 to master@10.0.7.111:5050
```

So Marathon gets the initial TASK_RUNNING notification but nothing else. I guess that mesos should either follow up with a TASK_RUNNING with healthy state or an unhealthy state.

So if I am not missing something and that is entirely possible, it looks like a Mesos bug. Or maybe the log is incomplete?

**Comment by tillt** [comment] 2015-09-24 14:09
Seems we run into two issues here:

1. Why does the health-check run into a timeout
-> the current health-check script seems rather slow in execution - I timed a couple of attempts and it always took more than 24 seconds to run it entirely. As such the timeout of 60 seconds appears to be too optimistic for a machine with a higher workload. Seems you got at least two options here; A. adapt the health-check, maybe by putting it entirely into a single JAVA code invocation. B. raise the timeout to e.g. 2 or more minutes.

```
export PATH=$MESOS_DIRECTORY/hdfs-mesos-0.1.4/bin:$PATH && export JAVA_HOME=$MESOS_DIRECTORY/jre1.7.0_76 && hadoop fs -ls hdfs://hdfs/ && rm -rf hdfs-framework-healthcheck && hadoop fs -rm -r -f hdfs://hdfs/hdfs-framework-healthcheck && hadoop fs -mkdir hdfs://hdfs/hdfs-framework-healthcheck && mkdir hdfs-framework-healthcheck && echo "this is a test" > hdfs-framework-healthcheck/test1.txt && hadoop fs -put hdfs-framework-healthcheck/test1.txt hdfs://hdfs/hdfs-framework-healthcheck && hadoop fs -get hdfs://hdfs/hdfs-framework-healthcheck/test1.txt hdfs-framework-healthcheck/test2.txt && rm -rf hdfs-framework-healthcheck && hadoop fs -rm -r -f hdfs://hdfs/hdfs-framework-healthcheck
```


2. Why does the health-check not send any updates after it ran into a timeout
-> covered by https://issues.apache.org/jira/browse/MESOS-3479

**Comment by gabrielhartmann** [comment] 2015-09-24 14:12
@kolloch:  Thanks for having a look again Peter.  I'll be moving this investigation to the Mesos team.  Hopefully this bug doesn't live in some no-man's land between Marathon and Mesos.  I have a feeling there are at least two bugs here, or that the same bug manifests in different ways.

@tillt:  I can bump the timeout again, but as you can see from the timestamps in this case, execution fell well within the 60 second period.  So I'm not sure the referenced Mesos bug has anything to do with this particular failure.  Although it might be a different manifestation.  I'm not worried about production loaded systems at the moment.  The tests I'm running fall very often and they're run on totally pristine unloaded systems.

**Comment by gabrielhartmann** [comment] 2015-09-30 22:55
Apologies for opening this again.  I had a pretty close look from someone from the Core team.  It looks to us like this may be a Marathon issue.  Here is what we found:

1. [The HDFS Scheduler comes up and immediately launches a health-check at about 19:02:52](https://gist.github.com/gabrielhartmann/3d0882d67a8f2d0c3d9c#file-hdfs-stdout-L5-L6)
2. [This fails pretty much immediately here](I0930 19:02:52.870311  1461 main.cpp:100] Ignoring failure as health check still in grace period)
3. It then fails 2 more times [here](https://gist.github.com/gabrielhartmann/c7db0f2fe5b63356b5db#file-gistfile1-txt-L69) and [here](https://gist.github.com/gabrielhartmann/c7db0f2fe5b63356b5db#file-gistfile1-txt-L75) separated at approximately 60s intervals as specified by intervalSeconds in the marathon.json.
4. It is attempted again [here](https://gist.github.com/gabrielhartmann/c7db0f2fe5b63356b5db#file-gistfile1-txt-L76) again pretty much exactly 60s later.  This time it's going to fail with stack traces spewing into stderr.  It has completed failed by [here](https://gist.github.com/gabrielhartmann/c7db0f2fe5b63356b5db#file-gistfile1-txt-L322).  Note that the duration of the attempt / failure is ~40s here.  Well within the 60s timeout.
5. The health check is attempted one more time and succeeds [here](https://gist.github.com/gabrielhartmann/c7db0f2fe5b63356b5db#file-gistfile1-txt-L323-L335).

No more health check attempts are made, and Marathon's status regarding HDFS is that there 1 running task, with 0 healthy, 0 staging, and 0 unhealthy.  The above logs seem to indicate proper operation of Mesos.  There are two interesting observations I'd like to make:
* When we see this failure it always follows the pattern above with the stack spew from the health-check followed by a single successful iteration of the health-check.
* The final iteration of the health-check is near the end of the gracePeriod.  The gracePeriod is 300s.  We started at about 19:02:32.  We start the final successful health-check at 19:06:43 and complete it at 19:07:04

Here's a link to the [huge Master logs in their entirety](https://drive.google.com/file/d/0B7T17JhI11rCNUNvLTA3aE5fSzg/view?usp=sharing).
In an excerpt of that log here, we see the Marathon health checker getting started, but when looking at more logs with this ID, I never see any further mention of getting health check results from HDFS.  I see health check results from another framework,  ArangoDB,  but never HDFS.

Is it possible, the akka health-check actor is having problems?  I think the above investigation pretty much proves this isn't HDFS's problem.  I'm not sure if it's Mesos's problem.  I'd like not to bounce back and forth between Mesos and Marathon teams anymore.  If there's something I'm doing that's illegal in my health-check, let me know.  It's a simble cmd line command.  It produces an exit code.  It seems like the fault must lie elsewhere.  This problem has been haunting the HDFS framework for a long time now.  I'd like to see if somehow a resolution can be found.

**Comment by gabrielhartmann** [comment] 2015-09-30 23:24
Nevermind.  There are overlapping healthchecks going on.  It looks like [the one spewing a stack trace did timeout](https://gist.github.com/gabrielhartmann/c7db0f2fe5b63356b5db#file-gistfile1-txt-L331).  This happened while the last one was running and then succeeded.  My bad.  Closed forever.

**Closed by gabrielhartmann** 2015-09-30 23:24 UTC
Labels: bug

**Comment by kolloch** [comment] 2015-10-01 07:59
Hey @gabrielhartmann, even though it eventually turned out to be something else, thanks for excellent info provided with the last comment! 

Just some comments to debug something like this in the future and to decide which component (Mesos, Marathon) is "responsible". The COMMAND health checks (as opposed to HTTP health checks) are executed by Mesos. The "actor" in Marathon doesn't really make much in this case. Marathon is dependent on getting the health info from Mesos via a task status update.

If you grep the master log with `grep "hdfs\\." logs.txt | grep TASK`, you will see:

```
Sep 30 19:02:48 ip-10-0-7-233.us-west-2.compute.internal mesos-master[1242]: I0930 19:02:48.484849  1251 master.cpp:4069] Status update TASK_RUNNING (UUID: 80d4134b-de09-4bc7-9631-c4bac2cb76fa) for task hdfs.ce956568-67a5-11e5-baa4-7643f8838a73 of framework 20150930-184507-3909550090-5050-1242-0000 from slave 20150930-184507-3909550090-5050-1242-S5 at slave(1)@10.0.0.138:5051 (ip-10-0-0-138.us-west-2.compute.internal)
Sep 30 19:02:48 ip-10-0-7-233.us-west-2.compute.internal mesos-master[1242]: I0930 19:02:48.484938  1251 master.cpp:4108] Forwarding status update TASK_RUNNING (UUID: 80d4134b-de09-4bc7-9631-c4bac2cb76fa) for task hdfs.ce956568-67a5-11e5-baa4-7643f8838a73 of framework 20150930-184507-3909550090-5050-1242-0000
Sep 30 19:02:48 ip-10-0-7-233.us-west-2.compute.internal mesos-master[1242]: I0930 19:02:48.485108  1251 master.cpp:5576] Updating the latest state of task hdfs.ce956568-67a5-11e5-baa4-7643f8838a73 of framework 20150930-184507-3909550090-5050-1242-0000 to TASK_RUNNING
Sep 30 19:02:48 ip-10-0-7-233.us-west-2.compute.internal java[1282]: [2015-09-30 19:02:48,485] INFO Received status update for task hdfs.ce956568-67a5-11e5-baa4-7643f8838a73: TASK_RUNNING () (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$4feea61a:100)
```

And then many times reconciliation status updates:

```
Sep 30 19:05:27 ip-10-0-7-233.us-west-2.compute.internal java[1282]: [2015-09-30 19:05:27,202] INFO Received status update for task hdfs.ce956568-67a5-11e5-baa4-7643f8838a73: TASK_RUNNING (Reconciliation: Latest task state) (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$4feea61a:100)
```

None of these contain any health status. If Mesos doesn't pass health status information to Marathon, Marathon cannot act on them.
