### ISSUE TITLE
Is marathon able to deploy, run a script into a docker container and quit

### ISSUE THREAD

**Issue by kopax** [mesosphere/marathon#2828] opened 2015-12-15 17:58 UTC
And possibly delete the instance and image ?

**Comment by philipnrmn** [comment] 2015-12-15 18:19
Hi @kopax,

Marathon is a service for long-running tasks, so isn't really built to do things like this. It *is* possible, you can simply send a `DELETE` to your app endpoint at the end of its command, but it's rather hacky. 

If you're looking to run a script in a docker container on a schedule, check out [Chronos](https://github.com/mesosphere/marathon). If you want a one-off script, there is a tool called `mesos-execute` which comes with Mesos.

**Comment by kopax** [comment] 2015-12-15 19:45
I want to be able to deploy with the rest API.
I am not sure Chronos feat for my needs.
I am able to start the container, run my script, kill and remove by doing this : 

	#!/bin/bash

	echo "Deploying data containers on ${HOSTNAME}"

	ID_DATACONTAINER_IMAGE=$(docker images -a | grep datacontainer | awk '{print $3;}')
	ID_DATACONTAINER_SINGLE_INSTANCE=$(docker ps -a | grep datacontainer | awk '{print $1;}')

	echo "ID_DATACONTAINER_IMAGE: $ID_DATACONTAINER_IMAGE"
	echo "ID_DATACONTAINER_SINGLE_INSTANCE: $ID_DATACONTAINER_SINGLE_INSTANCE"

        /script.sh

	echo "Removing this container and image"
	docker rm -f $ID_DATACONTAINER_SINGLE_INSTANCE & PID_SINGLE_INSTANCE=$!
	docker rmi -f $ID_DATACONTAINER_IMAGE & PID_IMAGE=$!
	wait $PID_SINGLE_INSTANCE
	wait $PID_IMAGE

	exit 0

At this point, the container stop and restart.

**Comment by philipnrmn** [comment] 2015-12-16 10:40
Hi @kopax,

Yes, this is actually Mesos functionality. Mesos will clean up the container after a configurable delay (default 6 hours). The docker image will be held on the node to which it was downloaded, and to the best of my knowledge isn't currently cleaned up by Mesos, so you'd need to take care of this separately.

**Comment by kopax** [comment] 2015-12-16 10:50
@philipnrmn 

Are you speaking about the image removing loop of Mesos ?

This will clean downloaded image to make some free space, it will not prevent from running again and again the restart loop in marathon.

I think something like this should work : 

1. Post to marathon my container
1. Run script inside container
1. Post DELETE to marathon inside container
1. Loop will automatically clean unused downloaded image by Mesos.

**Comment by philipnrmn** [comment] 2015-12-16 12:02
Yes, that sounds like it would work to me. 

I should note again that it isn't exactly the right way to do things - but since the right way would be writing your own Mesos framework, this approach might be your preference.

**Comment by kopax** [comment] 2015-12-16 12:08
The original problem I am trying to solve is to be able to set the container name started with mesos/marathon to have data container using `volumes-from` docker parameter.

**Comment by junneyang** [comment] 2016-04-26 05:51
+1

**Comment by junneyang** [comment] 2016-05-10 02:59
+1
eg: for mysql container, we want to run sql script and quit.

**Comment by gkleiman** [comment] 2016-05-26 13:04
Dupe of #344

**Closed by gkleiman** 2016-05-26 13:04 UTC
Labels: question
