### ISSUE TITLE
Improve CLUSTER constraint documentation

### ISSUE THREAD

**Issue by brentonr** [mesosphere/marathon#2810] opened 2015-12-11 17:47 UTC
**Was**: "Changing CLUSTER constraint results in stuck deployment"
**Summary**: The explanation of the CLUSTER constraint is not clear enough. It does not explain that Marathon will wait for enough resources to start _all_ the app's tasks in nodes that satisfy the constraint before starting/stopping tasks.

We have an existing application with a CLUSTER constraint matching ["server_class","CLUSTER","oldValue"].

Changing the value to a different value (i.e. ["server_class","CLUSTER","newValue"]) with a PUT or via the UI causes offers to be rejected, seemingly incorrectly, and the deployment to get stuck:

```
Dec 11 17:30:15 ip-10-41-40-130 marathon[18080]: [2015-12-11 17:30:15,093] INFO Offer [20151211-121617-2183670026-5050-2650-O35216]. Constraints for app [/app1] not satisfied.
Dec 11 17:30:15 ip-10-41-40-130 marathon[18080]: The conflicting constraints are: [field: "server_class"
Dec 11 17:30:15 ip-10-41-40-130 marathon[18080]: operator: CLUSTER
Dec 11 17:30:15 ip-10-41-40-130 marathon[18080]: value: "newValue"
Dec 11 17:30:15 ip-10-41-40-130 marathon[18080]: ] (mesosphere.mesos.ResourceMatcher$:marathon-akka.actor.default-dispatcher-7)
Dec 11 17:30:15 ip-10-41-40-130 marathon[18080]: [2015-12-11 17:30:15,126] INFO Offer [20151211-121617-2183670026-5050-2650-O35216]. Insufficient resources for [/app1] (need cpus=0.1, mem=256.0, disk=0.0, ports=([9090, 9091] required), available in offer: [id { value: "20151211-121617-2183670026-5050-2650-O35216" } framework_id { value: "20151211-121617-2183670026-5050-2650-0001" } slave_id { value: "20151211-121617-2183670026-5050-2650-S18" } hostname: "10.41.21.162" resources { name: "ports" type: RANGES ranges { range { begin: 1 end: 65535 } } role: "*" } resources { name: "cpus" type: SCALAR scalar { value: 8.0 } role: "*" } resources { name: "mem" type: SCALAR scalar { value: 14015.0 } role: "*" } resources { name: "disk" type: SCALAR scalar { value: 975.0 } role: "*" } attributes { name: "server_class" type: TEXT text { value: "newValue" } }] (mesosphere.mesos.TaskBuilder:marathon-akka.actor.default-dispatcher-7)
```

I expect that the app would start as a new instance on a slave matching the "server_class" attribute of "newValue", then stop the old app instance on the slave matching "server_class" attribute with "oldValue", and it seems the above message is the root of the problem.

Tested with 0.13.0.

**Comment by brentonr** [comment] 2015-12-11 22:05
I did try changing from CLUSTER to LIKE, and that appears to work.

**Comment by mcoffin** [comment] 2015-12-15 22:39
I'm experiencing this as well. Going to try and fix it.

I can also confirm that it is unique to the `CLUSTER` operator.

# Steps to reproduce

1. Create an application with a `CLUSTER` constraint.
2. Once the application is in a steady-state, change the desired value of the `CLUSTER` constraint.
3. The application will sit in the waiting state and Marathon will reject offers on the basis that the constraints don't fit (even for offers where they should).

**Comment by mcoffin** [comment] 2015-12-16 00:29
Found the cause of the issue. With the `CLUSTER` operator, it is intended to ensure that the *entire* cluster of tasks is running under the same matching attribute. See [ConstraintsChecker.checkAttribute](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/mesos/Constraints.scala#L84-L87).

Therefore, the resistance to deploying part of the application to a different attribute value while the other tasks are running at least appears to be working as intended, though it might violate the Principle of least astonishment.

The fix for this, then, would be to detect when performing an upgrade of an application that changes it's `CLUSTER` constraint, and device a deployment strategy which ensures that the versions of the application running under the old attributes terminate before the creation of the new ones, assuming that this is the intended behavior.

For my use case, however, I think I was intended to just use the `LIKE` operator, since I don't care if two versions of the application are running on new vs old attributes simultaneously.

**Comment by gkleiman** [comment] 2015-12-21 13:09
@mcoffin thanks for the research. I updated the title and added a summary, so that we improve the docs.

**Comment by brentonr** [comment] 2015-12-21 16:08
@mcoffin thanks as well. @gkleiman, updating the docs sounds like a good solution to me - thanks as well.

**Comment by mcoffin** [comment] 2015-12-21 16:25
@gkleiman It would eventually be a good idea to come up with a DeploymentStrategy or something for restarting apps with a `CLUSTER` constraint. It would require downtime, since you couldn't start the new tasks until the old ones had been killed, but  right now there's no way (at least that I could reason about) to change the required value of a `CLUSTER` constraint without fully deleting the application.

In that manner, this might be more than a docs issue, but it's not effecting my use case at all.

**Comment by meichstedt** [comment] 2017-03-06 20:46
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3336. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment] 2017-03-07 12:26
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3336. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Closed** 2017-03-27 07:43 UTC
Labels: docs, enhancement, OKR Usability
