### ISSUE TITLE
can't ⌘+C or Ctrl+C on the Marathon page as it launches "create" dialog

### ISSUE THREAD

**Issue by ghostsquad** [mesosphere/marathon#3065] opened 2016-01-21 18:22 UTC
can't ⌘+C or Ctrl+C on the Marathon page as it launches "create" dialog

**Comment by philipnrmn** [comment] 2016-01-21 18:30
See also #2033, where we decided it was not reproducible. Unfortunately I have since reproduced it.

**Comment by scalp42** [comment] 2016-01-21 19:50
Having the same issue here.

**Comment by pierlo-upitup** [comment] 2016-01-22 11:18
Fixed in https://github.com/mesosphere/marathon-ui/pull/579

**Closed by pierlo-upitup** 2016-01-22 11:18 UTC
Labels: bug, gui, ready for review
