### ISSUE TITLE
Including docker container information and a blank CMD field in an app JSON breaks PUT updates but not POST app creations

### ISSUE THREAD

**Issue by john-dodson** [mesosphere/marathon#1630] opened 2015-06-09 16:02 UTC
If include Docker container information in your JSON and "cmd": "", then using POST to create the app in Marathon will work, but using PUT to update it throws the error:

"AppDefinition must either contain one of 'cmd' or 'args', and/or a 'container'."

If you remove the "cmd": "" from the JSON the PUT update for the app works.

Marathon should behave identically in both cases when "cmd": "" is provided, either throwing an error in both cases or never throwing an error for that. I would argue that it should not throw the error like the current functionality of the POST command.

**Comment by aquamatthias** [comment] 2015-06-16 13:55
Thanks @john-dodson for this report. 
I could reproduce this behavior.
We have different data models for creation and update. 
Obviously the validation logic is not congruent.

**Comment by kolloch** [comment] 2015-06-17 11:01
Hi @aquamatthias , isn't it a duplicated of https://github.com/mesosphere/marathon/issues/1446?
Did you test on master?

**Comment by aquamatthias** [comment] 2015-06-17 11:43
Duplicate of #1446 which is fixed in 0.9.0.

**Closed by aquamatthias** 2015-06-17 11:43 UTC
Labels: reproduced
